### ISSUE TITLE
Matlab R2016b FMU Export in ME and Co-simulation error

### ISSUE THREAD

**Issue by lvanfretti** [CATIA-Systems/FMIKit-Simulink#1]
Hi @t-sommer 

I've got the error shown in the figure below, along what the settings I'm using.

What's my mistake or its this a bug?

Thanks

Luigi

<img width="1379" alt="screenshot 2019-03-07 13 54 13" src="https://user-images.githubusercontent.com/7248948/53958112-80d7f780-40e0-11e9-960e-cf6367f690f8.png">

>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.1.0.441655 (R2016b)

Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 17763)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.1         (R2016b)
Simulink                                              Version 8.8         (R2016b)
Control System Toolbox                                Version 10.1        (R2016b)
Curve Fitting Toolbox                                 Version 3.5.4       (R2016b)
DSP System Toolbox                                    Version 9.3         (R2016b)
Database Toolbox                                      Version 7.0         (R2016b)
Datafeed Toolbox                                      Version 5.4         (R2016b)
Fuzzy Logic Toolbox                                   Version 2.2.24      (R2016b)
Global Optimization Toolbox                           Version 3.4.1       (R2016b)
MATLAB Coder                                          Version 3.2         (R2016b)
MATLAB Compiler                                       Version 6.3         (R2016b)
MATLAB Compiler SDK                                   Version 6.3         (R2016b)
MATLAB Report Generator                               Version 5.1         (R2016b)
Model Predictive Control Toolbox                      Version 5.2.1       (R2016b)
Model-Based Calibration Toolbox                       Version 5.2         (R2016b)
Neural Network Toolbox                                Version 9.1         (R2016b)
Optimization Toolbox                                  Version 7.5         (R2016b)
Parallel Computing Toolbox                            Version 6.9         (R2016b)
Robust Control Toolbox                                Version 6.2         (R2016b)
Signal Processing Toolbox                             Version 7.3         (R2016b)
SimEvents                                             Version 5.1         (R2016b)
Simscape                                              Version 4.1         (R2016b)
Simscape Power Systems                                Version 6.6         (R2016b)
Simulink Coder                                        Version 8.11        (R2016b)
Simulink Control Design                               Version 4.4         (R2016b)
Simulink Design Optimization                          Version 3.1         (R2016b)
Simulink Desktop Real-Time                            Version 5.3         (R2016b)
Simulink Real-Time                                    Version 6.5         (R2016b)
Simulink Report Generator                             Version 5.1         (R2016b)
Stateflow                                             Version 8.8         (R2016b)
Statistics and Machine Learning Toolbox               Version 11.0        (R2016b)
Symbolic Math Toolbox                                 Version 7.1         (R2016b)
System Identification Toolbox                         Version 9.5         (R2016b)
Trading Toolbox                                       Version 3.1         (R2016b)
Wavelet Toolbox                                       Version 4.17        (R2016b)
>>

**Comment by t-sommer** [comment]
Currently you have to configure Visual Studio 2015 as a compiler on Windows with

```
mex -setup
```

We'll update the source code, so it compiles with VS 2012 again.

**Comment by lvanfretti** [comment]
Torsten, actually, this was because an issue due to the default installation of VS 2015.
It is explained in [here](https://www.mathworks.com/matlabcentral/answers/316861-how-do-i-select-visual-studio-c-compiler-using-mbuild-setup-and-mex-setup#answer_283633).

I am able to compile now, thanks for all the help!

<img width="1147" alt="screenshot 2019-03-07 15 37 34" src="https://user-images.githubusercontent.com/7248948/53964205-25f9cc80-40ef-11e9-9865-e63d14fda81b.png">
