### ISSUE TITLE
Issue with loading FMUs into Simulink

### ISSUE THREAD

**Issue by Walshest** [CATIA-Systems/FMIKit-Simulink#100]
When  I am using FMIKIT 2.6 in Simulink  (2018b) I get the following error when importing an FMU -CS 2.0. 

Has this issue been seen before.?I get this error back whenever I press ok or apply. 

![image](https://user-images.githubusercontent.com/45364510/69946983-fb596a80-14ec-11ea-8ab5-8097199277df.png)

**Comment by t-sommer** [comment]
@Walshest, can you reproduce the problem with [FMI Kit 2.7 Alpha 1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.7-alpha.1)?

**Comment by Walshest** [comment]
@t-sommer Thank you for your quick reply. 
I am getting back errors in a lot of functions when I am trying the import in Simulink with 2.7. 
Has the fmikit.jar file been updated for version 2.7? 
![image](https://user-images.githubusercontent.com/45364510/69966429-aa5e6c00-1516-11ea-8bdd-490984deceb1.png)

**Comment by Walshest** [comment]
1. Run initalize.m script in +FMIKit 2.7 alpha 1
2. Open Simulink 2018b
3. Create new simulink model
4. Drag and drop FMU block from "FMIKit_blocks.slx" into the new Simulink project
5. Load a CS FMU 2.0 with a sample time of 1 [s]
6. Click apply or OK and the following error is returned
![image](https://user-images.githubusercontent.com/45364510/70030045-abd87480-15a8-11ea-9ef0-7848ba88a435.png)

Note: I have not been able to reproduce the "Wrong fmikit.jar.... " error today again.

**Comment by t-sommer** [comment]
Did you add the folder that contains `+FMIKit` to the MATLAB path before calling `FMIKit.initialize()`? Also make sure there is no folder on the MATLAB path that is called `FMIKit`.

**Comment by t-sommer** [comment]
Try these commands:

```matlab
% download FMI Kit to the current folder
unzip('https://github.com/CATIA-Systems/FMIKit-Simulink/releases/download/v2.7-alpha.1/FMIKit-Simulink-2.7-alpha.1.zip', 'FMIKit-Simulink-2.7-alpha.1')

% add the folder to the MATLAB path
addpath(fullfile(pwd, 'FMIKit-Simulink-2.7-alpha.1'))

% initialize FMI Kit
FMIKit.initialize()

% open the Bouncing Ball demo
fmikit_demo_BouncingBall
```

**Comment by Walshest** [comment]
Hi @t-sommer, 

I can confirm that I have followed the steps above and I can simulate the bouncing ball FMU. But when I open the dialogue box for the FMU Simulink block and select OK or Apply; I get the error with winqueryreg. 
Do you know what this error is due to or how it can be patched? 
![image](https://user-images.githubusercontent.com/45364510/70042080-94a48180-15be-11ea-8978-6937cc6c51ec.png)

**Comment by t-sommer** [comment]
Can you try again with 60d5eb5a1edd4767c5adea93066d174dd85bbf23?

**Comment by t-sommer** [comment]
As a workaround you can install Visual Studio or a Windows SDK.

**Comment by Walshest** [comment]
@t-sommer, 
This is defiantly weird. I have both Visual Studio express and Windows SDK installed and within the Matlab path (for SDK). 
I have been able to get it to work by manually changing the setSFunctionParameter.m file as you did. 
Thank you !

As a side note I am also having issues with GIT interface. Should the _**fmikit.jar**_ file be included in [GIT ver. 2.7](https://github.com/CATIA-Systems/FMIKit-Simulink/tree/release/v2.7 )? 
Along with _**sfun_fmurun.mexw64**_?

**Comment by t-sommer** [comment]
This fix will be included in the next alpha release together with the pre-built `fmikit.jar` and `sfun_fmurun.mex*` S-functions.
