### ISSUE TITLE
Comment on FMI 2.0.1 compliance in release note of FMI-Kit

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#101]
In FMI 2.0.1 there came severalclarifications compared to FMI 2.0. It would be very good to comment in the release notes, if they are all implemented in FMI-Kit.

**Comment by t-sommer** [comment]
Do you have any specific clarification in mind?

**Comment by chrbertsch** [comment]
It would be good to have a general statement w.r.t compliance with FMI 2.0.1 and comments regarding
* documentation/licensing directory
* prefix of source code FMUs
* location of additional DLLs
* ....

**Comment by t-sommer** [comment]
The updated FMI headers and the new template directory (that allow you to add licenses, DLLs etc.) have been mentioned in the [release notes](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.7).
