### ISSUE TITLE
Provide license information in /docmentation/licenses folder

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#102]
In FMI 2.0.1 there is a new folder /docmentation/licenses forseen to provide license information of included open source software. This helps complying with open source software license conditions when passing FMUs between organizations.
```
documentation // Optional directory containing the FMU documentation
  index.html // Entry point of the documentation
  <other documentation files>
  licenses // Optional directory for licenses license.{txt,html} // Entry point for license information   
   <license files> // For example BSD licenses
```

Especially: BSD-License texts for
- FMI-Kit
- FMI 2.0.1 header files
(is there any other open sources software included?)

**Comment by t-sommer** [comment]
With b194bf7684b1b723f6a075af43ab3320d232e634 you can now provide a template directory that is copied to the FMU, e.g.

```
+ documentation
    + licenses
        - license.txt
        - BSD-2-clause.txt
```

Adding a default license for FMI Kit would create a false sense of compliance since it would not cover the exported model and any copied resources.

**Comment by chrbertsch** [comment]
> 
> 
> With [b194bf7](https://github.com/CATIA-Systems/FMIKit-Simulink/commit/b194bf7684b1b723f6a075af43ab3320d232e634) you can now provide a template directory that is copied to the FMU, e.g.
> 
> ```
> + documentation
>     + licenses
>         - license.txt
>         - BSD-2-clause.txt
> ```
> 
> Adding a default license for FMI Kit would create a false sense of compliance since it would not cover the exported model and any copied resources.

The option to provide a template directory seems to be available only for the grtfmi target. 
It would be very good to provide this also for the rtwsfcnfmi target.

**Comment by chrbertsch** [comment]
> With [b194bf7](https://github.com/CATIA-Systems/FMIKit-Simulink/commit/b194bf7684b1b723f6a075af43ab3320d232e634) you can now provide a template directory that is copied to the FMU, e.g.
> 
> ```
> + documentation
>     + licenses
>         - license.txt
>         - BSD-2-clause.txt
> ```
> 
> Adding a default license for FMI Kit would create a false sense of compliance since it would not cover the exported model and any copied resources.

Using grtfmi.tlc I do not find the template directory or its content in the generated FMU.
