### ISSUE TITLE
Significant simulation performance decrease in comparison to Dymola or native Simulink import block. CS FMU 2.0 - x23 slower!

### ISSUE THREAD

**Issue by Walshest** [CATIA-Systems/FMIKit-Simulink#104]
We have been doing some internal testing on the best way to export from Dymola and import into Simulink. See the snippet from our report regarding simulation speed with FMI Kit. I have tested this again with  version 2.7 without any improvements unfortunately. 
![image](https://user-images.githubusercontent.com/45364510/70312445-f6115e00-1813-11ea-98fe-33c1e3da41e5.png)
It would be possible to share a black box FMU of our model and some sample dynamic data to test.; if interested in solving this bug.

**Comment by t-sommer** [comment]
Yes, please. You can send me an e-mail, if you don't want to share the FMU here.

**Comment by Walshest** [comment]
@t-sommer I have just checked with my company policies and we would need to sign a NDA; before sharing any files even if it is a black box. If you would agree; can you send me an email at Stefan.Walshe@danfoss.com please?

**Comment by Walshest** [comment]
@t-sommer 
I have found a method in order in improve the simulation speed of my large model (CS FMU v2.0). 

### Direct Input
I have found that if I selected _**Direct Input**_ for the FMU it can simulate at speeds that I expect. 
However what does this direct input do to the .FMU (not interpolating the inputs? )
![image](https://user-images.githubusercontent.com/45364510/70453681-7a304380-1aa9-11ea-907e-c20b278b775a.png)

### Relative Tolerance
I have also ran some tests and noticed that adjust the _**Relative Tolerance**_ has no effect on the output of my FMU model and/or simulation speed. 
- When I adjust the FMU error tolerance in the native .FMU block in Simulink it can vastly change the outputs from my model and simulation speed.

**Comment by t-sommer** [comment]
> However what does this direct input do to the .FMU (not interpolating the inputs? )

When you enable "Direct Input", FMI Kit will use the inputs at time t_1 to calculate the outputs at t_1. While this is against the idea of FMI Co-Simulation where you use the inputs at t_0 to calculate the outputs at t_1, it can give better results for some models.

> When I adjust the FMU error tolerance in the native .FMU block in Simulink it can vastly change the outputs from my model and simulation speed.

You should see in the log file if this flag has been passed correctly to the FMU. Please open a new issue if this is not the case.

**Comment by Walshest** [comment]
@t-sommer Do you recommend then simulating with Direct Input enabled then? 

As mentioned with my model: 
- Direct Input disabled (default): Simulation speed 3x Real time
- Direct Input enabled: Simulation speed 0.11x Realtime 
  - Similar to FMU Import with Dymola and native Simulink FMI Import

I have added another issue for tollerance: #106

**Comment by t-sommer** [comment]
[FMIKit-Simulink-5464a6.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3951008/FMIKit-Simulink-5464a6.zip) is a build, that behaves like the native CS FMU import, i.e.

- no input port direct feedthrough
- no input derivatives
- inputs are set in mdlUpdate()

Can you give it a try?

**Comment by t-sommer** [comment]
> Do you recommend then simulating with Direct Input enabled then?

The "Direct Input" option has been removed in [2.7 Alpha 3](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.7-alpha.3) and the direct input feedthrough is now set automatically [as described in the docs](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/release/v2.7/docs/fmu_import.md#calling-sequence) which should give you results comparable to Simulink's native import.

**Comment by t-sommer** [comment]
Please re-open if you can reproduce the problem with the latest alpha.

**Comment by Walshest** [comment]
Hi Torsten, 

Thank you for your fast fix. I can confirm that that following issues have been solved in [FMIKit v2.7-rc.1](https://github.com/CATIA-Systems/FMIKit-Simulink/tree/v2.7-rc.1 ) and are working perfectly for me: 
- Direct Input has been removed; which was causing a speed degradation of x23 when compared to simulating the FMU in Dymola. 
- Relative tolerance can now be set within CS FMU and works as expected. 
- Simulation results from FMIKit match those from native Simulink FMU block.

I can now recommend this toolbox internally for FMU Importing into Simulink :)
Thank you for your great work.
