### ISSUE TITLE
FMU Export with GRT Target: Issues with Visible Parameters and Initial Value of Outports

### ISSUE THREAD

**Issue by Batemo-Karlsruhe** [CATIA-Systems/FMIKit-Simulink#105]
I played around with the GRT target recently. It works great, I really like it! However, there were two issues I was not able to resolve.
I used the following model for testing: [testing_model.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3931554/testing_model.zip).

**1.) Visible Parameters**
I attached a simple model that contains one integrator block, one gain parameter p and and a bias parameter q. In configuration under "Code Generation" / "FMI" / "Visible parameter" I set just p as the visible parameter (see _01_Visible_Parameter_Config.png_). However, after building the FMU all parameters are visible in the FMU (see _02_Visible_Parameter_Result.png_).
When I tried to debug, I realized that the function `grtfmi_exclude_variable` that probably removes parameters that are not supposed to be visible is not even called in my case. Any idea what potentially goes wrong there?

**2.) Initial Outport Values**
In the attached model, the implicit fixed-step solver "ode14x" is used. The outport is not direct feed-through. However, when the FMU is simulated with p=1 and q=1, the very first simulated value of the outport is 0 (see _03_Initial_Outport_Result.png_). This is wrong, it should be 1. 
When I tried to debug, I saw that I can set the start value of the outport in the FMU mask of the FMI Kit. Nevertheless I think this behavior is unwished: In my example the outport can be uniquely calculated for the initial condition. Moreover not all simulation environments the FMU is imported to offer the opportunity to set the start value of the outport.
Is there a way how the model can be changed so that the initial value of outport is calculated?

**Comment by t-sommer** [comment]
Regarding 2.): the outputs of a GRT model are `0` until `model_step()` is called.

**Comment by Batemo-Karlsruhe** [comment]
Regarding 2.): OK, this explains the behavior. Can you give me more details why it is implemented like that?

In the Co-Simulation calling sequence of FMI 2.0 in the initialization mode the "... state equations are active to determine all outputs (...). The variables that can be retrieved by `fmi2GetXXX` calls are ... variables with `causality = "output"`." That is why I do not understand why all outputs are initialized as zero.
In my application the initial zero outputs cause problems in models the FMU is imported into because there are outputs of physical quantites that are nonzero when the simulation starts (e.g. a voltage of a capacitor or a surface temperature of a body). Thus, the wrong initial zeros that the FMU outputs falsify the following simulation.

Please let me know if I can support in any way!

**Comment by t-sommer** [comment]
> Can you give me more details why it is implemented like that?

It's the way the GRT generates code (this has nothing to do with FMI). As a workaround you could write a script that simulates on step to calculate the outputs and set these values start values.

**Comment by Batemo-Karlsruhe** [comment]
**Regarding 1.) Visible Parameters**
I took some time to look at the bug. In one TLC file is not checked which parameters are supposed to be included and that is why they show up in the FMU later. Without having a deeper understanding of the whole project it seems that in the file **grtfmixml.tlc** the line 99
`%assign vr = OutputParameterFMI(param, vr)`
must be replaced with the four following lines:
```
%if FEVAL("grtfmi_exclude_variable", "%<param.Identifier>", "%<VisibleParameters>")
   %continue
%endif
%assign vr = OutputParameterFMI(param, vr)
``` 
I performed some small tests and it seems to work. Nevertheless please thoroughly check if this is really correct.
Moreover, I think it would help the user if the tooltip of the "Visible Parameters" field would define the format in which the parameters must be inputted. Therefore I recommend to change the respective line in the file **grtfmi.tlc** to:

`rtwoptions(i).tooltip = 'Parameters to include in the model description as space separated list (e.g. p1 p2 p3). Leave empty to include all.';`

**Comment by t-sommer** [comment]
With `2.8-alpha.1` I get the expected results. Please reopen if you find any problems.
