### ISSUE TITLE
Max / Min attributes missing in modelDescription.xml

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#107]
If I set limits in inputs or integrators, they might be compiled into the FMU binary, but they are not published in the modelDescription as max / min attributes. Please add that functionality.

**Comment by t-sommer** [comment]
Can you share an example model and the expected XML?

**Comment by Spiegel-Leser** [comment]
Sure, see mail to you. I'm not sure the syntax in the modified XML is correct, I have no correct example as a template. But it's easy to see the attributes were totally missing in the original XML.

**Comment by Spiegel-Leser** [comment]
Sure, see attached. I'm not sure the syntax in the modified XML is
correct, I have no correct example as a template. But it's easy to see
the attributes were totally missing in the original XML. See p. 40 / 41
from the specification for the expected existance of these attributes in
the XML.


Am 02.01.2020 um 09:21 schrieb Torsten Sommer:

**Comment by t-sommer** [comment]
> Sure, see attached.

You can pack the files as a ZIP and drag it onto the text field to share it here or e-mail me directly if you can't.

**Comment by Spiegel-Leser** [comment]
ok, this is the example I meant to send
[Test_limits.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4037335/Test_limits.zip)

**Comment by Spiegel-Leser** [comment]
and this is the specification
[FMI-Specification-2.0.1.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4037344/FMI-Specification-2.0.1.zip)

**Comment by Spiegel-Leser** [comment]
This is a reminder, please add function to publish input limits and state limits in FMU-XML.

**Comment by t-sommer** [comment]
This is already implemented for `grtfmi.tlc` and will be added to `rtwsfcnfmi.tlc` in the next release.

**Comment by Spiegel-Leser** [comment]
Cool, I'll hyppily beta-test it. Just tell me when it's in the current source code.

**Comment by t-sommer** [comment]
@Spiegel-Leser, can you check again with `develop`?

**Comment by Spiegel-Leser** [comment]
I checked but creation of the FMU fails. The message is

The call to rtwsfcnfmi_make_rtw_hook, during the after_make hook
generated the following error: Undefined function or variable
'grtfmi_dir'. The build process will terminate as a result.

    Caused by:
  * Undefined function or variable 'grtfmi_dir'.

Also, FMIKit.initialize() answers with 2.7, not 2.8.


Am 24.04.2020 um 22:44 schrieb Torsten Sommer:

**Comment by Spiegel-Leser** [comment]
Sorry, been very busy. Now I checked, issue is unresolved.

**Comment by t-sommer** [comment]
> Could you please split this into a separate thread? The error message with grtfmi.dir in sfcnfmi (!) for 2.8 Alpha1&2 happens regardless of min/max values.

This problem has been fixed with 2f0e50cfa50f180cd76dfa473dbc30451c34b7e3.

**Comment by Spiegel-Leser** [comment]
I tested, yes, now it works! Also min/max values are correctly inserted into the XML.
<Real start="0" min="47.0" max="130.0"/>
I ask for another enhancement: Could you, in this case of limits that don't allow 0, choose the limit nearest to 0 for such an input start value?

**Comment by t-sommer** [comment]
> I ask for another enhancement: Could you, in this case of limits that don't allow 0, choose the limit nearest to 0 for such an input start value?

Please open a new issue.
