### ISSUE TITLE
FMU export in Windows

### ISSUE THREAD

**Issue by andrealuisv** [CATIA-Systems/FMIKit-Simulink#108]
When trying to export an FMU from Simulink in Windows, I get the following error: 'Unable to locate template makefile: rtwsfcnfmi_18b_lcc64.tmf'. Is there any solution for this? It's similar to a unix error from what I've read...

**Comment by t-sommer** [comment]
Visual Studio is the only supported compiler for `rtwsfcnfmi.tlc` on Windows. You can try `grtfmi.tlc` which let's you use any compiler supported by CMake.

**Comment by Cleanbud** [comment]
Hi, I selected the grtfmi.tlc but I am still not able to export an FMU. First I got an error message that FMUArchive folder is missing inside the _grt_fmi_rtw folder, so I created it and didn't get the error. I get a different error message now '
_The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    SubSystem block does not have a parameter named 'CMakeCompilerOptimizationLevel'_'

I set the compiler optimization level to Disabled
