### ISSUE TITLE
Supress / Remove "_sf"

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#109]
The S-Function target produces all files with an additional _sf in the filename, which is copied to the FMU file name and is used internally, too. I'd like an option to either supress the _sf from the beginning or remove (rename) it after the S-Function building part, before making the FMU.

**Comment by t-sommer** [comment]
Solved with 81dcabf94b2e81787d7ea013bb2d1d5f232b9123
