### ISSUE TITLE
Error getting/setting start values via Matlab FMIKit.getStartValue & FMIKit.setStartValue

### ISSUE THREAD

**Issue by Maverick1182** [CATIA-Systems/FMIKit-Simulink#115]
Hi,

I'm having an issue following the documented instruction of getting a start value of a variable in the Simulink FMI wrapper. 

K>> **FMIKit.getStartValue(gcb, 'JICE')**
Error using FMIKit.showBlockDialog
Too many input arguments.

Error in FMIKit/getStartValue (line 14)
dialog = FMIKit.showBlockDialog(block, false);

I get a similar issue when trying to set a value

K>> **FMIKit.setStartValue(gcb,'JICE',0)**
Error using FMIKit.showBlockDialog
Too many input arguments.

Error in FMIKit/setStartValue (line 34)
dialog = FMIKit.showBlockDialog(block, false);

**Comment by t-sommer** [comment]
The functions work for me in [2.7 alpha 3](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.7-alpha.3):

```
>> fmikit_demo_BouncingBall
>> gcb

ans =

    'fmikit_demo_BouncingBall/BouncingBall'

>> FMIKit.getStartValue(gcb, 'e')

ans =

    '0.7'

>> FMIKit.setStartValue(gcb, 'e', '5e-1')
>> FMIKit.getStartValue(gcb, 'e')

ans =

    '5e-1'
```

Please reopen if you can provide steps to reproduce the issue with the latest alpha.

**Comment by Maverick1182** [comment]
Hi Torsen, 

Actually I'm using the stable 2.6 release, would you recommend moving to the unstable alpha?

**Comment by t-sommer** [comment]
Yes, definitely. 2.7 is about to be released soon and brings a lot of fixes and improvements. We're not planning any changes for the release, only urgent bug-fixes if necessary.

`fmikit_demo_BouncingBall` is part of the FMI Kit distribution (just run the command).

**Comment by Maverick1182** [comment]
OK will do, one strange thing I found was the KIT didn't appear to add a simulink library automatically , and I had to navigate to the installed folder in AppData and then open the library and then copy the Import block.... is this an indication of a broken install? I simply ran the appinstaller and it ran without error and initialises without issues as well....

**Comment by chrbertsch** [comment]
@Maverick1182 with the app-installer of 2.6 you have klick on the installed app icon to initialize it. You can also automatize this as described here: https://github.com/CATIA-Systems/FMIKit-Simulink/issues/36

**Comment by t-sommer** [comment]
Upon multiple request we changed the distribution back to the plain old ZIP file. See [Quick start](https://github.com/CATIA-Systems/FMIKit-Simulink/tree/release/v2.7#quick-start) for instructions.

**Comment by Maverick1182** [comment]
> @Maverick1182 with the app-installer of 2.6 you have klick on the installed app icon to initialize it. You can also automatize this as described here: #36

Thanks, I did this already.

And 

> Upon multiple request we changed the distribution back to the plain old ZIP file. See [Quick start](https://github.com/CATIA-Systems/FMIKit-Simulink/tree/release/v2.7#quick-start) for instructions.
> 
> UPDATE: make sure you update the download link to the latest pre-release.

Yup, noticed the different distribution method from the documentation, and yes changed the references to refer to alpha.3

**Comment by Maverick1182** [comment]
Just tried with the common bouncing ball example and still have similar issue despite using alpha.3

K>> gcb

ans =

    'fmikit_demo_BouncingBall/BouncingBall'

K>> FMIKit.getStartValue(gcb, 'e')
Error using FMIKit.showBlockDialog
Too many input arguments.

Error in FMIKit/getStartValue (line 14)
dialog = FMIKit.showBlockDialog(block, false);

**Comment by t-sommer** [comment]
Can you add the output of the `ver` command?

**Comment by Maverick1182** [comment]
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.5.0.944444 (R2018b)
MATLAB License Number: 40640518
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 15063)
Java Version: Java 1.8.0_152-b16 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------

**Comment by t-sommer** [comment]
I can't reproduce the problem with R2018b on Windows. Make sure you don't have any other FMI Kit folders on your MATLAB path or any FMI Kit Apps installed.

**Comment by Maverick1182** [comment]
I've removed the stable release's mention in the path, 

restarted matlab , and trying to run the command, I can some extra information? 

>> FMIKit.getStartValue(gcb, 'e')
**Warning: Attempt to execute SCRIPT slblocks as a function:
C:\Program Files (x86)\Dymola 2017\Mfiles\FMIKit_for_Simulink\import\slblocks.m** 
Error using FMIKit.showBlockDialog
Too many input arguments.

Error in FMIKit/getStartValue (line 14)
dialog = FMIKit.showBlockDialog(block, false);

**Comment by t-sommer** [comment]
`C:\Program Files (x86)\Dymola 2017\Mfiles\FMIKit_for_Simulink\import` (an old FMI Kit installation folder) still seems to be on your MATLAB path for some reason.

**Comment by Maverick1182** [comment]
Hi Torsen, 

This appears to have been the issue, there was a stale line in the matlab path with this old folder location, removing it and running 2.7 appears to at least allow the getstartvalue command to work now 

>> FMIKit.getStartValue(gcb, 'e')

ans =

    '0.7'

Thanks for the support!
