### ISSUE TITLE
Create a list of all current variables and their respective values in FMU

### ISSUE THREAD

**Issue by Maverick1182** [CATIA-Systems/FMIKit-Simulink#116]
Apologies for asking this in the issues forum, however I'm new to GitHub and can't find a location where one can ask general questions nor are there any contact details to get in touch with the developer (other than for commercial use).

I wanted to know if there is a way to extract the full list of variables in the FMU together with their values? 

Currently the only method would be to use FMIKit.getStartValue(FMUBLOCK, 'Variablename'); but that requires knowledge of the variable in advance. Instead I want to generate a list of all the variables and their values just before I start the simulation (for sim debugging purposes)

**Comment by t-sommer** [comment]
[StackOverflow ](https://stackoverflow.com/) is the right place for this type of question. Please ask it there and link from this issue for reference.

**Comment by Maverick1182** [comment]
Will do. Thanks for the direction.

**Comment by t-sommer** [comment]
@Maverick1182, can you share the link to your question on StackOverflow?

**Comment by Maverick1182** [comment]
[https://stackoverflow.com/questions/59659711/create-a-list-of-all-current-variables-and-their-respective-values-in-fmikit-sim](url)
