### ISSUE TITLE
mexErrMsgIdAndTxt unsupported

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#117]
In S-Functions we use 'mexErrMsgIdAndTxt'  to generated an error message when values of variables are outside allowed ranges. This method does not seem to be supported for FMU generation with FMI-Kit. Is there a way to map this function (or a workaround) to an FMI error message?

**Comment by t-sommer** [comment]
Can you provide an example model / S-function?

**Comment by t-sommer** [comment]
The functions in `mex.h` are not available when exporting code with the GRT target.
