### ISSUE TITLE
Importing a source code FMU with static libraries fails

### ISSUE THREAD

**Issue by mdempse1** [CATIA-Systems/FMIKit-Simulink#118]
We are trying to import a source code FMU generated by Dymola but the FMI Kit fails to compile the FMU as it doesn't link in the static libraries.  We get the following error message after clicking Apply on the FMU dialog box.  How can we specify the static libraries that should be linked in as part of this compilation process?

Compiling S-function modelname
Building with 'Microsoft Visual C++ 2013 (C)'.
Failed to compile S-function
  Creating library sfun_modelname.lib and object sfun_modelname.exp
all.obj : error LNK2019: unresolved external symbol fcnName_1 referenced in function_name
all.obj : error LNK2019: unresolved external symbol fcnName_2 referenced in function_name
all.obj : error LNK2019: unresolved external symbol fcnName_3 referenced in function_name

**Comment by t-sommer** [comment]
Can you share an example model and FMU?

**Comment by t-sommer** [comment]
You can specify additional (static) libraries under `Configuration Parameters > Code Generation > Custom Code > Libraries`:

![static_library](https://user-images.githubusercontent.com/2453858/71984870-fc876100-3229-11ea-8b90-7c79a0633859.png)

**Comment by mdempse1** [comment]
As far as I know those options only work when exporting a model with Simulink Coder.  I don't think that works when we're importing the source code FMU and it is being compiled for use within Simulink.

If you look in the function +FMIKit/private/applyDialog.m the mex command is setup to compile the source code FMU but doesn't specify any link options.

**Comment by federicodaros** [comment]
I've attached a simple example to prove the problem.:
[testExternData.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4039810/testExternData.zip)
The model is using the open source ExternData Library, available on GitHub https://github.com/modelica-3rdparty/ExternData

**Comment by t-sommer** [comment]
For Simulink internal use you can specify static libraries under `Configuration Parameters > Simulation Target > Libraries`:

![static_library](https://user-images.githubusercontent.com/2453858/72082952-50b14480-3301-11ea-8af2-dc0236bf9e21.png)

**Comment by federicodaros** [comment]
That doesn't have any effects to me.
It seems the FMI kit is ignoring the information included in the panel you are pointing at when compiling the S-function (i.e. button "OK" or "Apply" on the FMU dialog box).

**Comment by t-sommer** [comment]
@mdempse1, @federicodaros, can you give 1d46c10a1616a02ad04721aed711ee30379db86d at try?
