### ISSUE TITLE
Avoid warning about precision loss in fmi2SetReal by explicitly casting to REAL32_T

### ISSUE THREAD

**Issue by fchucholowski** [CATIA-Systems/FMIKit-Simulink#123]
In fmi2SetReal, the compiler issues a warning, since a double is converted to a single, which causes precision loss. In this case, this is desired, so we should explicitly cast to REAL32_T.
(see https://github.com/CATIA-Systems/FMIKit-Simulink/pull/122)

**Comment by t-sommer** [comment]
Solved with 5bb99833d330509495fd6ab0d2a149bf39d458dd.
