### ISSUE TITLE
Libraries and additional source files provided via rtwmakecfg.m are not considered during build

### ISSUE THREAD

**Issue by fchucholowski** [CATIA-Systems/FMIKit-Simulink#125]
When custom s-functions are used inside a Simulink model, they can provide additional source files or libraries via an rtwmakecfg.m file, that resides in the s-function's directory.
Currently none of the information provided by these functions is considered when creating an FMU, which causes the build to fail.

A possible solution would be to always use all source files, headers and libraries provided by the buildInfo structure (see https://github.com/CATIA-Systems/FMIKit-Simulink/pull/120).

**Comment by bazcoIndustries** [comment]
@fchucholowski , this line doesn't work when no external libraries are present:
`custom_library = {buildInfo.getLinkObjects.Name}';`
Suggest changing it to
```
if ~isempty(buildInfo.getLinkObjects)
  custom_library = {buildInfo.getLinkObjects.Name}';
else
  custom_library = {};
end
```

Your solution then ran and generated the CMakeCache, but our project uses a block generated by the Legacy Code Tool where the additional sources were specified using relative paths---relative to the directory when the user last ran the Legacy Code Tool, not the build directory.  Therefore those extra sources cannot be found.

I looked at the rtwmakecfg.m generated by Legacy Code Tool, and it does have the source files listed, but the root-level function in that file does NOT return the source files--only the directories, which is useless.  The only way I could see to use the file directly would be to parse it.

An alternate solution that works for our project, is to parse the Simulink block description field, which also has the source and include files, then locate the files in the search path, as shown here. (Add this to grtfmi_model_sources.m around line 27.)

```
% Add any Legacy Code Tool source files that were not added as SFunctionModules
for i = 1:numel(sfcns)
    block = sfcns{i};
    p = get_param(block, 'ObjectParameters');
	
    % First sign of Legacy Code Tool block: Has a non-empty mask
    if ~isfield(p, 'MaskObject'), continue; end
    mo = get_param(block, 'MaskObject');
    if isempty(mo), continue; end
	
    % Second sign of Legacy Code Tool block: Type is Legacy Function
    if ~strcmp(mo.Type, 'Legacy Function'), continue; end
	
    fprintf('Found legacy code tool block: %s\n', block);

    % Legacy Code Tool produces a description containing the def structure
    % as MAT code.  Parse it to obtain the source files as a cell array,
    % i.e. {'foo.c', 'bar/baz.c'}
    [tok, ~] = regexp(mo.Description, 'def\.SourceFiles = (\{[^\n)]*\})*', 'tokens');
    % Skip if didn't parse properly
    if isempty(tok)
        warning('Could not parse source files of Legacy Code Tool block %s', block);
        continue
    end
	
    sourceFiles = eval(tok{1}{1});
    fprintf('\tAdding source modules: %s\n', java.util.Arrays.toString(sourceFiles));
    sourceFilesLocated = cellfun(@which, sourceFiles, 'UniformOutput', false);
    fprintf('\tAbsolute paths:        %s\n', java.util.Arrays.toString(sourceFilesLocated));
    sources = [sources sourceFilesLocated(:)'];

    [tok, ~] = regexp(mo.Description, 'def\.HeaderFiles = (\{[^\n)]*\})*', 'tokens');
    % Skip if it didn't parse properly
    if isempty(tok)
        warning('Could not parse include files of Legacy Code Tool block %s', block);
        continue
    end

    includeFiles = eval(tok{1}{1});
    includesLocated = cellfun(@which, includeFiles, 'UniformOutput', false);
    includeDirs = unique(cellfun(@fileparts, includesLocated, 'UniformOutput', false));
    fprintf('\tAdded include dirs:    %s\n', java.util.Arrays.toString(includeDirs));

    include = [include includeDirs(:)'];
end
```

Fragile, but it does the job for us.

**Comment by bazcoIndustries** [comment]
@fchucholowski Thank you for posting this.  I made a few modifications to your patch to handle when the library list is empty and to find the absolute paths of unqualified file names added by the Legacy Code Tool.  This solution seems to be working well.
