### ISSUE TITLE
Getting the following when using 2.7.0 RC1 having added the new install directory with subfolders in Matlab

### ISSUE THREAD

**Issue by Maverick1182** [CATIA-Systems/FMIKit-Simulink#127]
when running the initialising command

 FMIKit.initialize()

The output gives

**Initializing FMI Kit 2.7.0**
Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION".

Error in FMIKit.getBlockDialog (line 9)
libraryVersion = char(fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION);

Error in FMIKit.showBlockDialog (line 18)
dialog = FMIKit.getBlockDialog(block);

Error in FMIKit.loadFMU (line 9)
dialog = FMIKit.showBlockDialog(block, false);

Error in RunAllGearShifts_Variant_RunSims (line 223)
    FMIKit.loadFMU(FMUBLOCK, InputFiles.fmufile)

No such issue using 2.7.0 Alpha3

**Comment by chrbertsch** [comment]
I do not have this issue (in ML/SL 2016B)

**Comment by t-sommer** [comment]
@Maverick1182, can you double check that RC1 is _the only_ FMI Kit folder on your MATLAB path?

**Comment by Maverick1182** [comment]
Sorry for the delay in reply. I definitely only have the rc1 folder and subfolders in the path of Matlab (2018b) 

On closing and rebooting, the error now appears when calling 

FMIKit.loadFMU(FMUBLOCK, InputFiles.fmufile)

Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION".

Error in FMIKit.getBlockDialog (line 9)
libraryVersion = char(fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION);

Error in FMIKit.showBlockDialog (line 18)
dialog = FMIKit.getBlockDialog(block);

Error in FMIKit.loadFMU (line 9)
dialog = FMIKit.showBlockDialog(block, false);

Error in RunAllGearShifts_Variant_RunSims (line 223)
    FMIKit.loadFMU(FMUBLOCK, InputFiles.fmufile)

**Comment by t-sommer** [comment]
If you cannot run the commands in [Quick start](https://github.com/CATIA-Systems/FMIKit-Simulink#quick-start) in a clean working directory there's probably something wrong with your MATLAB path.

**Comment by Maverick1182** [comment]
All the commands from the Quick Start run fine. I assume the 2.7 zip is identical in content to the 2.7rc1 available in the download section?

**Comment by t-sommer** [comment]
> {'C:\Projects\GearboxSimulationTool\Simulink\FMIKit-Simulink-2.7-rc.1\Java\src' }

This file is source code, not a compiled distribution. You should use the `FMIKit-Simulink-<version>.zip` from the releases.

**Comment by Maverick1182** [comment]
OK, I see, apologies, I'd gone from the last stable > Alpha3 > Rc1. 

Will note it for the future, but curious as to why the RC1 had issues (not so pressing now given I have a new build that works).
