### ISSUE TITLE
GRT export: Parameter and Port with same name

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#129]
In Simulink it is allowed to have a port in the model with the same name as a workspace variable that is used as a parameter. When such a model is used to generate an FMU with the grtfmi target, the resulting FMU has two ScalarVariable entries in the modeldescription that have the same name. This is not allowed.

**Comment by t-sommer** [comment]
Would it be okay to enforce unique names in the model instead of pre-fixing the variable names in the modelDescription.xml?

**Comment by fajansen** [comment]
For my models it would be ok. But as it is allowed in Simulink I would not expect to have to kind of limitation imposed by "some export target", there is a high risk of deterring possible users from using FMIKit.

**Comment by t-sommer** [comment]
We can use the same approach as for `rtwsfcnfmi.tlc`: prefix parameters with `Parameters.`, no prefix for inputs and outputs.
