### ISSUE TITLE
mex64 compilation successfull but ...

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#13]
After some adaptations to the `CMakeLists.tx`t and `build.bat` bat file. i.e.:

- adapt to available visual studio version:
`cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE=Release ..`

- change to MATLAB  path to 2015b:
`set(MATLAB_DIR "C:/Program Files/MATLAB/R2015b" CACHE STRING "MATLAB install directory")`

mex64 and compilation in general will succeed. 
the succeding MATLAB call as: 
`matlab -nodisplay -nosplash -wait -r "matlab.apputil.package('FMIKit.prj'); exit()"`
will return an error:

`Error using matlab.apputil.package (line 50)
Java exception occurred:
com.mathworks.project.api.InvalidProjectException: File fmi1.c from Files included through analysis does not exist.`

A second try, by running `initialize_fmikit.m` will return an error as well: 
`Warning: Invalid file or directory 'C:\FMIDS\FMIKit-Simulink\fmikit.jar'.`

Therefore I wonder: 

- What are the toolchain dependencies to build the project? 
- What's wrong with our build process? 
- is there a reason for hard coded (Specific) MATLAB and Visual Studio Versions in the bat and cmake file? 

Thanks in advanced!

**Comment by t-sommer** [comment]
You have to build the `fmikit.jar` first using Maven:

```
call mvn -f Java/pom.xml install
```

**Comment by t-sommer** [comment]
> is there a reason for hard coded (Specific) MATLAB and Visual Studio Versions in the bat and cmake file?

No. For the next release we're planing to ship the .jar and .mex* files precompiled with R2012b.

**Comment by jbernalr** [comment]
Thanks.
Using `jdk1.8.0_201`, `apache-maven-3.6.0` and MATLAB/2015b:

`fmikit.jar` will compile successuflly. 

Still after the call:
`matlab -nodisplay -nosplash -wait -r "matlab.apputil.package('FMIKit.prj'); exit()"`

MATLAB will return: 
`Error using matlab.apputil.package (line 50)
Java exception occurred:
com.mathworks.project.api.InvalidProjectException: File fmi1.c from Files included through analysis does not exist.`

However this time: calling `initialize_fmikit` will initialize the kit with the only issue being, not adding the root installation directory to the path. 
After adding it manually it will work. (Lastest was done by the installer automatically)


Thanks

**Comment by t-sommer** [comment]
Thanks for your help. We'll fix the build and documentation for the next release. If you build everything locally you can just add the FMIKit folder to the MATLAB path and call `FMIKit.initialize()` directly.
It's not a requirement to build the App Installer.

**Comment by t-sommer** [comment]
The app installer build has been removed from the build script. Instead of building the binaries you can copy the `fmikit.jar` and `sfun_fmurun.mex*` from the latest app installer (it's just a ZIP file).
