### ISSUE TITLE
Option to allow use of Default Experiment Tolerance in FMU, even when in Model Exchange is selected

### ISSUE THREAD

**Issue by Maverick1182** [CATIA-Systems/FMIKit-Simulink#130]
Reading the documentation, it appears the relative tolerance value reported in the advanced option tab is only available in CoSimulation FMUs.

Is it possible to allow the user to set a tolerance value to be used even if the FMU is run in model exchange? 

I am aware of some other FMU wrappers that at least allow the user to specific that the system should query the default tolerance value attribute within the FMU and to use that for simulations, even in model exchange. 

I am seeing that the same FMU generates slightly different results when using the FMI-Kit versus another FMU wrapper package.

I am told the alternative package allows the use of this internal tolerance parameter whilst I assume KMI-Kit is not , as stated in the documentation. Would it be possible to "unlock" this option to see if this solves the divergence in results between the two packages?

**Comment by t-sommer** [comment]
For Model Exchange FMUs the relative tolerance is the value of `RelTol` for variable step and `0` for fixed step solvers.

**Comment by Maverick1182** [comment]
Where do I find and set this value, does it simply have to be set in the workspace or is it park of the UserData structure that the documentation speaks of? 

https://github.com/CATIA-Systems/FMIKit-Simulink/blob/v2.7-rc.1/docs/fmu_import.md
