### ISSUE TITLE
SSP support?

### ISSUE THREAD

**Issue by meek1** [CATIA-Systems/FMIKit-Simulink#131]
@t-sommer, @chrbertsch Any plans on implementing SSP support as part of FMIKit? I.e. enable import and export of FMI composite model architecture and parameterization, compliant with the SSP standard?

https://ssp-standard.org/

**Comment by t-sommer** [comment]
Please re-open when an example is available (see also https://github.com/CATIA-Systems/FMPy/issues/104)

**Comment by meek1** [comment]
@lochel OMSimulator has SSP support to some extent. Would it be possible and relevant to provide the basis for that implementation as an example here?
