### ISSUE TITLE
can‘t find 'grtfmi.tlc' and 'rtwsfcnfmi.tlc'

### ISSUE THREAD

**Issue by qilianshanlgz** [CATIA-Systems/FMIKit-Simulink#135]
I have executed the code ‘unzip(['https://github.com/CATIA-Systems/FMIKit-Simulink/releases/' ...
  'download/v2.7/FMIKit-Simulink-2.7.zip'], 'FMIKit-Simulink-2.7')..........’
But I can‘t find 'grtfmi.tlc' and 'rtwsfcnfmi.tlc' in 'System target file'  of simulink.
How to set path of 'FMI Kit 2.7' in MATLAB?

**Comment by t-sommer** [comment]
Can you share the full command line output?

**Comment by qilianshanlgz** [comment]
> Can you share the full command line output?
I have exceuted executed the code as following：
---------------------------------------------------------
unzip(['https://github.com/CATIA-Systems/FMIKit-Simulink/releases/' ...
  'download/v2.7/FMIKit-Simulink-2.7.zip'], 'FMIKit-Simulink-2.7')
addpath(fullfile(pwd, 'FMIKit-Simulink-2.7'))
FMIKit.initialize()
---------------------------------------------------------
The default path is ‘C:\MATLAB\R2018b\bin’ when I run MATLAB on my PC.
So 'FMIKit-Simulink-2.7' was unziped in ‘C:\MATLAB\R2018b\bin’
My puzzle is which path should I unpack FMIKit-Simulink-2.7 to, then I can  find 'grtfmi.tlc' and 'rtwsfcnfmi.tlc' in 'System target file' of simulink.

**Comment by t-sommer** [comment]
Just change to a working directory where you have write access before running the above commands.
