### ISSUE TITLE
Define description string for inputs and outputs

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#137]
It would be helfpful to define the optional "description" string for inputs and outputs of FMUs generated with FMI-Kit.
E.g., for outputs the "signal name" could be used for this purpose
![grafik](https://user-images.githubusercontent.com/16363372/73018204-6d7d6a00-3e21-11ea-9d73-b66d74ac90e5.png)

Reason: in some FMU importing tools  (e.g., GT-Suite) the description string is primarily displayed and not the input or output "name".

For this use case it would also suffice to have an option to generally set the "description" string to the same name as the "name" string of an input or an output of the FMU generated with FMI-Kit.

**Comment by t-sommer** [comment]
see #55
