### ISSUE TITLE
Creation of fmikit.jar?

### ISSUE THREAD

**Issue by joaha058** [CATIA-Systems/FMIKit-Simulink#138]
is is possible to create the fmikit.jar without using intelliJ? For example from the command line in linux? or using eclipse?

In our development environment there are a limited number of tools and it is not so simple to install new tools.

**Comment by t-sommer** [comment]
You can build the fmikit.jar with Maven using the [pom.xml](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/Java/pom.xml).
