### ISSUE TITLE
grtfmi.tlc: error while exporting power system blocks

### ISSUE THREAD

**Issue by F-Perabo** [CATIA-Systems/FMIKit-Simulink#140]
While exporting an electrical power system model including components such as
- three-phase dynamic load
- RMS
- Fourier

from the Simscape library, an error is thrown and the FMU cannot be exported:
`sfun_discreteVariableDelay.obj : error LNK2019: unresolved external symbol rt_mxGetEps referenced in function mdlOutputs`

All of the before mentioned blocks are including the S-Function "sfun_discreteVariableDelay" which seems to cause the error. Does the FMIKit support exporting these blocks and how could this error be solved?

Attached you find the full error log and an example Simulink model (remove the .zip-extension).
[Error Simulink Export FMI Kit.txt](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4140251/Error.Simulink.Export.FMI.Kit.txt)
[mytest.slx.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4140255/mytest.slx.zip)

Software Configuration:
- Matlab R2019b, Update 4
- Catia Dymola FMI Kit 2.7
- Virtual Studio 2019
- Windows 10

**Comment by t-sommer** [comment]
I don't have the "Simscape Electrical" package available to export you example. It seems like there's a source file missing in the CMake project that contains the definition of `rt_mxGetEps`. Can you also share the exported `*_grt_fmi_rtw` folder?

**Comment by chrbertsch** [comment]
@F-Perabo : do you get the same error when you use the grt.tlc target from Mathworks?

**Comment by F-Perabo** [comment]
@t-sommer: here you can find the `*_grt_fmi_rtw` folder: [mytest_grt_fmi_rtw.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4146876/mytest_grt_fmi_rtw.zip)

@chrbertsch: there is no error using the grt.tlc target

**Comment by F-Perabo** [comment]
I just figured out how to solve the problem. The file `matlabroot/rtw/c/src/rt_matrx.c` that is containing the definition of the function `rt_mxGetEps` has to be manually added as a custom source in the model (absolute path):

Configuration Parameters > Code Generation > Custom Code > Additional build information > Source files

After adding this parameter, the linking error will be solved.

**Comment by F-Perabo** [comment]
@t-sommer:  45b2c4f is working fine for me, thanks a lot
