### ISSUE TITLE
make process fails on one machine

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#141]
On one machine the fmu build fails during Linking because the command "mt" is unknown, see attached log.

On another machine it works, though there is the same line in the makefile:

FMI_MT  = mt -manifest $(MODEL)_sf.dll.manifest -outputresource:$(MODEL)_sf.dll;2

Full makefile attached
[Test_limits_20200227_145757.txt](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4267094/Test_limits_20200227_145757.txt)
working
[Test_limits.mk.txt](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4267097/Test_limits.mk.txt)
not working
[Test_limits2.mk.txt](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4267132/Test_limits2.mk.txt)

**Comment by t-sommer** [comment]
The TMF build for the rtwsfcnfmi.tlc target will be replaced with a CMake build in the next release (see https://github.com/CATIA-Systems/FMIKit-Simulink/tree/feature/rtwsfcnfmi-cmake-mi).
