### ISSUE TITLE
Run initializeModelVariables in Initialization mode, not in Instantiate

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#142]
Currently fmi2Instantiate calls the initializeModelVariables function of Simulink, which in turn calls the mdlStart and mdlInitializeConditions callbacks.

These callbacks are used to initialize the continuous states using the s-function parameters.
When changing a parameter, the parameter value is only set after fmi2Instatantiate and fmi2SetupExperiment, so the initialisation happens with the wrong values.

Please call initializeModelVariables in fmi2EnterInitializationMode instead.

**Comment by fajansen** [comment]
This is about the export, not the import.

**Comment by t-sommer** [comment]
@fajansen, can you check if 7e081e1d7e5ab1327d759640d19170ea8f1f11ff works for you?

**Comment by fajansen** [comment]
Works fine
