### ISSUE TITLE
Wrong datatype for boolean parameters

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#143]
I have a model with a Gain block of gain 1. The block is connected to a logical operator, and the output datatype is set to Inherit via backpropagation.
In the generated code, the parameter is of type uint8_T, has dtypeID=14, and a value of 128U. In the modelDescription it shows up as Integer start="128".
When executing the FMU, the call to fmi2GetInteger to read this value fails, as the dTypeID is not SS_UINT8 (=3).

**Comment by t-sommer** [comment]
Can you share your example model?

**Comment by t-sommer** [comment]
@fajansen, can you give 73418bce5c6d51c311fc186037714ef460fe601b a try?

**Comment by fajansen** [comment]
With this version, it is possible to simulate the FMU. Now it is only confusing that the 1 gets converted to 128 in the model description.

**Comment by t-sommer** [comment]
`128U` is the start value Simulink uses in the generated code in `boolparam_data.c`:

```c
/* Block parameters (default storage) */
P_boolparam_T boolparam_P = {
  /* Computed Parameter: Gain_Gain
   * Referenced by: '<Root>/Gain'
   */
  128U
};
```
