### ISSUE TITLE
Nested FMU problem

### ISSUE THREAD

**Issue by StefanMa-hub** [CATIA-Systems/FMIKit-Simulink#146]
Hi all,
I have a problem using the nested FMU feature. When using a nested FMU with only a gain in the inner FMU, the whole FMU works like expected, but when I use an integrator in the inner FMU, the model outputs of this inner FMU are all 0. 
Best regards
Stefan

**Comment by t-sommer** [comment]
Can you share the Simulink model and the FMUs to reproduce the problem?

**Comment by StefanMa-hub** [comment]
I shared the files with you via mail, see mail from 16.03.2020 14:12, shall I also attach the files here to this issue?

**Comment by t-sommer** [comment]
@StefanMa-hub, can you please try again with the latest version of `develop`?

**Comment by StefanMa-hub** [comment]
this works, thank you
