### ISSUE TITLE
FMIKit fails to generate 32-bit binary FMU

### ISSUE THREAD

**Issue by miracle8510** [CATIA-Systems/FMIKit-Simulink#147]
I have successfully used FMIKit2.7 in 64-bit Matlab / Simulink (Matlab2017a) to generate a 64-bit binary FMU, which is indeed useful. However, now other simulation tools need to use 32-bit binary FMU for co-simulation, I follow the following way:
[https://ww2.mathworks.cn/help/coder/ug/build-32-bit-dll-on-64-bit-windows(r)-platform-using-msvc-toolchain.html?s_tid=srchtitle](url)
Added a 32-bit compiler toolchain to 64-bit Matlab.
In addition, Intel-> x86-32 (Windows32) is selected for Hardware Implementation, and rtwsfcnfmi.tlc is selected for System Target File. The FMI Option sets the output to a Co-Simulation type FMU.
However, in fact, the FMU generated by FMIKit is still a 64-bit binary FMU.
My guess is that FMIKit automatically chose a 64-bit compiler during the compilation and linking process. What do I need to do to modify the FMIKit configuration file (such as a .tlc file) or Matlab / Simulink to generate a 32-bit binary FMU?
Thank you very much for your efforts in promoting FMIKit！

**Comment by t-sommer** [comment]
Which target are you using to export the FMU, `grtfmi.tlc` or `sfcnrtwfmi.tlc`?

**Comment by miracle8510** [comment]
sfcnrtwfmi.tlc：
Ctrl+B to generate FMU：
Diagnostic Viewer Info：


Best Regards
景传奇
汽车电子应用工程师
 
 
From: Torsten Sommer
Date: 2020-03-23 17:47
To: CATIA-Systems/FMIKit-Simulink
CC: miracle8510; Author
Subject: Re: [CATIA-Systems/FMIKit-Simulink] FMIKit fails to generate 32-bit binary FMU (#147)
Which target are you using to export the FMU, grtfmi.tlc or sfcnrtwfmi.tlc?

**Comment by t-sommer** [comment]
@miracle8510, can you accept the answer on StackOverflow and close this issue?

**Comment by miracle8510** [comment]
OK，Thank you！


Best Regards
景传奇
汽车电子应用工程师
 
 
From: Torsten Sommer
Date: 2020-04-16 06:36
To: CATIA-Systems/FMIKit-Simulink
CC: miracle8510; Mention
Subject: Re: [CATIA-Systems/FMIKit-Simulink] FMIKit fails to generate 32-bit binary FMU (#147)
@miracle8510, can you accept the answer on StackOverflow and close this issue?
