### ISSUE TITLE
FMU export in MATLAB R2018b

### ISSUE THREAD

**Issue by Cleanbud** [CATIA-Systems/FMIKit-Simulink#149]
Hi, I tried using the grtfmi.tlc to export an FMU but got an error message that FMUArchive folder is missing inside the _grt_fmi_rtw folder. So I created the folder at that location and didn't get the error again. 
After trying again, I get a different error message now 
'The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
SubSystem block does not have a parameter named 'CMakeCompilerOptimizationLevel''

I set the compiler optimization level to Disabled.

Could you let me know what you think of it.

**Comment by t-sommer** [comment]
@Cleanbud, please provide steps to reproduce the problem.

**Comment by Cleanbud** [comment]
Thanks for your reply!

1) I create a folder having the model and related header files
2) I load all the parameters in the workspace
3) I unzip the FMIKit folder to C:\Temp
4) In Matlab workspace I write:
addpath(' C:\temp\FMIKit-Simulink-master\FMIKit-Simulink-master');
FMIKit.initialize();
5) If I select grtfmi.tlc then I get the above error and if I select rtwsfcnfmi.tlc then I get the same error as in https://github.com/CATIA-Systems/FMIKit-Simulink/issues/108

Please let me know what you think about it.

Thanks,

**Comment by t-sommer** [comment]
Can you reproduce this problem with [v2.8-alpha.2](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/download/v2.8-alpha.2/FMIKit-Simulink-2.8-alpha.2.zip)? Also make sure you don't have multiple FMIKit directories on the MATLAB path.

**Comment by t-sommer** [comment]
Please reopen if the problem persists.
