### ISSUE TITLE
Invalid modelDescription for block parameters that are fields of structures

### ISSUE THREAD

**Issue by marpulli** [CATIA-Systems/FMIKit-Simulink#151]
If I set a block parameter to be a field of a structure as below:
<img width="496" alt="Screenshot 2020-04-02 at 16 39 01" src="https://user-images.githubusercontent.com/33632490/78268697-77e27100-7500-11ea-890f-5ce340179281.png">

The `modelDescription.xml` file has no `start` value for this parameter so `fmpy` fails to import the FMU:
![Screenshot 2020-04-02 at 16 44 34](https://user-images.githubusercontent.com/33632490/78269244-3dc59f00-7501-11ea-8996-3e596f3ac517.png)

This happens whether the variable in the base workspace is a simulink parameter object, or a matlab structure.

Keeping groups of parameters together as a structure is often a neat way of organising them - it would be great if FMIKit could support exporting models where this is the case.

Attached example model:
[WaveGenExample.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4422093/WaveGenExample.zip)

**Comment by t-sommer** [comment]
To work around the problem you can access the field by name:

```
simulink.('Amplitude')
```

**Comment by t-sommer** [comment]
@marpulli, is the above workaround acceptable for you?

**Comment by t-sommer** [comment]
This issue is a duplicate. Closing in favor of #74.
