### ISSUE TITLE
Support the simulation of 32bit FMUs in a 64bit ML/SL

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#156]
Would it be possible to port the remoting feature of fmpy to FMI-Kit?

**Comment by t-sommer** [comment]
With FMPy you can add the remoting binaries to any `win32` FMU, so you can run them in `win64` MATLAB.

**Comment by chrbertsch** [comment]
Ah, now I understand. Great!
