### ISSUE TITLE
Wrong target in generating tool string 

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#159]
FMI-Kit 2.8alpha, for an FMU generated with Target  rtwsfcnfmi.tlc target

![grafik](https://user-images.githubusercontent.com/16363372/80098006-7559c100-856c-11ea-8a96-b5457becf3e3.png)

for a ME FMU , one gets displayed as generation tools the wrong target and the wrong version number.

![grafik](https://user-images.githubusercontent.com/16363372/80098077-93272600-856c-11ea-8490-d433b759b7cd.png)

**Comment by t-sommer** [comment]
Solved with 4c089583327968818c94d5552e21d333378c1890
