### ISSUE TITLE
Expose selected parameters from black box FMU

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#16]
I want to expose some (but not all) parameters so they are tunable by the user of the FMU.

There is currently a way to do this. One can set the "Default parameter behaviour" under "Optimization/Signals and Parameters" to "Inlined", and then use the "Configure..." button to make selected parameters tunable (set to "ExportedGlobal"). Then, when "Generate black-box FMU" is not enabled, only the selected parameters are visible in the generated FMU.

However, there are some side-effects:
1. The internal states of the integrators and their derivatives are now named after the block name, and not "concealed", leaking information about the internal structure of the FMU.
2. As the non-visible parameters are now inlined, the generated code is different than when not inlining them. We have a model that crashes, when the parameters are inlined.

It would be great to be able to build a black box FMU and then have a list of parameters that are made visible, without affecting the actual generated code.

**Comment by t-sommer** [comment]
@fajansen, would the "Visible parameters" approach of the `grtfmi.tlc` target work for you?

**Comment by fajansen** [comment]
Yes, that would be ideal!

**Comment by t-sommer** [comment]
@fajansen, can you give c44fabb55ea3c2b7d0ef910675423817058ce97b a try?

**Comment by fajansen** [comment]
Works for me!
