### ISSUE TITLE
Clarify FMI 3.0 export capability in FMI-Kit 2.8.alpha

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#160]
It is possible to select FMI version "3" in the grtfmi.tlc target, but this is not documented.

It is great to see progress towards FMI 3.0 support in FMI-Kit, but it would be better to name this "3.0alphaX" and add a description of the capabilities and limitations in the FMU export documentation.

The exported 3.0 cannot be loaded with fmpy 0.2.9
![grafik](https://user-images.githubusercontent.com/16363372/80340372-ce716f80-8860-11ea-88c7-56a871b3df30.png)

**Comment by t-sommer** [comment]
As of v2.8 the FMI 3 version suffix is now exported in the modelDescription.xml
