### ISSUE TITLE
Debug Build

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#162]
Please provide an option to build a debuggable FMU (provide debug symbols).

**Comment by t-sommer** [comment]
@fajansen, can you give 436ba930987253ec4bfbe9c440ad3655b96c4911 a spin?

**Comment by fajansen** [comment]
Works. Another great improvement would be to include the generated .pdb in the resources folder of the fmu

**Comment by t-sommer** [comment]
> Works. Another great improvement would be to include the generated .pdb in the resources folder of the fmu

@fajansen, can you try ce68e737a6665f07d920ab87e01102f9c9f2681a?

**Comment by fajansen** [comment]
Works like a charm, thank you!
