### ISSUE TITLE
Multiple Instances of FMU fails.

### ISSUE THREAD

**Issue by Jiter** [CATIA-Systems/FMIKit-Simulink#163]
I tried to use the same FMU twice in a Simulation.

There seems to be an Issue with Instantiating more than one Instance of an FMU.

**Steps:**
Import FMU 
Use FMIKit FMU Import Block in submodel.
Choose FMU
Use submodel twice.
When trying to Simulate following Message appears:

> The S-Function block 'harness/FMU' is not supported in multi-instance Normal mode because it does not declare that it supports multiple execution instances. If the S-Function satisfies the multiple execution instances requirements, you can declare this using the SimStruct function 'ssSupportsMultipleExecInstances' in the 'mdlSetWorkWidths' method.

I tried the same FMU with the Simulink FMU-Blocks and I can use it in expected way.

**Comment by t-sommer** [comment]
Can you share an example model, maybe based on `fmikit_demo_BouncingBall` to reproduce the problem?
