### ISSUE TITLE
Nested FMUs for 32bit

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#164]
I am using 64bit Matlab/Simulink. I want to create a nested FMU, and export to a 32bit FMU. As the inner FMU probably needs to be 32bit as well, I created a 32bit FMU. When triggering the build it fails with the following message:

Error reported by S-function 'sfun_fmurun':
The current platform (Windows 64-bit) is not supported by the FMU

**Comment by t-sommer** [comment]
This should be resolved since ShLwApi.lib is linked via `#pragma comment(lib, "shlwapi.lib")` now.
