### ISSUE TITLE
Link error when exporting FMU on Linux

### ISSUE THREAD

**Issue by Tony607** [CATIA-Systems/FMIKit-Simulink#165]
Link error happens during exporting the SIMULINK model to FMU on Ubuntu Linux. I have successfully exported other simpler SIMULINK models(such as the SIMULINK  "[Aircraft Longitudinal Flight Control](https://www.mathworks.com/help/simulink/slref/aircraft-longitudinal-flight-control.html)" example) on the same Linux machine.

The same SIMULINK file can be successfully exported to FMU file on Windows 10 (64bit) with MATLAB R2019b but failed on Linux.

- OS: Linux - Ubuntu 18.04.2 LTS
- MATLAB Version: R2020a Linux 64bits
-  FMIKit-Simulink Version: [2.8 Alpha 1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.8-alpha.1)
- Simulink Coder target: `grtfmi.tlc`
- Fixed-step size: 0.001
- cmake version: cmake-3.15.2-Linux-x86_64

Export FMU error log on Ubuntu Linux,
```
[100%] Linking C shared library hydraulic_servo_valve.so
/usr/bin/ld: libmc.a(mc_15d12d95.c.o): relocation R_X86_64_PC32 against symbol `mc__BJ1NEDJTgOMhaJKDrM6pN' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/hydraulic_servo_valve.dir/build.make:839: recipe for target 'hydraulic_servo_valve.so' failed
make[2]: *** [hydraulic_servo_valve.so] Error 1
The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Unknown error occurred.

The build process will terminate as a result.
Caused by:
Unknown error occurred. 
```

Full error log file on MATLAB:
[hydraulic_servo_valve_linux_build_error.log](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4584662/hydraulic_servo_valve_linux_build_error.log)

SIMULINK file
[hydraulic_servo_valve.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4584736/hydraulic_servo_valve.zip)

Linux build folder
[hydraulic_servo_valve_grt_fmi_rtw.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4584767/hydraulic_servo_valve_grt_fmi_rtw.zip)

**Comment by t-sommer** [comment]
Does the problem still exist with [v3.0-alpha.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.1)?

**Comment by t-sommer** [comment]
Please reopen if the problem persists with [v3.0-beta.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-beta.1).
