### ISSUE TITLE
nested FMU: snprintf not found with VS2013

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#167]
When building a FMU from a model that contains another FMU with FMIKit 2.8 alpha2 with Visual Studio 2013 I get the following error message:
`sfun_fmurun.cpp(841): error C3861: 'snprintf': identifier not found `
The same model works with VS2015.

If VS2013 is not supported, please remove it from the cmake options.

**Comment by t-sommer** [comment]
Exporting a model with nested FMUs requires a new Visual Studio version than 2013. However this is not a general limitation of the FMU export.
