### ISSUE TITLE
nested FMU: Access violation

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#168]
I have a model that imports an FMU and want to export it as FMU. The export (with FMIKit2.8 alpha2) works fine, but when I try to simulate the FMU it crashes with an access violation.

Example will be sent by mail.

**Comment by fajansen** [comment]
Any news on this?

**Comment by t-sommer** [comment]
The problem seems to be that the path for the binary of the nested FMU is still pointing to an absolute path. This error is reported via ssSetErrorStatus() but it's not forwarded to the parent FMU.

**Comment by t-sommer** [comment]
As a workaround you can keep the unzip directory of the nested FMU (or create it on the target machine), so the S-function can use the hard-coded path.

**Comment by t-sommer** [comment]
@fajansen, can you give 9f1ba6c1680c1a833590f12d555a7bed62d25c0c a spin?

**Comment by StefanMa-hub** [comment]
tested the build with new sfun_fmurun.cpp file, fmu is not crashing any more

**Comment by sibitvm** [comment]
Hello, I am facing a similar access violation issue when tried to import and simulate the nested FMU in Simulink. Please find the attachment of my sample trial.
[Ex_Nested_fmu.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/8368247/Ex_Nested_fmu.zip)
