### ISSUE TITLE
Provide option to set cmake CMAKE_GENERATOR_TOOLSET (-T)

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#169]
Please provide an option to set the CMAKE_GENERATOR_TOOLSET. It should be passed as parameter -T in the call to cmake, i.e.
` status = system(['"' command '" -G "' generator '" -T"' toolset '" "' strrep(grtfmi_dir, '\', '/') '"']);`
in line 105 of grtfmi_make_rtw_hook.m

**Comment by fajansen** [comment]
For some reason the FMU generated from our model takes twice the time to compute with VS2015 and newer than with VS2013. With VS2019 and LLVM/CLANG the FMU is faster than with VS2013, and this change would enable us to use LLVM with FMIKit

**Comment by t-sommer** [comment]
@fajansen, can you give 97da763 a try?

**Comment by fajansen** [comment]
The Line
`toolset_option = [' -T "' toolset ' "'];`
should be
`toolset_option = [' -T "' toolset '"'];`
Then it works. (there is a space too much between the toolset and the ")
