### ISSUE TITLE
 Invalid file error of 2.8 Alpha 2 

### ISSUE THREAD

**Issue by Satinelamp** [CATIA-Systems/FMIKit-Simulink#171]
I got an error when using FMI Kit 2.8 Alpha 2 in MATLAB 2020a on Win10.
Warning: Invalid file or directory 'xxx/FMIKit-Simulink/fmikit.jar'.
But the version 2.7 works fine, I guess there is something wrong with the 2.8 Alpha 2 version.

**Comment by t-sommer** [comment]
If you download the sources, you have to build the binaries (generic S-functions and fmikit.jar) yourself.

Please use the pre-built [FMIKit-Simulink-2.8-alpha.2.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/download/v2.8-alpha.2/FMIKit-Simulink-2.8-alpha.2.zip) instead.
