### ISSUE TITLE
S-Function from Source Code Incorrect Inputs

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#174]
Not sure if this problem is fixed in another branch, but the inputs when building an S Function from code are not matching the normal inputs. When generating the S-Function from source code, all input are flattened to a list of single inputs, creating a new port for each signal in a vector. Also, the feed through settings are different.

**Comment by t-sommer** [comment]
@Marvin-TMG, can you give 24eef6a14384c1f7cee9a6130e6dc6eb71ec5860 a spin?

**Comment by Marvin-TMG** [comment]
Seems to work correctly now, thanks!
I am not sure about the feedthrough settings (maybe keep it open until confirmed), since I was not able to run the S-Function, there seems to be another issue, but the port dimensions are correct at least.
