### ISSUE TITLE
Problems when switching FMU

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#175]
There are some problems when switching FMU's in the GUI:
- Changing FMU often leads to the error that the new FMU can not be unzipped. Furthermore, the 'old' unzip folder is kept, which is probably not desired
- Changing the FMU or changing the unzip directory name also does not remove the references in the build settings to the previous FMU path

It is also probably cleaner to collect all FMU's under a specific subfolder, similar to how Matlab's native implementation does this (i.e. slprj/{GUID}/), to avoid creating various folders in the model root directory, every time a new FMU is loaded.

**Comment by t-sommer** [comment]
You can change the directory where the FMU is extracted under `Advanced > Unzip directory` in the block dialog (e.g. to `slprj/...`).

If you load / reload an FMU, the block will remember all its settings (start values, custom outputs, unzip directory, etc.) which is very convenient when e.g. updating to a newer version of the same FMU.

However, if you load a different FMU, you should delete the block and create a new one.

**Comment by Marvin-TMG** [comment]
Hi Torsten,

The problem is that the paths do not get updated automatically after you change it and the build info is also not cleaned properly sometimes.

Kind regards,

Marvin

**Comment by t-sommer** [comment]
> The problem is that the paths do not get updated automatically after you change it and the build info is also not cleaned properly sometimes.

This is tricky because this information is shared with other blocks in the model. Please re-open this issue if you have an idea how to solve this in a robust way.
