### ISSUE TITLE
2.7 sfcn FMU export not working (with R2019a)

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#176]
I'm using Matlab R2019a Upd. 7, Visual Studio 2015, all x64, and tested FMIKit 2.7, using rtwsfcnfmi.tlc, rtwsfcnfmi_tmf

The template makefile, [...]\rtwsfcnfmi\tlc\rtwsfcnfmi_18b_vcx64.tmf, must contain the |>COMPILER_COMMAND_FILE_NAME<| token if the corresponding toolchain, "MinGW64 | gmake (64-bit Windows)", has corresponding values for the RequiresCommandFile and NoCompilerCommandFile attributes.
The toolchain attributes are:

    RequiresCommandFile = true
    NoCompilerCommandFile = false

As the message has "_18b_" perhaps that is the reason, at least it works with R2018a. So perhaps a warning message should be integrated into 2.7, that it doesn't work with > R2018b ? Or is something else amiss?

**Comment by t-sommer** [comment]
The TMF build will be superseded by a CMake build in v2.8 that supports R2012b - R2020a. There will be no more updates to the TMF build.
