### ISSUE TITLE
Make description editable

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#18]
The description attribute of the fmiModelDescription in the modelDescription.xml is set to "S-function with FMI generated from Simulink model xxxx" as standard.
Making this editable (same way as the author attribute) would allow to give a meaningful description to the users of the FMU.

**Comment by t-sommer** [comment]
How about using `Model Properties > Description` directly?

**Comment by fajansen** [comment]
That would also be a good solution!

**Comment by t-sommer** [comment]
Solved with ae2c26616abc40d58313dcf90b856d890baf18d2

**Comment by t-sommer** [comment]
This does not work with RTWSFCNFMI yet

**Comment by t-sommer** [comment]
Solved with 81dcabf94b2e81787d7ea013bb2d1d5f232b9123
