### ISSUE TITLE
Reoccuring problem with FMU-Export via rtwscfnfmi

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#180]
Building the FMU with R2019a, VS 2015, FMIKit 2.8a2 fails with some models with this message:

The call to rtwsfcnfmi_make_rtw_hook, during the after_make hook
generated the following error: Undefined function or variable
'grtfmi_dir'. The build process will terminate as a result.

    Caused by:
  * Undefined function or variable 'grtfmi_dir'.

I compared a working .slx with a problematic one and synchronized all settings, as far as I can see. I also tried removing the temporary build files.

I'd upload the files to the developers, but not publicly.

**Comment by t-sommer** [comment]
@Spiegel-Leser, you can send the files to torsten.sommer@3ds.com if you can't share them here.

**Comment by Spiegel-Leser** [comment]
Thx for the support. Info for all: Development version is NOT latest alpha version. My mistake.

With the current dev version the problem is fixed.
