### ISSUE TITLE
FMU export: Matlab R2019b freezes when building model

### ISSUE THREAD

**Issue by BrotKolben** [CATIA-Systems/FMIKit-Simulink#184]
Hello, 

I'm trying to build the (very simple) attached Model as 32Bit FMU using **grtfmi.tlc**.
Currently, when selecting Build Matlab freezes and I have to close it with the Task Manager. Any ideas?
BR

[diff.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4856892/diff.zip)

**Comment by t-sommer** [comment]
What's the output on the MATLAB console if you build with `rtwbuild(gcs)`?

**Comment by t-sommer** [comment]
The attached model builds fine with e73221964bddb14ac352936ba98c57c9d9730da2 and the selected in R2020a.
