### ISSUE TITLE
Support "ExportedGlobal" storage class

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#185]
Example sent via E-Mail

**Comment by fajansen** [comment]
Thanks for the fast improvement. Since writing the ticket I found out how to set the storage Class also for signals. Either programmatically
`ph=get_param(blockname,'PortHandles'); set_param(ph.Outport,'StorageClass','ExportedGlobal');`
or manually (right click on signal, Properties, Code Generation, Storage class Exported Global - Signal must have a name for this to work).
Can you also support this?

**Comment by t-sommer** [comment]
@fajansen, can you please open a new issue and attach an example model?
