### ISSUE TITLE
Unable to set start values

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#189]
I have a model and it throws an error when it is unable to set starting values. The model terminates, but when avoiding the termination call, the simulation continues just fine.

See the log below, where the asset_ok in fmu_common was commented out to avoid model termination.

### setStartValues
#[0] VR: 100664336 - V: 0.000000
#[1] VR: 100763020 - V: 1.000000
#[2] VR: 100763027 - V: 1.000000
#[3] VR: 100763036 - V: 1.000000
#[4] VR: 100763038 - V: 1.000000
#[5] VR: 100763220 - V: 1.000000
#[6] VR: 100763242 - V: 1.000000
#[7] VR: 436207687 - V: 1.000000
fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
#[8] VR: 436207683 - V: 1.000000
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
#[9] VR: 436207679 - V: 1.000000
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
#[10] VR: 436207675 - V: 1.000000
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
#[11] VR: 436207671 - V: 1.000000
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored
#[12] VR: 436207687 - V: 1.000000
fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
#[13] VR: 436207683 - V: 1.000000
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
#[14] VR: 436207679 - V: 1.000000
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
#[15] VR: 436207675 - V: 1.000000
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
#[16] VR: 436207671 - V: 1.000000
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored
#[17] VR: 369201367 - V: 1.000000
#[18] VR: 436207687 - V: 1.000000
fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
#[19] VR: 436207683 - V: 1.000000
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
#[20] VR: 436207679 - V: 1.000000
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
#[21] VR: 436207675 - V: 1.000000
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
#[22] VR: 436207671 - V: 1.000000
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored
#[23] VR: 352321558 - V: 0.000000
#[24] VR: 335544329 - V: 1000.000000

**Comment by t-sommer** [comment]
Can you share the part of the modelDescription.xml where the above variables are declared?

**Comment by Marvin-TMG** [comment]
Work-around in sfun_fmu_common.c, remove the ASSERT_OK call in the function setStartValues() 

```
    // scalar start values
    for (i = 0; i < mxGetNumberOfElements(SCALAR_START_VALUES_PARAM); i++) {

		type = (int)SCALAR_START_TYPES[i];
		vr = (FMI_API(ValueReference))SCALAR_START_VRS[i];

		switch (((int)SCALAR_START_TYPES[i])) {
        case REAL:
			real_value = SCALAR_START_VALUES[i];
            FMI_API(SetReal)(COMPONENT, &vr, 1, &real_value);
			// ASSERT_OK(FMI_API(SetReal)(COMPONENT, &vr, 1, &real_value), "Failed to set real start value")
			break;
        case INTEGER:
			integer_value = (FMI_API(Integer))SCALAR_START_VALUES[i];
			FMI_API(SetInteger)(COMPONENT, &vr, 1, &integer_value);
            // ASSERT_OK(FMI_API(SetInteger)(COMPONENT, &vr, 1, &integer_value), "Failed to set integer start value")
			break;
        case BOOLEAN:
			boolean_value = SCALAR_START_VALUES[i] != 0;
            FMI_API(SetBoolean)(COMPONENT, &vr, 1, &boolean_value);
			// ASSERT_OK(FMI_API(SetBoolean)(COMPONENT, &vr, 1, &boolean_value), "Failed to set boolean start value")
			break;
        }
    }
```

**Comment by t-sommer** [comment]
The variables you're trying to set are local variables (e.g. `VR=436207687`). Setting these variables results in undefined behavior. If you want to change them you have to make them parameters or inputs.

**Comment by Marvin-TMG** [comment]
These settings are baked into the FMU for some reason, no idea why. None the less, running this model in FMIKit without the 'source code' option checked works just fine, with the same warnings below, but it does not terminate. Also, when using the native Matlab FMI block, it works fine as well. Matlab's implementation seems to ignore these variables alltogether and does not show any references to it in their log.

This is the log when running it in FMIKit with the option "source code" unchecked:

fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207687# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207683# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207679# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207675# at this stage, setting of variable ignored
fmiSetReal: may not change #r436207671# at this stage, setting of variable ignored

Could you change  sfun_fmu_common.c accordingly?

**Comment by Marvin-TMG** [comment]
Never mind, the problem seems to have dissapeared after reinstalling FMIKit and deleting all blocks folders and settting everything up from scratch. No idea why this happened, seems all fine now, you can close this topic.
