### ISSUE TITLE
Set unzip directory path

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#19]
In some cases I get that unzipping is not possible when trying to load an FMU.
One example is: If you have a Simulink model open with an FMU imported, and create a new Simulink model where you want to import the same FMU.
Would it be possible to make the unzip-directory configurable in the "load FMU" mask=

**Comment by t-sommer** [comment]
You can set the unzip directory in the FMU block dialog under `Advanced > Unzip Directory` before you select `Load` or `Reload`. If this does not work for you please provide step-by-step instructions how to reproduce the issue.

**Comment by chrbertsch** [comment]
Works fine. (Never had seen this option before.)
