### ISSUE TITLE
Runtime Crash dSpace Scalexio due to ssGetTFinal 

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#190]
It seems that on the dSpace Scalexio, the value obtained via ssGetTFinal is a large negative number, when Inf is specified in Matlab. This straight away terminates the FMU at the first doStep call.

**Comment by t-sommer** [comment]
Solved with 08ad1ade7f2b3006a44fc01b16b7e2f3e0488708.

**Comment by Marvin-TMG** [comment]
Thanks, this should work indeed. I will try it as soon as possible.
Can you change it in sfun_fmu_fmi2_me.c as well (and possibly v1 also for consistency)?
