### ISSUE TITLE
Print diagnostics dSpace Scalexio

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#193]
On the dSpace Scalexio the diagnostics are not printed. A possible fix is to modify sfun_fmu_common.c as follows:

```
#ifdef ssPrintf
#undef ssPrintf
#endif
#define ssPrintf printf

#if FMI_VERSION == 1
#define FMI_API(F) fmi ## F
#define ASSERT_OK(F, M)  if (F != fmiOK) { printf(M); ssSetErrorStatus(S, M); return; }
#elif FMI_VERSION == 2
#define FMI_API(F) fmi2 ## F
#define ASSERT_OK(F, M)  if (F != fmi2OK) { printf(M); ssSetErrorStatus(S, M); return; }
#endif
```

**Comment by t-sommer** [comment]
Wouldn't it be a better solution to implement `ssSetErrorStatus()` on the target system? Printing to the console is generally not a good idea.

**Comment by Marvin-TMG** [comment]
Yes, maybe a better idea. For the moment we can just define it like so on a local branch.
