### ISSUE TITLE
Simulink generated Co-simulation FMUs fails in Reset() function

### ISSUE THREAD

**Issue by manasdas17** [CATIA-Systems/FMIKit-Simulink#196]
I'm trynig to simulate some FMIKit-Simulink2.7 generated Co-simulation FMUs 
on my simulation code based on FMI2.0 libraries. My simulation runs for all other
types of FMUs (both 32 &  64 bits) except Simulink based FMUs. 

The simulink generated FMUs fails in **Reset() function** only.

Regards,
Manas

**Comment by t-sommer** [comment]
Can you reproduce the problem with [v2.8-alpha.3](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.8-alpha.3)? If so, please share an example model.

**Comment by t-sommer** [comment]
I can reset `sldemo_engine` (exported with 24af663687510e285a9e03b81e9337d03a2e903a) without problems. Please provide steps to reproduce the problem and reopen the issue if the problem persists.
