### ISSUE TITLE
Unable to find BlockName within the ExternalOutput scope

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#199]
With v2.8-rc.1 generating an FMU fails with the following error message:
```
Error: File: FMIKit-Simulink-2.8-rc.1\grtfmi\grtfmixml.tlc Line: 245 Column: 56
Unable to find BlockName within the ExternalOutput scope

```
Looking at the .rtw file, the attribute BlockName only exists for ExternalInputs, not for ExternalOutputs.

**Comment by fajansen** [comment]
ML2016a

**Comment by t-sommer** [comment]
@fajansen, can you share an example model to reproduce the problem?

**Comment by fajansen** [comment]
@t-sommer for me it happens with every model. But I think I found a fix:
`        %assign variableName = FEVAL("get_param", block.Name, "Name")`
