### ISSUE TITLE
Make "Direct Input" the default for ME FMU import

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#2]
Unexperienced users get wrong results especially in feedback loops, as delays are included if "direct inputs" is unchecked.
Additionally it would be good to document the behaviour of "Direct inputs" both for ME and CS FMUs

**Comment by chrbertsch** [comment]
It is important to include this change in the 2.6 release.
For the update of models from 2.4. to 2.6, the setting should stay as it is, for new imported ME FMUS one should have the "Direct Input" settings. And a documentation what checking and unchecking means.

**Comment by t-sommer** [comment]
Wouldn't it be better to keep the default (unchecked) for co-simulation and always use "direct input" for model exchange? The checkbox could be grayed out when model exchange is selected to indicate that it has no effect.

**Comment by chrbertsch** [comment]
I agree that one should always check this option for ME. (However, when updating model from 2.4 with this option unchecked, this would change the behaviour)
What is exactly the effect of checking or unchecking this for CS?

**Comment by t-sommer** [comment]
For CS, if "Direct Input" is checked, the current input signals of the S-function are set to the input variables of the FMU ("direct feed-through), i.e. the FMU gets the inputs at `t+1` to calculate the outputs at `t+1`.

If "Direct Input" is not checked, the FMU get the inputs at `t` to calculate the outputs at `t+1`. If the FMU supports input derivatives, the inputs at `t+1` are used to calculate the derivatives.

**Comment by chrbertsch** [comment]
Direct input "unchecked" as Default behaviour for CS FMUs is fine for me. 
Is it possible to make setting the derivative optional?

**Comment by t-sommer** [comment]
> Is it possible to make setting the derivative optional?

Yes, please open a separate issue.
