### ISSUE TITLE
Support for get_param, set_param MATLAB Commands for FMIkit Block

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#20]
Would it be possible to support get_param and set_param commands for an FMI-Kit Block in a Simulink model?

Use case: Re-use toolboxes in Matlab that use these commands e.g. for parameter sweeps for "normal" Simulink blocks.

(Current work-around: use a MATLAB workspace variable as a parameter for the FMU in the FMI-Kit mask and change this workspace variable)

**Comment by t-sommer** [comment]
You can use the [MATLAB commands](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_import.md#matlab-commands) to change the settings of the FMU block. If you change the `UserData` struct e.g. with `set_param(gcb, 'UserData', ud)` you have to re-generate the S-function parameters by applying the FMU dialog. Using workspace variables as parameters is probably more efficient.
