### ISSUE TITLE
Internal time of CS FMU differs depending on export target (GRT or S-Function)

### ISSUE THREAD

**Issue by PhilippZofer** [CATIA-Systems/FMIKit-Simulink#200]
Depending on the export target (GRT or S-Function) the output variable of an internal clock in the FMU differs. The GRT exported FMU has a delay of one step-size and is still at time 0 after the first DoStep() call (see Screenshot)

**Steps to reproduce:**

1. Create Simulink model consisting of an internal clock and a corresponding output (Solver: fixed-step, ode1, step size = 0.01)
1. Export this model as CoSimulation FMU with 
  **a.  grtfmi.tlc** (via MinGW and CMake) -> internal_clock-GRT.fmu
  **b.  rtwsfcnfmi.tlc** (via VS 2017 Professional) -> internal_clock-SFunction.fmu
1.  Simulate FMUs in FMPy and log FMI calls, set Output value = 0.01
1.  Check output value after first DoStep() call
  **a.**  value is 0
  **b.**  value is 0.01
![CompareValuesOfFirstDoStep](https://user-images.githubusercontent.com/51989887/88286652-5e547780-ccf1-11ea-807d-d24016da58c3.png)

Find both FMUs and the simulink model in this ZIP:  [GRT-vs-SFunction-time-difference.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4965920/GRT-vs-SFunction-time-difference.zip)

**Setup:** 

- Windows 10
- MATLAB 2018b
- FMI Kit 2.7
- CMake 3.14.5

Using time triggered events inside the FMU - for example with a combi time table - this can lead to different results. 
Is this behavior know? Why do they behave different?

**Comment by t-sommer** [comment]
Can you still reproduce the issue with [v2.8](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.8)?

**Comment by PhilippZofer** [comment]
> 
> 
> Can you still reproduce the issue with [v2.8](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.8)?


Yes, same behaviour as before.

**Comment by t-sommer** [comment]
I can reproduce the above behavior with this simple model:

![myclock](https://user-images.githubusercontent.com/2453858/91189691-098e8d00-e6f3-11ea-97a2-1a8b02b95ca2.PNG)

However, the output of the FMU is exactly what I get from the generated code:

![grt_debug](https://user-images.githubusercontent.com/2453858/91189837-36db3b00-e6f3-11ea-8336-b2e41a13fd9a.PNG)

**Comment by t-sommer** [comment]
@PhilippZofer and @fajansen, can you give 39265045f54b1f8c377911b97e17601027f60660 a try?

**Comment by fajansen** [comment]
This solves the issue with the delay.
It does cause problems with our environment though, as one of our simulation tools does not initialize the FMU inputs correctly in Initialization mode. It only sets the correct inputs after ExitInitializationMode, but before first DoStep. Would it be possible to have a choice, if the "doFixedStep" is called in ExitInitializationMode when generating the FMU?

**Comment by t-sommer** [comment]
You can achieve the old behavior by commenting out the call to `doFixedStep()` in `fmi2ExitInitializationMode()` in `grtfmi/fmi2Functions.c`.

**Comment by PhilippZofer** [comment]
> 
> 
> @PhilippZofer and @fajansen, can you give [3926504](https://github.com/CATIA-Systems/FMIKit-Simulink/commit/39265045f54b1f8c377911b97e17601027f60660) a try?

Yes, this solves the issue. Thank you @t-sommer !
