### ISSUE TITLE
fmikit.jar file issue

### ISSUE THREAD

**Issue by rrahman2020** [CATIA-Systems/FMIKit-Simulink#207]
Hi:

I am having following issues:

Warning: Error evaluating 'LoadFcn' callback of S-Function block (mask) 'FMIKit_blocks_R2012b/FMU'. 
> In load_system (line 21)
  In FMIKit.initialize (line 76) 
Warning: Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION". 
> In load_system (line 21)
  In FMIKit.initialize (line 76) 
Warning: Error evaluating 'ModelCloseFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'DeleteFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'DestroyFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'LoadFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In load_system (line 21)
  In FMIKit.initialize (line 83) 
Warning: Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION". 
> In load_system (line 21)
  In FMIKit.initialize (line 83) 
Warning: Error evaluating 'ModelCloseFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: Error evaluating 'DeleteFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: Error evaluating 'DestroyFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Initializing FMI Kit 2.8.0
Warning: Error evaluating 'LoadFcn' callback of S-Function block (mask) 'FMIKit_blocks_R2012b/FMU'. 
> In load_system (line 21)
  In FMIKit.initialize (line 76) 
Warning: Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION". 
> In load_system (line 21)
  In FMIKit.initialize (line 76) 
Warning: Error evaluating 'ModelCloseFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'DeleteFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'DestroyFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 78) 
Warning: Error evaluating 'LoadFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In load_system (line 21)
  In FMIKit.initialize (line 83) 
Warning: Undefined variable "fmikit" or class "fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION". 
> In load_system (line 21)
  In FMIKit.initialize (line 83) 
Warning: Error evaluating 'ModelCloseFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: Error evaluating 'DeleteFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: Error evaluating 'DestroyFcn' callback of S-Function block (mask) 'FMIKit_blocks/FMU'. 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)
  In FMIKit.initialize (line 90) 
Warning: No class fmikit.ui.FMUBlockDialog can be located on the Java class path 
> In close_system>i_builtin (line 74)
  In close_system>i_close_system (line 48)
  In close_system (line 37)

Can't load an FMI in Simulink. 

I was trying to build fmikit.jar based on the documentation but couldn't succeed. Not experienced with Java build. Can you please help on how to resolve this?

**Comment by t-sommer** [comment]
Download a [release build](https://github.com/CATIA-Systems/FMIKit-Simulink/releases) (FMIKit-Simulink-*.zip). It contains all necessary binaries.
