### ISSUE TITLE
Make array index base 0/1 selectable

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#208]
To make coupling with other FMUs that use 0 as a base for array indices easier, provide a switch to select base 0 or 1.

**Comment by t-sommer** [comment]
I'll leave this issue open until https://github.com/modelica/fmi-standard/issues/1128 is resolved.

**Comment by t-sommer** [comment]
@fajansen, since there seems to be consensus in the FMI group that 0-based indexing was always allowed, would it be ok to switch to 0-based for the FMU export?

**Comment by fajansen** [comment]
Yes, that would be perfect for me, but it might break other's people workflow.

**Comment by t-sommer** [comment]
@fajansen, can you give adfc6e6fc8847131a7044623e69498c60254d096 a try?

**Comment by fchucholowski** [comment]
We set the attribute `variableNamingConvention="structured"` to achieve structured or array inports and outports when using an FMU in Simulink.
With this change, this is no longer possible. Arrays will no longer be considered as arrays now by Simulink.
