### ISSUE TITLE
Better DirectFedthrough setting for ME Import

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#21]
In Simulink, direct feethrough is a property of inputs of an S-Function, while in FMI ME one can provide a matrix providing the information which input has direct feedthrough to which output.

Thus it is not possible to make use of all present direct feedthrough information from the FMI in Simulink.

Currently FMI-Kit sets all inputs of the S-Function which wraps the FMU to HasDirectFeedthough=true, and sets the inputs of the FMU in the mdlOutputs method of the S-function.

However, this leads possibly to unnecessary detected "Algebraic loops" in Simulink, which can lead to slow simulations and prossible problems in combination with discontinueties, as for algebraic loops Simulink changes the solver behaviour.

Proposal: 
find out from the XML, which input of the FMU is used for any output and set HasDirectFeedthrough only for the inputs where it is necessary.

Then the inputs should be set then for the variables with directFeedthrough=true in mdlOutputs, and for the variables with directFeedthrough=false in mdlDerivatives.

Thus fewer "false" algebraic loops would be created.

**Comment by t-sommer** [comment]
The above proposal is implemented in 2.7 Alpha 3 (except that inputs with direct feedthrough are also set in `mdlDerivatives()` and `mdlZeroCrossings()`).
