### ISSUE TITLE
Export ModelExchange FMU with FMI Kit 2.7 and grtfmi.tlc System Target File 

### ISSUE THREAD

**Issue by erlinghs** [CATIA-Systems/FMIKit-Simulink#210]
Hi all,

we are switching from simulix to FMI Kit in our simulation team because we now also have to generate ModelExchange FMUs.
Therefore we would like to use the grtfmi.tlc System Target File to export FMUs from Simulink with the FMI Kit 2.7.

Exporting Co-Simulation FMUs with the FMI Kit 2.7 and grtfmi.tlc works fine.
We struggle to generate a ModelExchange FMU with these settings.
We only did set the Solver settings to Variable-Step to export a ModelExchange FMU with FMI Kit 2.7.
But the exported FMU was identified as Co-Simulation by FMU-Checker and CarMaker.

Are there any more settings we missed in the Configuration to generate a ModelExchange FMU with the grtfmi.tlc target file with FMI Kit 2.7? 

I have just found a documentation on Dassault Systems for FMI Kit 2.4 which shows the usage of the rtwsfcnfmi.tlc system target file.

Many thanks for your Help.

Best Regards 
Stefan

**Comment by t-sommer** [comment]
Please follow the [documentation](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md#s-function-based-fmu) and reopen the issue if the problem persists with the [latest version](https://github.com/CATIA-Systems/FMIKit-Simulink/releases) and provide steps to reproduce.
