### ISSUE TITLE
FMI initialization failure

### ISSUE THREAD

**Issue by rrahman2020** [CATIA-Systems/FMIKit-Simulink#215]
Hello:

I am trying to import an FMU in Simulink using FMIKit2.9 (Also FMIKit 2.8). It gives me error:

**Failed to exit initialization mode
Failed to exit initialization mode. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).
Error in 'Test/FMU' while executing C MEX S-function 'sfun_fmurun', (mdlStart), at time 0.0.
Caused by:
Unexpected Standard exception from MEX file.
What() is:Failed to exit initialization mode. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).**

I'll appreciate any suggestion or comment to resolve this.

Thank you!

Best,
Rez

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by rrahman2020** [comment]
Sorry, it will be difficult due to IP reason. Is there  any other way to resolve this?

**Comment by t-sommer** [comment]
You can contact me directly on torsten.sommer@3ds.com.
