### ISSUE TITLE
Parameters in nested FMUs, not present in XML

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#218]
When generating a nested fmu, parameters of the inner fmu which depend on workspace matlab variables are not shown in the new generated fmu's xml.
I will send over the example fmus per email

**Comment by t-sommer** [comment]
The parameters of the parent FMU are automatically generated from the parameters of the `sfun_fmurun` blocks by the Simulink Coder. As a workaround you can try to reverse engineer the name of the parameters and change the variable names in the XML.
