### ISSUE TITLE
Mutiple enums for inports, only first enum referenced is in typedefinitions

### ISSUE THREAD

**Issue by d4geiger** [CATIA-Systems/FMIKit-Simulink#220]
Hi,

I want to use 2 different enums for root-inports. I created an example with 2 enums: LEDColor, LEDSize as class scripts.

When using:
- LEDColor for Inport 1 
- LEDSize for Inport 2

Only LEDColor is in the TypeDefinitions and Inport 2 also has LEDColor as its declaredType.
``` <TypeDefinitions>
    <SimpleType name="LEDColor">
      <Enumeration>
        <Item name="GREEN" value="1"/>
        <Item name="RED" value="2"/>
      </Enumeration>
    </SimpleType>
  </TypeDefinitions>
```

```    <!-- Inputs -->
    <ScalarVariable name="In1" valueReference="1" causality="input">
      <Enumeration declaredType="LEDColor" start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2" valueReference="2" causality="input">
      <Enumeration declaredType="LEDColor" start="0"/>
    </ScalarVariable>
```

Always the first enum is created and is also used for the second inport, even when switching the enums. 
Am i doing something wrong here or is it a bug?

I attached the example model, the enum class scripts and the build folder:

[EnumTest.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/5291243/EnumTest.zip)

Im using Matlab 2016b and tested with FMIKit 2.9

Thanks in advance.

**Comment by t-sommer** [comment]
Thanks for reporting this, @d4geiger!
