### ISSUE TITLE
Keep dots (".") in input and output names

### ISSUE THREAD

**Issue by rokil** [CATIA-Systems/FMIKit-Simulink#222]
When an inport or an outport of the model contains a dot in its name, e.g.
Environment.Air.Temperature
then an FMU exported with the grtfmi target has an input or output with the name
EnvironmentAirTemperature

There is no reason why this dot is removed.

Even if naming conventions of FMI are considered, the dot should remain:
- in "flat" naming, it is a valid symbol.
- in "structured" naming, it has a s special meaning but is still a valid symbol.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem with [v2.9](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.9)?

**Comment by rokil** [comment]
I'm very sorry, I did not notice this was already fixed! Not reproducible with v2.9.
