### ISSUE TITLE
Offer choice of variableNamingConvention as code generation option

### ISSUE THREAD

**Issue by rokil** [CATIA-Systems/FMIKit-Simulink#223]
Would it be possible to add the FMI attribute variableNamingConvention, with its choice between "flat" and "structured", as option in the code generation settings?

Note that this is about a GUI choice, in contrast to the related #198, which is rather about the default value.

**Comment by t-sommer** [comment]
`variableNamingConvention="structured"` in combination with inputs / outputs that don't comply with the structured naming convention would lead to illegal FMUs.

**Comment by rokil** [comment]
Do you see any possibility of handling illegal symbols in input/output names?
From what I can see in the spec., the difference between the explicit allowed symbol list in "structured" and the "any Unicode-char" in "flat" might be huge. Looks like it is all umlauts, sz, accents, arabic letters, hebrew letters and asian symbols.

**Comment by t-sommer** [comment]
If you can ensure that your variable names comply with the structured naming convention, you can add the following line to `grtfmi/grtfmixml.tlc` after line 29:

```
  variableNamingConvention="structured"
```

This will generate the following XML:

```xml
<fmiModelDescription
  fmiVersion="2.0"
  guid="{4e71ae8f-5045-4f40-8dc1-1adb1ebd8211}"
  modelName="f14"
  generationTool="Simulink 8.11 (R2016b) 25-Aug-2016 with FMI Kit 2.9 (grtfmi.tlc, ode1, 0.1 s)"
  generationDateAndTime="2020-09-30T11:16:49"
  author="TSR2"
  variableNamingConvention="structured"
  version="1.13">
```
