### ISSUE TITLE
Clarify glyphicons license

### ISSUE THREAD

**Issue by rokil** [CATIA-Systems/FMIKit-Simulink#224]
The license overview on [https://www.glyphicons.com/license/](https://www.glyphicons.com/license/) is incomplete so that it is not clear which conditions apply to glyphicons' icons used in FMI Kit. 
According to the linked website, the license

> is always tied with one email address, unique order ID and the name of the customer.

and can be used for

> personal or commercial projects

1. How does it apply to FMI Kit since FMI Kit is neither a personal nor a commercial project, but an open-source project?
2. The license website does not clarify any distribution details which are important with respect to open-source projects.
3. Further, which terms apply if the content on [https://www.glyphicons.com/license/](https://www.glyphicons.com/license/) changes? Please add license details for the icons to LICENSE.txt (or elsewhere).

**Comment by t-sommer** [comment]
We have a commercial license for the Glyphicons which allows us to ship the icons as part of FMI Kit. If you want to use them in your own project, you have to comply with the above license.

**Comment by rokil** [comment]
Thank you for the clarification.
