### ISSUE TITLE
Simulink hangs on FMU Error

### ISSUE THREAD

**Issue by jpkauffman** [CATIA-Systems/FMIKit-Simulink#225]
I am running a proprietary FMU created in Dymola 2021, running Simulink 2020b using FMIKit on Windows 10 x64. 

At some time instances, the FMU becomes fragile and can fail to resolve a given time step. I am certainly working to resolve the issues in the FMU, but I also believe that Simulink should be able to fail gracefully. Currently, when my FMU fails at a given time step, Simulink continues to sit and wait for the FMU to complete the step (indefinitely), and must be forced closed in the task manager. Stopping the simulation with the Simulink Stop button does nothing as I believe Simulink is still waiting for the repsonse from the FMU.

Is it possible to define a timeout after which time Simulink will kill the FMU process and exit the simulation in a failed state? In that way, each time before the DoStep() method is called, the timer is reset. The timer is then monitored and if the process has not completed before the timeout elapses, the FMU process is terminated.

Are there other options that you would suggest for handling a case like this?

Thanks for your consideration.

**Comment by t-sommer** [comment]
The `doStep()` is executed in Simulink's simulation thread, so `sfun_fmurun` has to wait until it returns. The only way to do this (I can think of) is to add a timer inside the FMU.

@KarlWernersson, do you think this  would be possible?

**Comment by KarlWernersson** [comment]
I dont beleave it is a good idea to implement a timeout timer inside an fmu.
How we do it in dymola is to let the simulation run in a different process from the dymola program, then a user can easily terminate it,
How this is done in simulink i don't know.
