### ISSUE TITLE
FMU state

### ISSUE THREAD

**Issue by frodrigue1246** [CATIA-Systems/FMIKit-Simulink#226]
Hi, Thank for your work!

On FMI documentation show how getting and setting the complete FMU state and in this document says:
_"These functions are only supported by the FMU, if the optional capability flag <fmiModelDescription> <ModelExchange / CoSimulation canGetAndSetFMUstate in = "true"> in the XML file is explicitly set to true"_

But this option does not exist in the FMIKit-Simulink (or i dont know how enable it). Im using the system target file "grtfmi.tlc".
I think adding this capacity would be very useful.

**Comment by t-sommer** [comment]
The state of FMUs exported with `grtfmi.tlc` cannot be retrieved / serialized.
