### ISSUE TITLE
Inconsistency getting derivatives

### ISSUE THREAD

**Issue by pyro-dev** [CATIA-Systems/FMIKit-Simulink#228]
Using Matlab R2019b, with FMIKit 2.9 and rtwsfcnfmi.tlc as a target.
I could basically reproduce the issue with a simple integrator, which I tried to export as a ME FMU ([integrator.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/5374761/integrator.zip))

When reimporting that FMU within Simulink, it runs just fine.
Execution is ok with FMPy as well.
However, when trying to use it in Dymola, the FMU just returns a zero output, no matter what signal I feed it.

After investigation, it seems that calling getDerivative() doesn't give the same value like reading the der(ContinuousStates.position) variable.
Dymola may have a different way to retrieve derivatives than FMPy, which would explain why the problem occurs there only.

**Comment by t-sommer** [comment]
@pyro-dev, can you give ed2d701b78b27243cc4e5fd83f8fcf12862cb818 a try?

**Comment by pyro-dev** [comment]
It seems to do the trick. I could import in Dymola and run it properly at least.
