### ISSUE TITLE
Rename Actual Unzip Directory when Renaming in GUI

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#230]
When the unzip directory is renamed in the GUI, the source folder should be renamed as well to avoid accumulating ghost folders.

Steps to reproduce:
- Create new FMIKit block, load an FMU
- Check from source code option and click apply (S Function compiles)
- Change unzip directory name in GUI and click apply (compilation fails)

Matlab command window output:

Compiling S-function sfun_TS050_Internal_Chassis_Road
Failed to compile S-function
C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road_Renamed\sources\all_TS050_Internal_Chassis_Road.c not found; check that you are in the correct current folder, and check the spelling of 'C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road_Renamed\sources\all_TS050_Internal_Chassis_Road.c'.
Compiling S-function sfun_TS050_Internal_Chassis_Road
Building with 'Microsoft Visual C++ 2017 (C)'.
MEX completed successfully.
Compiling S-function sfun_TS050_Internal_Chassis_Road
Failed to compile S-function
C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road_Renamed\sources\all_TS050_Internal_Chassis_Road.c not found; check that you are in the correct current folder, and check the spelling of 'C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road_Renamed\sources\all_TS050_Internal_Chassis_Road.c'.

The source code paths are also not renamed in the build settings, instead new paths are created, accumulating ghost paths:
"C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road\sources\all_TS050_Internal_Chassis_Road.c" "C:\WORK\Git\DriveabilityModelClean\Simulink\TS050_Internal_Chassis_Road_Renamed\sources\all_TS050_Internal_Chassis_Road.c"

**Comment by t-sommer** [comment]
What is the use case for renaming the unzip directory _after_ the FMU has been imported?

**Comment by Marvin-TMG** [comment]
The usecase is to load a new FMU within the existing block and assign it a different path. The old previous folder and file references will not be disposed in that case.

**Comment by t-sommer** [comment]
The re-load is designed to import a new version of the same FMU (with minimal changes), so the start values etc. can be reused.
To import a new FMU you should delete the block and create a new one.
