### ISSUE TITLE
FMI kit data paths issue

### ISSUE THREAD

**Issue by IgorPolushkin** [CATIA-Systems/FMIKit-Simulink#231]
we are using FMI kit 2.8 for generating FMUs out of simulink.
We have issues with the datapaths that are some kind of hard-coded in the FMU. Is there a possibility to define the working directory path?

**Comment by t-sommer** [comment]
The MATLAB working directory can be changed with the [cd command](https://www.mathworks.com/help/matlab/ref/cd.html).

**Comment by berndwassertheurer** [comment]
@t-sommer, thanks for your reply, but the problem is not to be solved that easy I am afraid.
I can build the FMU without an error. I see the problem when I try to run the FMU afterwards (within simulink and other tools). I get the error message that one of the neccessary *.dlls couldn't be found. The relative paths to the subdirectories and the files have to stay as they are but as I see it during building the FMU the paths are "rearranged".
Is there a possibility to get the relative path structure into the FMU and how can I chose the "working directory" where the FMU is running internaly (not just the MATLAB working directory where I start the simulation)?

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem? Which target are you using? Where do the dependent DLLs come from?

**Comment by berndwassertheurer** [comment]
I have a simulink model including sfunctions and some wrappers to combine everything. The sfunctions are built from simulink models, some sfunction are hosting c-code. All is linked by a static library. Everything is delivered from our supplier. There is communication between the functions via a shared memory solution, that means a client/server communication is active during simulation. 
For generating the FMU I start up everything. So the client/server communication ist set up and all paths are set. I set the configuration parameters in simulink (FMIKit-Simulink-2.8\rtwsfcnfmi\rtwsfcnfmi.tlc and C++) and start the build process which runs successfully.
Whet I try to run the FMU afterwards I can see that the "working directory" is set to "[....]/slprj/_fmu/c76b05d3929972a02ffbd548d10a53e8/Subsystem_sf".
The error message is: VCU-Adapter: Error loading ECU-DLL;  Error reason: 0

That' kind of hard coded within the FMU. It's absolutely neccessary that the folders and folder structure stays the same as the code depends on relative paths within the software.

**Comment by t-sommer** [comment]
Would a solution like the `FMU_RESOURCES_DIR` in `grtfmi.tlc` (see #89) work for you?

**Comment by berndwassertheurer** [comment]
I tried to repeat the FMU creation  with the 2.9 version now. First had some issues with the new cmake build tool things but git that fixed.
I ran in some errors and decided to have a look on a simple example. So I created a simulink model just doing a summation and a multiplication. I created a sFunction out of it. Next step was to insert this sFuncion into a new Simulink model and with this tried to build a FMU out of it.
This is also my use case with the "real model", so this should work before getting to the huge model.
I get the following error message:
`[C:\temp_WB\FMU\Dassault\20201117_FMU_2p9\Test_Block\Test_sFun_sfcn_rtw_fmi\Test_sFun.vcxproj]
  Test_sFun_sf_data.c
c:\temp_wb\fmu\dassault\20201117_fmu_2p9\test_block\test_sfun_sfcn_rtw_fmi\Test_sFun_sf_types.h(23): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Subsystem_sfcn_rtw/Subsystem_sf.h": No such file or directory [C:\temp_WB\FMU\Dassault\20201117_FMU_2p9\Test_Block\Test_sFun_sfcn_rtw_fmi\Test_sFun.vcxproj]
  model_interface.c
c:\temp_wb\fmu\dassault\20201117_fmu_2p9\test_block\test_sfun_sfcn_rtw_fmi\Test_sFun_sf_types.h(23): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Subsystem_sfcn_rtw/Subsystem_sf.h": No such file or directory [C:\temp_WB\FMU\Dassault\20201117_FMU_2p9\Test_Block\Test_sFun_sfcn_rtw_fmi\Test_sFun.vcxproj]
  rtGetInf.c
  rtGetNaN.c
  sfcn_fmi.c
c:\temp_wb\fmu\dassault\20201117_fmu_2p9\test_block\test_sfun_sfcn_rtw_fmi\Test_sFun_sf_types.h(23): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Subsystem_sfcn_rtw/Subsystem_sf.h": No such file or directory [C:\temp_WB\FMU\Dassault\20201117_FMU_2p9\Test_Block\Test_sFun_sfcn_rtw_fmi\Test_sFun.vcxproj]
  Code wird generiert...`
I can support the example model if needed - where can I share it?
Do you have any suggestions what might cause the problems? It should be possible to build a FMU out of a Simulink model including sFunctions?

**Comment by t-sommer** [comment]
You can create a ZIP file and drop it here (onto the message box) to attach it.

**Comment by berndwassertheurer** [comment]
[Test_Block.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/5572642/Test_Block.zip)
Test_Sub.slx is used to create the sFunction.
Test_sFun.slx is used to build the FMU out of the precompiled sFunction.

**Comment by t-sommer** [comment]
Please re-open if this is still relevant.
