### ISSUE TITLE
FMU could not be unzipped, only DEFLATED entries can have EXT description

### ISSUE THREAD

**Issue by Spiegel-Leser** [CATIA-Systems/FMIKit-Simulink#233]
A FMU cannot be imported into Simulink, giving the error message in the title. Interesting: It still works with FMIKit 2.7

edit - I mistakenly wrote 2.8, I meant 2.7

**Comment by t-sommer** [comment]
Can you share an FMU to reprocude the problem?

**Comment by Spiegel-Leser** [comment]
I sent it to you via email.

**Comment by t-sommer** [comment]
Your FMU contains a ZIP file under `resources/resources/obj/` that is not compressed with method `deflate` as required by the FMI Specification 2.0.1, p. 68, but with method `store` [which Java's ZipInputStream can't handle](https://bugs.openjdk.java.net/browse/JDK-8143613).

To import your FMU with FMI Kit you can either remove this file from the FMU (as it doesn't seem to be required) or re-pack it, e.g. with 7zip.
