### ISSUE TITLE
"use source code" option causes error s-function does not exists

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#234]
Activating the option "use source code" when importing an FMU causes the error: 
Error in S-function '.. ': S-Function 'sfun_myModelname' does not exist. 
I assume, the s-function is not being generated when applying, or pressing ok.
Is there another way to trigger the generation of the sfunction?
In this case I have a pure source code fmu.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by jbernalr** [comment]
I have provided an example as email. 
Thanks!

**Comment by jbernalr** [comment]
I have had no time to test this in detail. I will close it and reopen it if I encounter the problem again
