### ISSUE TITLE
Question about Sample time

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMIKit-Simulink#237]
Just a simple question: When using a CoSimulation FMU, is "Sample time" on tab "Advanced" of the FMU's parameter menue the same communication step size between FMU and Simulink, i.e. the same as "fmi_CommunicationStepSize" on tab "FMI" of the FMU's parameter menue when importing the FMU into Dymola? This would mean the FMU behaves like real hardware communicating via sampled I/O with sampling rate = 1/Sample time, right?
Thanks for clarification,
Toni

**Comment by t-sommer** [comment]
For Co-Simulation the "Sample time" is the value passed to [ssSetSampleTime()](https://www.mathworks.com/help/simulink/sfg/sssetsampletime.html) in [mdlInitializeSampleTimes()](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/sfun_fmurun.cpp#L813).
