### ISSUE TITLE
Wrong start value for boolean tunable parameters

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#240]
With FMIKit 2.9 grt target, when a model contains a parameter of type "Boolean", the resulting modelDescription looks like this:

`    <ScalarVariable name="Parameters.Constant_Value" valueReference="1" causality="parameter" variability="tunable">
      <Boolean start="1"/>
    </ScalarVariable>`

The start value should be "true", not "1".

**Comment by t-sommer** [comment]
`0` and `1` are legal start values for boolean attributes (see https://www.w3.org/TR/xmlschema11-2/#boolean).
