### ISSUE TITLE
fmu with possibly ilegal xml entries: parameters with no start values

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#241]
generating an fmu with grtfmi.tlc, produces this kind of entries:
    
```
<ScalarVariable name="Parameters.mstruct_something" valueReference="123" causality="parameter" variability="tunable">
      <Real/>
```
I am not sure these are legal. In anycase, FMPy will produce an error saying no startvalue is provided for this element.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem with the latest version?

**Comment by jbernalr** [comment]
this is the same as #248
