### ISSUE TITLE
GRT FMU with nested FMUs fails to simulate on linux64 and darwin64

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#243]
Example source code fmus with minimal modells as provided per email. 
Under windows no issues found.

**Comment by t-sommer** [comment]
The source code of the `sfun_fmurun` S-function is C++ which is not allowed in FMI 2.0. Visual Studio handles the `.cpp` files gracefully, that's why the compilation works on Windows.

**Comment by jbernalr** [comment]
@t-sommer one question and one observation: 

- this means that nested fmus from the FMIKit are in principle not legal fmus because they contain c++ code? 

The problem occurrs not at compile time but at runtime (under windows there is no problem) so the way the binaries are connected is in my eyes what is missing. A dirty fix for that would be nice 👍

**Comment by t-sommer** [comment]
> this means that nested fmus from the FMIKit are in principle not legal fmus because they contain c++ code?

Yes, FMI 2.0 allows only C sources.
