### ISSUE TITLE
Swingx LGPL V2.1 - corresponding license text and source code missing

### ISSUE THREAD

**Issue by SOesterreicher** [CATIA-Systems/FMIKit-Simulink#244]
The included SwingX library (swingx-1.6.jar) is copyright Copyright (c) 2005-2006
Sun Microsystems, Inc., 4150 Network Circle, Santa Clara, California 95054, U.S.A
and released under the GNU Lesser General Public License version 2.1
(https://opensource.org/licenses/LGPL-2.1).

Can you please attach the LGPL V2.1 license text and the corresponding SwingX Source Code, or provide information regarding the license obligation fulfilment.

Many greetings
Siegfried Oesterreicher

**Comment by t-sommer** [comment]
The ~[original SwingX project](https://github.com/ebourg/swingx)~ is no longer available. However, the source code has been mirrored on GitHub (e.g. https://github.com/arotenberg/swingx). The license text is available from [the above URL](https://opensource.org/licenses/LGPL-2.1).
