### ISSUE TITLE
Missing initial values in xml for simple blocks like constants and gains (values in workspace)

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#247]
Please see mini model sent per email: exmpl_InitParam.zip

**Comment by t-sommer** [comment]
The `DefaultParameterBehaviour` has to be set to `Tunable` to make the parameters appear in the XML. To access the values of a `Simulink.Parameter` you can use the solution proposed in #248:

```
SimulinkParameter.('firstElement')
```
