### ISSUE TITLE
missing initial values in xml for matlab structs

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#248]
This could be related to #247 
I have mailed a minimal example.

**Comment by t-sommer** [comment]
Fields of structs are currently not supported as parameters.  However, you can access the fields by name:

```matlab
>> a.b.c = 2.1

a = 

  struct with fields:

    b: [1×1 struct]

>> a.('b').('c')

ans =

    2.1000
```
