### ISSUE TITLE
multiple inputs with multiple time vectors

### ISSUE THREAD

**Issue by ggursun** [CATIA-Systems/FMIKit-Simulink#251]
I have an FMU with multiple input signals. Each input signal has its own time vector with irregular values. 
For instance, assume a pair is (time, value) and I have two input signals.

input1 = (0.0, v1)   (0.5, v2)     (1.0, v3)
input2 = (0.1, v4)   (0.15, v5)   (0.6, v6)   (1.1, v7)

How can I handle such inputs with the Input Class ? How would my input_signals vector should look like for the example above ?

**Comment by t-sommer** [comment]
Are you sure this an issue with FMI Kit?
