### ISSUE TITLE
Optional Input Port to Reset Model

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#252]
It would be nice to have the option for an additional input port to trigger a reset of the model at runtime. This could be particularly usefull for real time systems where it takes quite a long time to reload the application, so a direct reset of the model without the need to reload the application will save a lot of time.

**Comment by t-sommer** [comment]
Like so?

```C
static void mdlOutputs(SimStruct *S, int_T tid) {
    if (reset) {
        setStartValues(...);
        setInputs(...);
        fmi2Reset(...);
    }
    ...
}
```

**Comment by Marvin-TMG** [comment]
Yes, something like that would be great. If we can trigger this with a rising edge pulse on the simulink block, that should work!

**Comment by fajansen** [comment]
This is also interesting for me. But please make it optional, as the additional port might confuse users.
