### ISSUE TITLE
FMU export of system with embedded FMU does not work

### ISSUE THREAD

**Issue by matthiasliermann** [CATIA-Systems/FMIKit-Simulink#257]
I created a simple model which includes an FMU generated with the FMIKit. 
![FMUinFMUtest](https://user-images.githubusercontent.com/29143974/106591626-ca405400-654e-11eb-92a1-b726c14c457f.png)
I export this model as an FMU again without errors or warnings, but the generated nested FMU does not execute. In Simulink the error message is: 
```
Failed to instantiate FMU. The FMU crashed (exception code: ACCESS_VIOLATION).
Error in 'untitled/FMU' while executing C MEX S-function 'sfun_fmurun', (mdlStart), at time 0.0.
Caused by:
Unexpected Standard exception from MEX file.
What() is:Failed to instantiate FMU. The FMU crashed (exception code: ACCESS_VIOLATION).
.. 
```
With the FMU Simulator the message is:
`Could not lad shared library. The specified module could not be found. (System Error 126)`

Attached is my example code.
- gain.slx: model containing a gain block (Matlab 2019b)
- gain.fmu : cosimulation FMI 2 FMU of a simple model containing a gain block
-  integrator.slx: model containing a integrator block (Matlab 2019b)
 - integrator.fmu : cosimulation FMI 2 FMU of a simple model containing a integrator block
 - FMUinFMUtest.slx: model which contains the two FMUs
[FMUinFMUtest.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/5910623/FMUinFMUtest.zip)

**Comment by matthiasliermann** [comment]
Hello, I looked at that closed issue, which looks similar than mine. 
[issue 186](https://github.com/CATIA-Systems/FMIKit-Simulink/issues/168)
Do you have any idea what I need to do to create nested FMUs? Does it work with everyone else?

**Comment by chrbertsch** [comment]
You seem to use rtwsfcnfmi.tlc target. To my understanding, nested FMUs are only supported with the grtfmi.tlc target

**Comment by matthiasliermann** [comment]
Thanks a lot! You are right. This is very helpful. Could you please help me to understand the underlying issue? I have generated my own FMU from c-code and can't get the nested sfunction to work with this one.

**Comment by t-sommer** [comment]
Nested FMUs are not supported with `rtwsfcnfmi.tlc`.

**Comment by matthiasliermann** [comment]
Thanks for the clarification. I understand that I can't use the sfunction FMI target. My goal is then to export an FMU with the grt fmi target of a system which includes a custom-made FMU. I made this FMU myself from scratch and would like to include in in a system which I want to export as an FMU with the FMIKit using the grt fmi target. Please point me in a direction what I need to do to get this to work. Thanks!

**Comment by t-sommer** [comment]
The only requirement for exporting nested FMUs with grtfmi.tlc is that they have binaries for the platform you're exporting for. There is no source code required.

**Comment by hemant6043** [comment]
I am using an FMU export from Adams model and trying to run it in simulink  and I am still getting this error
Error in 'test/FMU' while executing C MEX S-function 'sfun_fmurun', (mdlStart), at time 0.0.
Caused by:
Unexpected Standard exception from MEX file.
What() is:Failed to instantiate FMU
