### ISSUE TITLE
loadFMU reports "WARNING: Failed to read model description"

### ISSUE THREAD

**Issue by matthiasliermann** [CATIA-Systems/FMIKit-Simulink#261]
the function loadFMU does not find the modelDescription. Please try the attached example.
I use the command 
`FMIKit.loadFMU('loadFMU_test/FMU','TestFMU.fmu')`
and receive
`WARNING: Failed to read model description. C:\git\DPSlib\SSS\GUIDE_SW_Harness\examples\SC05013H\TestFMU\modelDescription.xml (The system cannot find the path specified)`
This happens only, when the fmu hasn't been extracted yet. If it has already been unzipped, the warning does not appear. It seems that the loadFMU function does not give the unzip enough time to complete before reading the modelDescription.xml

Test files:
[loadFMU_Test.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6001090/loadFMU_Test.zip)

**Comment by t-sommer** [comment]
I cannot reproduce the problem. Have you tried it on another machine or with a different MATLAB version?

**Comment by t-sommer** [comment]
Does the problem still exist with [v3.0-alpha.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.1)?

**Comment by matthiasliermann** [comment]
Thanks for the reply. It worked with Matlab 2020b, both with v2.9 and v3.0-alpha.1. 
I couldn't use v3.0-alpha.1 with Matlab 2019b. It throws an error as soon as I try to load an FMU into the import block.

**Comment by t-sommer** [comment]
I cannot reproduce the problem with R2019b.
