### ISSUE TITLE
Support for SFunctionModules attribute in grtfmi target

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#262]
According to the Simulink documentation (see https://de.mathworks.com/help/rtw/ug/build-integrated-code-within-the-simulink-environment.html#bp67s_y-3) the S-Function parameter "SFunctionModules" can be used to specify additional libraries/c-files that are required to build the S-Function as a simpler alternative to the "CustomSource" parameter of the complete model. Using the standard grt target, this works. With the grtfmi target the files specified there are not included and therefore the build fails.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by t-sommer** [comment]
According to [this example](https://de.mathworks.com/help/rtw/ug/build-integrated-code-within-the-simulink-environment.html#bp67s_y-3) the modules have to be provided as a space separated list of names without single quotes.

After removing the quotes I can successfully build the model you shared via e-mail.

**Comment by fajansen** [comment]
My example worked with grt, so they seem to not follow their own documentation. Thanks for the clarification, we will adapt our models accordingly.
