### ISSUE TITLE
Failed to run CMake command:

### ISSUE THREAD

**Issue by harshapolimi** [CATIA-Systems/FMIKit-Simulink#263]
Hi,

I'm trying to export a simple simulink model to FMU model is simple adder a+b=c, but I'm getting following error, I have installed proper compilers and also the cmake generator. I have tried it in Matlab 2017b, 2019b and 2020a. Same error occurs. Please help. 

Thanks in advance.

The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to run CMake generator

The build process will terminate as a result.
Caused by:
Failed to run CMake generator 

[report.txt](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6010983/report.txt)

![image](https://user-images.githubusercontent.com/79323420/108523737-8e3b1c00-72ce-11eb-9749-7c849a0ae507.png)

**Comment by t-sommer** [comment]
MinGW is not supported (see https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md).
