### ISSUE TITLE
How to recompile FMU for different target system?

### ISSUE THREAD

**Issue by StrAma84** [CATIA-Systems/FMIKit-Simulink#265]
I have the following Use-Case and wonder if this is supported by the tool:
I'm creating FMUs from Simulink models on a Windows PC (using FMIKit-Simulink-2.9).
However sometimes the FMUs are required to run on a real-time machine that uses a Linux operating system.

Is there a workaround to re-compile the existing FMU (created in Windows) for Linux without installing Matlab in the Linux environment, thus without rerunning the complete code-generation built-process in Simulink?

**Comment by t-sommer** [comment]
Closing as duplicate of #79
