### ISSUE TITLE
fmuResourceLocation containing URL encoding with `%` sends logFormat with illegal arguments

### ISSUE THREAD

**Issue by andreas-junghanns** [CATIA-Systems/FMIKit-Simulink#268]
If the fmuResourceLocation encodes special characters using `%`, e.g. "file:///P:/tmp/%23MegaSetup_test/SuperSetup/Simulate/SimFiles/9L7YK_cs0_25136/resources", this gets passed to the callback function of the importer causing issues when interpreting this as format string.

To reproduce: Use a path containing `#` for resource location and a tool properly coding as URL.

**Comment by t-sommer** [comment]
You could try to[ check if the number of variadic arguments is > 0](https://stackoverflow.com/questions/4421681/how-to-count-the-number-of-arguments-passed-to-a-function-that-accepts-a-variabl) in your callback before calling `vsnprintf()`.
