### ISSUE TITLE
FMU issue

### ISSUE THREAD

**Issue by hemant6043** [CATIA-Systems/FMIKit-Simulink#272]
I am using an FMU export from Adams model and trying to run it in simulink  and I am still getting this error
Error in 'test/FMU' while executing C MEX S-function 'sfun_fmurun', (mdlStart), at time 0.0.
Caused by:
Unexpected Standard exception from MEX file.
What() is:Failed to instantiate FMU

**Comment by t-sommer** [comment]
Can you simulate the FMU with any other tool?

**Comment by hemant6043** [comment]
No I haven't tried with any other tool.

**Comment by t-sommer** [comment]
Please re-open if you can successfully simulate the FMU with the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker/releases).
