### ISSUE TITLE
Avoid Initialising FMU in Enabled Subsystem when Disabled

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#274]
We like to run various model variants in parallel, which rely on parameter files. The FMUs are in enabled subsystems and sometimes not used, but even if the FMU is disabled, FMIKit will still run the initialisation routine, which could cause a crash is the appropriate parameter file is not available.

Is there a possible solution for this?

**Comment by t-sommer** [comment]
Solved with a2e7e133b02684fc4fa2c0a0de8e2f69d74da7ba.
