### ISSUE TITLE
Make setting of input derivative optional

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#28]
As described in https://github.com/CATIA-Systems/FMIKit-Simulink/blob/develop/docs/fmu_import.md , in the case of "Direct inputs" not checked, for CS FMU input derivatives are approximated and set, if the imported FMU supports this.
It would be good to make this behavour optional by a new checkbox:  SetApproximatedInputDerivatives (default unchecked)

**Comment by t-sommer** [comment]
The "direct input" option has been removed in [v2.7](/CATIA-Systems/FMIKit-Simulink/releases/tag/v2.7).
