### ISSUE TITLE
FMU Ports Disappear when making Change to Simulink model or reopening

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMIKit-Simulink#281]
In the latest development branch, the model ports disappear when making a change to the surrounding Simulink model or when reopening the model. The only way to fix this is to double click the block and click OK again, but the connections also get messed up and the block shifts slightly. This did not happen with the previous release.

**Comment by t-sommer** [comment]
I cannot reproduce the problem with 5bf06dab2e1e98bbcd79364c74ac1dabe00bdfbe on R2021a. Can you please provide steps?
