### ISSUE TITLE
time delay and duplicate output value in newest v3.0-alpha.1 build

### ISSUE THREAD

**Issue by Tulgs** [CATIA-Systems/FMIKit-Simulink#282]
Hello, I saw that the new Pre-release 2ed1eef contains some additional functionality, so I wanted to test it, but recognized some weird time delay. In d59271d every output value was delayed one timestep. To see if the issue still remains I tried a simple Simulink model which adds **"In1"** and **"In2"** and outputs the result. I am using 10 samples, so timestepwidth = 1, graphs from FMPy.

The input values I use:
![grafik](https://user-images.githubusercontent.com/80069014/116695385-d78ba400-a9c0-11eb-9764-c452de860f12.png)

For a FMU created in d59271d the value at **t=0** is always **0**, then the outputs follow shifted by one timestep, so the expected **8** (=3+5) is output at **t=1** instead of **t=0**:

![FMIKit2 9Graph](https://user-images.githubusercontent.com/80069014/116695355-c93d8800-a9c0-11eb-97b1-cdc54c735a26.png)

Now a FMU created in 2ed1eef with the same model and the same input values:

![FMIKit3 0Graph](https://user-images.githubusercontent.com/80069014/116695919-83cd8a80-a9c1-11eb-9bf2-978cb4312276.png)

We can see that now the value at **t=0** is **8**, not **0** anymore, but then at **t=1** it is **8** again and all other output values again follow delayed by one timestep. So it seems that the first and second output values now both result from the first actual output and the following ones are as in d59271d. I don't know if you are aware of this issue, just wanted to point it out before release. If I might support you somehow with this let me know.
Greetings and thanks for your work

**Comment by t-sommer** [comment]
This could be due to numerical tolerances. Have you tried a smaller communication interval?

**Comment by t-sommer** [comment]
The second figure shows the expected output i.e. the sum of the inputs, delayed by the communication step size.

**Comment by Tulgs** [comment]
Okay, thank you for the clarification. The starting values in v3.0 seem to be much better than initializing 0 for all at least.
Greetings
