### ISSUE TITLE
problem with case sensitive enum

### ISSUE THREAD

**Issue by fchampavier** [CATIA-Systems/FMIKit-Simulink#284]
The Simulink model SMK_model.xls is the model to encapsulate in FMU. This model is fairly simple, it is only mean to illustrate an issue raised with a particular structure of data dictionary.
SMK_model.xls is linked to the data dictionary DD.sldd which contains:
•	A variable period (which defines compilation step-size).
•	Two enumerated: ENUM_Source and ENUM_source which are defined in the data dictionary ENUM_DD.sldd and added as a reference in DD.sldd. The only difference between the two enumerated names is the letter s which is either lower or upper case.  
•	The bus element Bus_output, the output bus of the model composed of one boolean.
•	The bus element Bus_input, the input bus of the model composed one Boolean and two Enumerated of type ENUM_Source and the other of type ENUM_source. The two ENUM are not consumed in the model.
During the compilation of the model FMU, multiple errors are obtained. The first error is: l:\enum_issue_file_2\smk_model_grt_fmi_rtw\SMK_model_types.h(35): error C2061: erreur de syntaxe : identificateur 'ENUM_Source'. It was suspected that this error comes from the name of the ENUM. A way to compile the model ihas been found by changing the name of this enumerated (for instance ENUM_Source by ENUM_Source_1) and update the reference in the corresponding ENUM of the Bus_input. Thereafter, the model can be encapsulated in the FMU. 
We would like to know if there is any possibility to encapsulate the model in FMU without changing the name of one of the enumerated ?
[FMIKit_ENUM_Issue.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6510613/FMIKit_ENUM_Issue.zip)

Versions and configuration used : 
•	Matlab R2018b
•	FMIKit-Simulink 2.9
•	FMI version: 2
•	Cmake generator: visual studio 14 2015

**Comment by t-sommer** [comment]
@fchampavier, can you please check if the problem still exists with [v3.0-alpha.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.1)?

**Comment by fchampavier** [comment]
@t-sommer . the problem exists with  v3.0-alpha.1

**Comment by t-sommer** [comment]
Simulink's GRT target (which grtfmi.tlc is based on) does not support enums with the same name but different capitalization. You can verify this by exporting the model with grt.tlc.

A possible workaround is to rename one of the enums.
