### ISSUE TITLE
FMI CMaker issue

### ISSUE THREAD

**Issue by Souiyous** [CATIA-Systems/FMIKit-Simulink#287]
Hi,

I am trying to create a FMU using your offered tool 2.9 in Matlab 2019a. As an error I get this:

The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to run CMake generator

The build process will terminate as a result.
Caused by:
Failed to run CMake generator 

No Idea how to add the right path of "MinGW Makefiles" in the CMake command. Is there any solution for this issue?

Best,

**Comment by t-sommer** [comment]
MinGW is not a supported compiler on Windows (see https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md).
