### ISSUE TITLE
FMU not working in linked model

### ISSUE THREAD

**Issue by j-emils** [CATIA-Systems/FMIKit-Simulink#289]
[FMUimport_MWvsFMIKit.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6591143/FMUimport_MWvsFMIKit.zip)
Simulink fails to run fmu when fmu is placed in a linked model. The attached file contains a script for running with an fmu. On row 33-34 one can toggle linked and not linked model. The error output is:

Warning: Unconnected output line found on
'kitBattTestLinked/Subsystem/current' (output port: 1) 
> In plotScriptMemoryUsage_MWvsKit (line 34) 
Error using plotScriptMemoryUsage_MWvsKit (line 34)
Error reported by S-function 'sfun_fmurun' in
'kitBattTestLinked/Subsystem/FMU':
Cannot find the FMU's platform binary binaries\win64.dll for
kitBattTestLinked/Subsystem/FMU.

System:
Windows 10
FMI 2.0 ME
Matlab 2019b & 2017b
FMIKit 2.9

**Comment by t-sommer** [comment]
When you move or share a model that contains an FMU block, you have to make sure that the extracted FMU exists in the path pointed to by `Advanced > Unzip directory`. By default this is the directory with the same name as the FMU next to the Simulink model. The *.fmu file is not required any more once it's been imported.
