### ISSUE TITLE
"Diagnostics for out-of-range inputus" in Simulink Look-up table  not contained in generated FMU

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#290]
With a simple Simulink model with a 1D LUT table where we have given the input which is out of the boundary, 
![grafik](https://user-images.githubusercontent.com/16363372/120979574-06dac100-c776-11eb-9d32-04573e9f50fb.png)
with the error-settings we get the expected the below error. 
![grafik](https://user-images.githubusercontent.com/16363372/120979477-f0346a00-c775-11eb-8523-2a573b323cdc.png)

When we create a co-simulation FMU (with rtwsfcnfmi.ltc target, FMI-Kit 2.9, ML/SL 2019b) and provided the same out of the boundary input to the fmu but this time it interpolates to the last value and generates an output without any error. 

Is there a way to preserve the error behaviour when generating an FMU?

Example:
[testFmuBuild.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6616246/testFmuBuild.zip)

**Comment by t-sommer** [comment]
This is a limitation of the S-function target. If you export the subsystem as an S-function it will also simulate without an error.

**Comment by chrbertsch** [comment]
Thanks! Does the limitation also exist with the grtfmi.tlc target?

**Comment by chrbertsch** [comment]
The same limitation applies for the grtfmi.tlc target.

**Comment by t-sommer** [comment]
The GRT shows the same behavior.
