### ISSUE TITLE
Sample Time Dependence of Model Exchange FMU

### ISSUE THREAD

**Issue by mabumallouh** [CATIA-Systems/FMIKit-Simulink#292]
When exporting a Model Exchange FMU (rtwsfcnfmi.tlc) from a Simulink model containing integrator blocks, whether the integrators are discrete or continuous, the time step the model was set to at generation gets embedded into the model and results in a dependency on that time step in order to get stable and accurate results. 

The time step embedded into the FMU is the fixed step size if set to a fixed step solver, and the maximum allowable step size if using a variable step solver. 

Is this a limitation of Simulink Coder or is there something that can be modified to allow for the model to be time step independent?

I'm using FMIKit 2.9 with MATLAB R2020a.

**Comment by dhenriksson** [comment]
For discrete integrators, the sample time of the integrator block will be used in the code for updating the integrator state. This is the expected behavior.
If the integrator belongs to the continuous sample time part, there should not be any dependence of any fixed time step. In that case the derivative of the integrator state will appear in the code for computing derivatives.

**Comment by mabumallouh** [comment]
@dhenriksson I appreciate you taking the time to respond.

The only portion of my model that depends on time are the integrator blocks, which are all continuous. All of the FMU's I have generated have shown the same behavior in terms of dependence on sample time.

**Comment by dhenriksson** [comment]
If this is the case, this should be a new property of Simulink Coder that I was not aware of. Could you please post the code for the derivative calculation of the integrator state from the generated mdlDerivatives() function? This is what it usually looks like:

_rtXdot->Integrator_CSTATE = *((const real_T **)ssGetInputPortSignalPtrs(S, 0))[0];

**Comment by mabumallouh** [comment]
@dhenriksson Thanks for following up.

I figured out what the issue was, and it had nothing to do with FMIKit. The issue came from the Memory blocks I had in my system.

When the model has a fixed step solver Memory blocks become discrete and, if you generate an FMU with the model set to a fixed step solver, they are also treated as discrete states at FMU generation. If you have the model set to a variable step solver, then Memory blocks become continuous (fixed in minor integration step, but continuous nonetheless). 

It was your first response that made me realize to look for discrete states, so thank you. I've been trying to figure this out for awhile so I really appreciate it.
