### ISSUE TITLE
Parallel computing of simulink models with FMIKit

### ISSUE THREAD

**Issue by jonasklingebiel1** [CATIA-Systems/FMIKit-Simulink#293]
Hi! 

**What we want to do**

We developed a simple calibration framwork in Matlab/Simulink to fit a model to measurement data by tuning predefined calibration parameters. The model is a fmu-file and is implemented in Simulink using FMIKit 2.9. To accelerate the calibration process we want to simulate the fmu multiple times in parallel using "parfor". 

**Description of problem**
 
As simply using "parfor" instead of "for" did not work, we broke down the problem to eliminate as many problem sources as possible. The error-message is always: 
 
![error_message](https://user-images.githubusercontent.com/48320530/122522864-b2a5cb80-d016-11eb-97ad-7f238ac071f6.png)

In the minimal working problem a simulink model with a FMU shall be simulated on a "local worker" using the "batch" function of Matlab. The local worker runs the job on one core of the PC. Note that this is not parallel computing yet but only outsourcing the computing job to a matlab local worker. The parfor loop then simply runs multiple local workers. The concept is shown in the following picture:   

<img src="https://user-images.githubusercontent.com/48320530/122522640-7b371f00-d016-11eb-932d-02313265cdf3.png" width="50%" height="50%">

In our problem we used the "Bouncing Ball" Model, wich is given as an example in the FMIKit. The following code runs the script "Job" on a local worker. "Job" just consists of a function to simulate the "Bouncing Ball" Model. 
 
```
`j = batch('Job','AdditionalPaths',AdditionalPaths);

wait(j);

load(j,'out');`
```

Additional paths are the paths to the model and the unzipped FMU, so the worker can access these. 
Doing the same thing with the Simulink FMU Block (not FMIKit) works. So the FMIKit seems to be the cause of the error.

**Is it possible to run a simulink model with a FMU on a seperate worker? Are there any tipps or hints to enable parallel computing for FMIKit?** 

Files that were used for testing:   
[minimal_working_problem.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/6675373/minimal_working_problem.zip)

Thanks for your help!

**Comment by jonasklingebiel1** [comment]
Can you provide any information regarding this problem? @t-sommer

**Comment by t-sommer** [comment]
The FMU block expects the extracted FMU in the relative or absolute path provided in `Advanced > Unzip directory`. If you use a relative path (default) you have to copy the extracted folder together with the model.

**Comment by t-sommer** [comment]
As an alternative you might want to consider [FMPy](https://github.com/CATIA-Systems/FMPy) to simulate an FMU on multiple cores (see [parameter_variation.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/parameter_variation.py) for an example).

**Comment by jonasklingebiel1** [comment]
Thank you for your help! We tried both absolute and relative paths with the extracted FMU in the same matlab directory as the model. Both variations produced the same error. Do you have any further suggestions? @t-sommer 

We are aware of the FMPy package but for our certrain use case this unfortunately can not be used since we want to apply a special simulink block.

**Comment by t-sommer** [comment]
I can run the `sim` command successfully if I make a copy of `fmikit_demo_BouncingBall.slx`, together with the extracted FMU:

![BouncingBall](https://user-images.githubusercontent.com/2453858/125496300-9588c44b-379b-4707-98d6-63f66560f297.png)
