### ISSUE TITLE
Error generating FMU with FMIKit 3.0-alpha

### ISSUE THREAD

**Issue by carlos5491** [CATIA-Systems/FMIKit-Simulink#297]
Hello,

I want to generate a FMU of a cooling circuit model in Matlab2017b and I get the following error: 

![error](https://user-images.githubusercontent.com/87063002/124721721-a45a1980-df09-11eb-9c28-437e9ba21f3e.png)

The point is that I am using my own thermo hydraulic library. To simulate the cooling circuit a flow solver block is required that is calculating mass flow, etc. ItMax is one parameter inside this solver. If I remove the solver block I am able to generate the FMU, so for me clearly the flow solver block makes the troubles. The problem is that I need it inside my model. Does anyone have an idea how to approach the problem?

**Comment by t-sommer** [comment]
Can you export your model with `grt.tlc`?

**Comment by carlos5491** [comment]
yes, when I export with grt.tlc it is no problem and I successfully generate the executable.

**Comment by t-sommer** [comment]
Can you share a model to reproduce the problem?

**Comment by carlos5491** [comment]
Unluckily I am not able to share the model.

**Comment by t-sommer** [comment]
Please reopen if you can provide steps to reproduce the problem.
