### ISSUE TITLE
Build process failure with GCC 5.3.0 on Win10-x64 due to missing dlfcn.h

### ISSUE THREAD

**Issue by svanimisetti** [CATIA-Systems/FMIKit-Simulink#299]
I am trying to build an FMU from a model that contain custom S-function block using TDM GCC 5.3.0. When I use _**grtfmi.tlc**_, I am able to compile the model without any issues. However, when I try to use _**rtwsfcnfmi.tlc**_, the build process fails with the following error.

```
W:\Scratch\FMIKit-Simulink-2.8\rtwsfcnfmi\sfunction.c:7:19: fatal error: dlfcn.h: No such file or directory
compilation terminated.
```

This issue is not seen when using MSVC for both target TLCs. I found a [port of dlfcn](https://github.com/dlfcn-win32/dlfcn-win32) for Win32 - is this a system requirement on Windows? On windows, is it possible to support rtwsfcnfmi.tlc with GCC?

Also, when I switch from _**rtwsfcnfmi.tlc**_ to _**grtfmi.tlc**_, I see that the "FMI -> FMI type" configuration option is not available. Are there any restrictions when using the latter? Do I always get a FMI2CS when using _**grtfmi.tlc**_?

**Comment by t-sommer** [comment]
On Windows only MSVC is supported (see [docs/fmu_export.md](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md)).
