### ISSUE TITLE
Create source code FMUs

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#3]
It would be great to be able to export source code FMUs from Simulink.

**Comment by t-sommer** [comment]
The FMU export is based on the S-function target (`rtwsfcn.tlc`) that generates C code with dependencies on libraries that are part of the MATLAB installation, so a pure C code FMUs is not possible.

**Comment by chrbertsch** [comment]
Would changing the CS FMU build to a `grt.tlc` be a too large  a change? With this, source code FMUs should be possible.

**Comment by t-sommer** [comment]
> Would changing the CS FMU build to a grt.tlc be a too large a change?

Yes. The generated code is very different from the S-function.

> With this, source code FMUs should be possible.

Yes.
