### ISSUE TITLE
Problem with FMIKit in Simulink Library browser

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#30]
When in installing the alpha3 mlapp in ML/SL 2016b, I get the following error in the library browser: 
![image](https://user-images.githubusercontent.com/16363372/58176838-77a00500-7ca3-11e9-9803-ca2050d1024d.png)
and the FMIKit Block is not displayd.

When I click on the "Fix" I get
![image](https://user-images.githubusercontent.com/16363372/58179516-a4a2e680-7ca8-11e9-8bb6-3065de4a1dbb.png)
Then  a modified version of the slx file is generated and stored
[FMIKit_blocks.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3207659/FMIKit_blocks.zip)
Only then the FMIKit Block appears in the Simulink library browser,

**Comment by t-sommer** [comment]
I can't reproduce the problem with R2016b after the library has been resaved, even by re-installing the FMI Kit app.

**Comment by t-sommer** [comment]
When I follow https://de.mathworks.com/help/simulink/ug/adding-libraries-to-the-library-browser.html in R2012b (the oldest supported version) I get an error:

```
>> set_param(gcs,'EnableLBRepository','on');
block_diagram does not have a parameter named 'EnableLBRepository'
```
