### ISSUE TITLE
Support for ninja as generator

### ISSUE THREAD

**Issue by svanimisetti** [CATIA-Systems/FMIKit-Simulink#300]
When using older distributions of GCC (TDM 4.5.1), I get the following error as _**mingw32-make.exe**_ was not included. Is it possible to substitute this with more modern make systems such as Ninja?. The drop down in the codegen settings (CMake->CMake generator) does not include Ninja as yet.

```
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".
CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".
CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

**Comment by t-sommer** [comment]
On Windows only MSVC is supported (see [docs/fmu_export.md](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md)).
