### ISSUE TITLE
Changing start values for inputs when using grtfmi.tlc

### ISSUE THREAD

**Issue by svanimisetti** [CATIA-Systems/FMIKit-Simulink#304]
I noticed that the start values are hardcoded to "0" when generating the modelDescription.xml.

https://github.com/CATIA-Systems/FMIKit-Simulink/blob/87cacf72a030650d042fb99b2d9fbfb17eec3a01/grtfmi/grtfmixml.tlc#L225-L227

As per specification, the FMU shall initialize the values using "start" values if the calling function does not initialize the inputs values to the FMU. When I manually edit the modelDescription.xml after creating the FMU, it does not seem to have an effect on the FMU results. Is this expected? I am assuming that there is nothing that is initializing the FMU using start values.

Also, is there a way to provide start values using an inport block property via Simulink? Not sure how feasible this is to implement, but being able to modify the start values will be a good feature to have.

**Comment by t-sommer** [comment]
> I noticed that the start values are hardcoded to "0" when generating the modelDescription.xml.

`0` is the initial value of the inputs.

> As per specification, the FMU shall initialize the values using "start" values if the calling function does not initialize the inputs values to the FMU. When I manually edit the modelDescription.xml after creating the FMU, it does not seem to have an effect on the FMU results. Is this expected? I am assuming that there is nothing that is initializing the FMU using start values.

The XML must not be changed after export (see https://github.com/modelica/fmi-standard/releases/download/v2.0.2/FMI-Specification-2.0.2.pdf, p. 56).

> Also, is there a way to provide start values using an inport block property via Simulink? Not sure how feasible this is to implement, but being able to modify the start values will be a good feature to have.

In FMI Kit you can set the start values via the block dialog.
