### ISSUE TITLE
FMU error "undefined symbol: rt_DestroyIntegrationData"

### ISSUE THREAD

**Issue by lucasrm25** [CATIA-Systems/FMIKit-Simulink#305]
Hi @t-sommer  and @dhenriksson. I am trying to export Model Exchange FMUs for linux but I have been running into some issues.
I was able to "fix" the problems until Issue 3 (see below), but I am still not able to make it work.
Could someone please give me some support on this issue?

<br>

My setup:

_rtwsfcnfmi --> Model Exchange
Red Hat 7.6 (Maipo)
Matlab R2018b
cmake-3.20.2-linux-x86_64_

<br>

### Error:

When trying to build the model in Simulink I get the following error
```
/home/FMI/FMIKit-Simulink-3.0-alpha.1/rtwsfcnfmi/fmi2Functions.c:289:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/FMI/FMIKit-Simulink-3.0-alpha.1/rtwsfcnfmi/fmi2Functions.c: In function 'fmi2SetInteger':
/home/FMI/FMIKit-Simulink-3.0-alpha.1/rtwsfcnfmi/fmi2Functions.c:322:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < nvr; i++) {
```

adding `-std=c99` or `-std=gnu99` to the Simulink configuration options:  Code Generation > CMake >custom compiler optimization flags, does not help.

### Solution:
Add the following line to https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/rtwsfcnfmi/CMakeLists.txt
```
set_property(TARGET ${MODEL_NAME} PROPERTY C_STANDARD 99)
```

### Error:

After solving the first problem I get this new error when building the Simulink model (same as in #270):
```
/home/FMI/FMIKit-Simulink-3.0-alpha.1/rtwsfcnfmi/sfunction.c:146:26: error: lvalue required as left operand of assignment
   ((char *)inputSignals) += typeSize;
                          ^
gmake[2]: *** [CMakeFiles/TestModel.dir/sfunction.c.o] Error 1
gmake[1]: *** [CMakeFiles/TestModel.dir/all] Error 2
gmake: *** [all] Error 2
```

### Solution:

Change
https://github.com/CATIA-Systems/FMIKit-Simulink/blob/87cacf72a030650d042fb99b2d9fbfb17eec3a01/rtwsfcnfmi/sfunction.c#L146
to
```
inputSignals = ((char *) inputSignals) + typeSize;
```

## Issue 3:

I am now finally able to build and generate the FMU.
However, when I import the FMU back to Simulink and run the model I get the following error
```
Error in supplied FMU: Unable to load dynamic library '/home/test/slprj/_fmu/1dc3da4752d08289c354db2e07fffe90/TestModel/binaries/linux64/TestModel.so': 
/home/test/slprj/_fmu/1dc3da4752d08289c354db2e07fffe90/TestModel/binaries/linux64/TestModel.so: undefined symbol: rt_DestroyIntegrationData. 
For more information, see the FMU troubleshooting documentation.
```

So, it seems the FMU is not being able to find the function `rt_DestroyIntegrationData`. The other rt_** functions are also not being found (I tested commenting out the lines where rt_DestroyIntegrationData is called).

Am I missing something?

_Obs1: I am testing with a super simple model (input > gain > output)
Obs2: I have tested with FMIKit 3.0-alpha.1 and also 2.9_

**Comment by t-sommer** [comment]
I can export an rtwsfcnfmi.tlc FMU successfully with e472af011e3bdab45994dcdefb28ca5592348a88 on R2022a / Ubuntu 20.04. Please reopen if the problem persists.
