### ISSUE TITLE
FMIKit-Simulink-2.9 Error "Undefined Identifier Units"

### ISSUE THREAD

**Issue by Wolfgang71** [CATIA-Systems/FMIKit-Simulink#308]
Hi,

I try to compile an FMU using FMIKit for Simulink 2.9 and Matlab 2020b. Model settings are fixed-step ode1(Euler) with VC2019 Professional as compiler and grtfmi.tlc as target file. For different models I always get the same error message:

Error: File: C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 24
Undefined identifier Units
Main program:
==> [00] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 30
The left-hand side of a . operator must be a valid scope identifier
Main program:
==> [00] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 39
The argument for an [] operation must be a repeated scope symbol, a vector, or a matrix
Main program:
==> [00] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 49
The left-hand side of a . operator must be a valid scope identifier
Main program:
==> [00] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
 Build Summary  1
Elapsed: 0.15 sec
Top model targets built:

Model                Action  Rebuild Reason                                    
===============================================================================
FMU_First_Try_clean  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 6.648s
Error: File: C:\xxx\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 24
Undefined identifier Units

Personal and path information is replaced by "xxx".
I could not find any related information on the net.
Does anybody have an idea where this comes from?

Thanks and regards,
Wolfgang

**Comment by t-sommer** [comment]
Can you reproduce the problem with [v3.0-alpha.2](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.2)?

**Comment by Wolfgang71** [comment]
No, with v3.0-alpha.2 the problem is gone and an FMU is generated.
