### ISSUE TITLE
FMI KIT 2.9 Issues with name of Model Description XML file

### ISSUE THREAD

**Issue by mdeppe** [CATIA-Systems/FMIKit-Simulink#312]
When reading the FMI 2.x specification they prefer the filename "**m**odelDescription.xml".
Nevertheless if you want to import an FMU archive using this naming convention the "Load" or "Reload" of the FMU fails in SIMULINK. The MATLAB console window shows this warning "_WARNING: Failed to read model description. C:\temp\SolvingExample\modelDescription.xml (The system cannot find the file specified)_". Indeed the folder used to extract the archive is empty.
**Workaround**: Rename from "modelDescription.xml" to "**M**odelDescription.xml" in the FMU archive and the FMU can be loaded.
Tested with MATLAB version 2019a and FMI KIT 2.9 
So two things here:

- Behaviour is against the FMI specification
- The error/warning message is not helpful at all to discover the root cause

**Comment by t-sommer** [comment]
Can you provide to steps to reproduce the problem?

**Comment by mdeppe** [comment]
Create new SIMULINK model in current working dir
Add FMI Block from the FMI Kit Library
Open the BLock mask
Press Load and select an FMU from the working dir
=>Nothing happens except warning in console (see above)

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by mdeppe** [comment]
[SolvingExample.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/7284423/SolvingExample.zip)

**Comment by t-sommer** [comment]
The FMU has an illegal modelDescription.xml (check with [FMU Check](https://fmu-check.herokuapp.com/)):

```
Validation failed. 1 problem was found:

ERROR (line 18, column 0): Element 'VendorAnnotations': Missing child element(s). Expected is ( Tool ).
```
