### ISSUE TITLE
Error with FMU Export using rtwsfcnfmi.tlc and MinGW Make

### ISSUE THREAD

**Issue by gowthamsrinivasan** [CATIA-Systems/FMIKit-Simulink#313]
I am using MATLAB 2018b, to export a Cosimulation FMU.

Target : rtwsfcnfmi.tlc
CMake generator : MinGW 

I am getting the following error:

![image](https://user-images.githubusercontent.com/33269562/136938010-7d23b256-a46c-40ea-9f46-8920ab6ac2ff.png)

I could successfully generate FMU with Visual Studio 15 2017 Win64 CMake generator.

**Comment by t-sommer** [comment]
MinGW is not a supported compiler on Windows (see https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/fmu_export.md).
