### ISSUE TITLE
FMU Name

### ISSUE THREAD

**Issue by ScienticToolsTeamLTS** [CATIA-Systems/FMIKit-Simulink#317]
Is it possible to define a different name for the FMU then the Simulink one ?
If not is it possible to add this feature ?
Thanks you.

**Comment by t-sommer** [comment]
What do you mean by "name for the FMU"?

**Comment by ScienticToolsTeamLTS** [comment]
Names of zip and binary files.
On DYMOLA it is possible to have a model called A.mo and to compile it into a FMU that will be named something else, B.fmu.

**Comment by t-sommer** [comment]
With grtfmi.tlc you cannot set the FMU's filename in the target settings but you'll have to rename the generated file.

**Comment by ScienticToolsTeamLTS** [comment]
Understood, thank you.
