### ISSUE TITLE
Matlab parsim does not work with imported FMU

### ISSUE THREAD

**Issue by MattAndrian** [CATIA-Systems/FMIKit-Simulink#318]
I have a Simulink file containing an FMU loaded with FMIKit 2.9. When I try to simulate it from the Matlab command line, using the "parsim" command from the parallel computing toolbox, I get the following error message: "The "FixedStepDiscrete" solver cannot be used to simulate block diagram 'TestParsim' because it contains continuous states" The same simulation works fine with the "sim" command. I generated a test case to demonstrate the issue. I am using Matlab R2021a on Windows 10 computer.

Test case:
1. Generate file in Dymola (Input -> Gain of 2 -> output) (TestParsim.mo)
2. Export as FMU, using discrete fixed step solver Euler with step size 1 (TestParsim.fmu)
3. Import FMU into Simulink with FMIKit 2.9, providing a discrete step as input and setting the Simulink solver to discrete with fixed step size of 1 to match the FMU. (TestParsim.slx)
4. Simulate from the Matlab command line with different times for the input step. Script shows how "sim" works, but "parsim" does not. (TestParsimScript.m)

[TestParsim.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/7486339/TestParsim.zip)

**Comment by t-sommer** [comment]
The above example runs fine with [v3.0-alpha.3](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.3).

**Comment by MattAndrian** [comment]
Awesome! Thank you for your support!
