### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMIKit-Simulink#320]
I export Cosimulation FMUs with Dassl from Dymola 2021x, importing them to Simulink 2020b using FMIKit 2.9.
At the end of the simulaton, I get a strange error message (ok I don't worry since I already have the desired result ;-):

... Error message from FMU_PMDC
INFO(4) = 1 and TSTOP (=5.000000e-01) before TOUT (=5.000000e-01).
Failed to do step
Failed to do step. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).
An error occurred while running the simulation and the simulation was terminated
Caused by:
Error in 'PMDC_DRV_2SpeedControlled/FMU_PMDC' while executing C MEX S-function 'sfun_fmurun', (mdlOutputs), at time 0.5. 
Unexpected Standard exception from MEX file.
What() is:Failed to do step. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).

**Comment by t-sommer** [comment]
The error handling has already been improved in the latest alpha. Please reopen if you can reproduce the issue with [v3.0-alpha.3](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-alpha.3).

**Comment by AHaumer** [comment]
Well, tried v.3.0-alpha.3:
[PMDC_DRV_1CurrentControlledStandStill/FMU] 
... Error message from FMU
 -> Error
[PMDC_DRV_1CurrentControlledStandStill/FMU] INFO(4) = 1 and TSTOP (=2.000000e-01) before TOUT (=2.000000e-01).
 -> Error
[PMDC_DRV_1CurrentControlledStandStill/FMU] 
 -> Error
An error occurred while running the simulation and the simulation was terminated
Caused by:
Error reported by S-function 'sfun_fmurun' in 'PMDC_DRV_1CurrentControlledStandStill/FMU':
The FMU reported an error.
