### ISSUE TITLE
Source code button unavailable

### ISSUE THREAD

**Issue by FR251508** [CATIA-Systems/FMIKit-Simulink#323]
Hi, 
In a project  need to generate C code from my simulink FMU, but presently this option is grey. Is their any reason of this grey button (advanced tab) ? 
BR
François

**Comment by t-sommer** [comment]
The `Use Source Code` checkbox is only enabled if the FMU is an FMI 2.0 source code.

**Comment by FR251508** [comment]
Hi,
I get a licence in order to create an FMU has an 2.0 source code. 
In other issues have seen FMIKit need Visual Studio... now when I Apply with Source code option I have the following error :
fatal error C1083: Impossible d'ouvrir le fichier include: 'sfun_fmu_fmi2_cs.c : no such file in directory 
but command open sfun_fmu_fmi2_cs, open the file.
if need minimal not working :) exemple
[electrolysis.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/7705290/electrolysis.zip)

**Comment by t-sommer** [comment]
Can you describe your goal and provide steps to reproduce the problem?

**Comment by FR251508** [comment]
I am trying to use FMIKit with an Opal RT real time simulator, this procedure has already been used. The procedure is describle in the attach document.
[Procedure_FMU_RT_LAB.pdf](https://github.com/CATIA-Systems/FMIKit-Simulink/files/7710524/Procedure_FMU_RT_LAB.pdf)

**Comment by t-sommer** [comment]
Can you export your model with the `grt.tlc` target?

**Comment by FR251508** [comment]
Hi,
no I can't, model setting I have two grt.tlc options (Generic Real Time Target & Create Visual C/C++ Solution File for Simulink Coder) I've try both it doesn't compil.

**Comment by t-sommer** [comment]
Can you share the build log?

**Comment by FR251508** [comment]
whatever option I try in Log level, I havn't any Log file , the best I can give you is :
Matlab command :
Compiling S-function sfun_Model_Exchange_VS2019_32Bits
Building with 'Microsoft Visual C++ 2019 (C)'.
Failed to compile S-function
sfun_Model_Exchange_VS2019_32Bits.c
D:\GIT\sfun_Model_Exchange_VS2019_32Bits.c(15): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'sfun_fmu_fmi2_cs.c'ÿ: No such file or directory
Diagnostic Viewer
Error in S-function 'electrolysis/SM_FMU/FMU': S-Function 'sfun_Model_Exchange_VS2019_32Bits' does not exist

**Comment by t-sommer** [comment]
The attached FMU does not compile:

```
>fmpy info FMU_Cosim.fmu
...
   Creating library FMU_Cosim.lib and object FMU_Cosim.exp
all.obj : error LNK2019: unresolved external symbol dgelsy_ referenced in function Modelica_Math_Matrices_LAPACK_dgelsyx_0vec_M
FMU_Cosim.dll : fatal error LNK1120: 1 unresolved externals
```

It seems like there are sources missing or dependencies on external libraries exist.

**Comment by t-sommer** [comment]
This is an issue with the Dymola FMU export. Please contact Dymola support.
