### ISSUE TITLE
fmiwrapper error C2039 (#47)

### ISSUE THREAD

**Issue by georgathome** [CATIA-Systems/FMIKit-Simulink#324]
Error message (already discussed in issue #47):
```
fmiwrapper.inc(1340,60): error C2039: "PARAM" ist kein Member von "P_PARAM_T_".
...
The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to build FMU
```

Environment:
- Win10 x64
- grtfmi
- Matlab 2019b
- VS 2019
- FMIKit v2.9

**Comment by t-sommer** [comment]
Can you reproduce the problem with the latest [alpha release](https://github.com/CATIA-Systems/FMIKit-Simulink/releases)?

**Comment by georgathome** [comment]
Yes, it's almost exactly the same:
`fmiwrapper.inc(1339,60):` a.s.o. as above

**Comment by t-sommer** [comment]
Can you share a model and steps to reproduce the problem?

**Comment by georgathome** [comment]
I can not share the original model.
I tried to simplify the model so that it can be shared, but then the error is:
```
### Building FMU
Error: could not find CMAKE_GENERATOR in Cache
```

**Comment by t-sommer** [comment]
Please reopen when you can provide steps to reproduce the problem.

**Comment by georgathome** [comment]
I would like to create a model I can share.. but for that, I first need to resolve the error above! Any hints on that? 
I already checked that the toolchain works by building [https://github.com/modelica/reference-fmus](url).
