### ISSUE TITLE
Multiple instances of a FMU in 1 simulink project

### ISSUE THREAD

**Issue by haitevds** [CATIA-Systems/FMIKit-Simulink#326]
Hi,

I'm importing a (CATIA generated) co-simulation FMU  2 times to create multiple instances of a model in a r2020a Simulink project.  Changes in behavior of these instances are expected when setting specific variables to different values.  However, both models behave exactly the same and reflect the behavior of the instance where last modifications take place.  
Do I have to take specific actions to create multiple instances of a FMU using the CATIA import ?  Using the Simulink standard FMU import this multiple instance creation does work so I assume the quality of the generated FMUs is ok.

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by haitevds** [comment]
Can I send it to you by wetransfer ?

**Comment by haitevds** [comment]
If everything went well you've been invited.

**Comment by haitevds** [comment]
Sort of..  Instances are still not correct. But now I see that one of them is dominant. 
In the 2.9 version the most recent changed FMU dominated the behavior. In this 3.0 alpha 3 version the same instance remains dominant.

**Comment by haitevds** [comment]
Could you access my FMU?

**Comment by haitevds** [comment]
FYI  
during initialization still 2.9.0 is mentioned

>> FMIKit.initialize
Initializing FMI Kit 2.9.0

**Comment by t-sommer** [comment]
Is anything inside the model using static variables, e.g. an S-function?

**Comment by haitevds** [comment]
There is no S-functions as far as I can see.

I used to Matlab workspace to initialize parameters using an dedicated M file that is called at PreLoadFcn of the model. These values are imported in the Simulink model using Constant blocks and sometimes copied to Goto blocks for reuse at several locations in the model.  In other values that appear as Constant blocks with manually entered values.
For both situations changing these parameters in de FMU dialog results in the strange behavior of mixing up values between the instances.

However:  When I make a variation to an initial condition value of an integrator in one of the instances then it is handled the right way.

I will make a very simple model next week and will do an additional check.



ir. Haite van der Schaaf | Senior Project Manager | Measurement & Controls Systems
MARIN | T +31 317 49 33 14 | M +31 611 34 42 86 | ***@***.******@***.***> | www.marin.nl<http://www.marin.nl>

[LinkedIn]<https://www.linkedin.com/company/marin> [YouTube] <http://www.youtube.com/marinmultimedia>  [Twitter] <https://twitter.com/MARIN_nieuws>  [Facebook] <https://www.facebook.com/marin.wageningen>
MARIN news:

**Comment by haitevds** [comment]
A simple example is included now.

**Comment by t-sommer** [comment]
The problem is that as of R2019a, block parameters are static in the exported GRT code, so a change in one parameter applies to all instances. You don't experience this problem with the native Simulink FMU import, because they re-extract the FMU for each block (under `slprj/_fmu`).

You can achieve the same behavior with the FMI Kit import if you select a different `Unzip directory` for each block on the `Advanced` tab.
