### ISSUE TITLE
Support for Sourcecode FMU from OpenModelica

### ISSUE THREAD

**Issue by Thandre** [CATIA-Systems/FMIKit-Simulink#329]
I have exported an FMU from OpenModelica. The simulation is working if I use the prebuild binaries of the FMU. Both methods (CS and ME) work. I need to run the simulation on a realtime plattform and therefore have to use the source code of the FMU. Unfortunately I don't get this up and running.
I managed to compile the FMU with Visual C++ Compiler. To get this working I had to tweak the compiler flags in the mex arguments. But when I start the simulation Matlab crashes during model initialisation.
Is there support for source code FMUs other than Dymola?

**Comment by Thandre** [comment]
[Testmodel.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/7869198/Testmodel.zip)
Sure. I also included the Modelica-File and my changes to the applyDialog.m
I also had to install the pthreads-w32 library to resolve the missing symbols with Visual C++ 2017 Compiler.

**Comment by t-sommer** [comment]
> Is there support for source code FMUs other than Dymola?

Generally any FMI 2.0 source code FMU should work. However this FMU seems to compile only on Linux. This might be related to

https://github.com/OpenModelica/OpenModelica/issues/8283,
https://github.com/OpenModelica/OpenModelica/issues/3790, and
https://github.com/OpenModelica/OpenModelica/issues/3288
