### ISSUE TITLE
Error exporting fmu of rtwsfcnfmi.tlc using matlab 2021b

### ISSUE THREAD

**Issue by qilianshanlgz** [CATIA-Systems/FMIKit-Simulink#337]
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType scope

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by qilianshanlgz** [comment]
> Can you provide steps to reproduce the problem?

step1：open simulink model；
step2：ctrl+E→Code Generation→System target file：rtwsfcnfmi.tlc
step3：ctrl+B
step4：Then，The following error message is displayed：
 Writing source file rtGetInf.c
### TLC code generation complete.
### Writing modelDescription.xml
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType **scope**
Main program:
==> [00] C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc:<NONE>(116)
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType scope
Main program:
==> [00] C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc:<NONE>(116)
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType scope
Main program:
==> [00] C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc:<NONE>(116)
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType scope
Main program:
==> [00] C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc:<NONE>(116)
 Build Summary  
Top model targets built:

Model       Action  Rebuild Reason                                    
======================================================================
controller  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 6.805s
Error: File: C:\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\rtwsfcnfmixml.tlc Line: 116 Column: 36
Unable to find CGTypeIdx within the DataType scope
