### ISSUE TITLE
Set solver tolerances of imported CS FMUs

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#34]
It would be beneficial to set the solver tolerances for imported CS FMUs in the mask of an FMI-Kit FMU-Block.

For Dymola exported CS-FMUs: This would be possible through the function fmi2SetupExperiment for dymoaSolver exported FMU’s since Dymola 2019 and has always been available for cvode exported fmu’s.

**Comment by t-sommer** [comment]
@chrbertsch, please let us know if this works for you. Attached is the pre-built app installer (remove `.zip` extention)

[FMIKit-feature-relative-tolerance.mlappinstall.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3280416/FMIKit-feature-relative-tolerance.mlappinstall.zip)

**Comment by chrbertsch** [comment]
Works fine, Thanks!

When I open a Simulink model containing an FMIKit-Block that was created with an earlier version of FMI-Kit, the value for the relative tolerance behaviour is "0". Which tolerance is used in this case?

**Comment by t-sommer** [comment]
`0` means "tolerance not defined". It's up to the FMU to decide what to do.
