### ISSUE TITLE
Error exporting fmu from simunlink model with s function

### ISSUE THREAD

**Issue by qilianshanlgz** [CATIA-Systems/FMIKit-Simulink#340]
Error when exporting fmu from simunlink model containing s function, s function is written in m code.
The error message is as follows:
Error: File: C:\MATLAB\R2021b\rtw\c\tlc\public_api\utils_api.tlc Line: 473 Column: 10
%exit directive:  Simulink Coder Fatal in block: "[forcepid/S-Function](matlab:das_dv_hyperlink('DAS','mdl','forcepid/S-Function'))", block type "S-Function": MFile S-functions without a corresponding TLC file are not supported. You can inline your S-function (pid_control) by creating a TLC file for it. You can also remap your S-function to C by creating a corresponding C Mex source file and a pid_control.tlc file in the same directory as the MFile S-function which contains (on the first line):
  %% CallAsCMexLevel1
or
  %% CallAsCMexLevel2

**Comment by t-sommer** [comment]
[Level-2 MATLAB S-Functions](https://de.mathworks.com/help/simulink/sfg/writing-level-2-matlab-s-functions.html) are not supported for FMU export.
