### ISSUE TITLE
FMIKit-3.0 Need to automatically activate parameters (for setting initial conditions later), from list

### ISSUE THREAD

**Issue by mast0rcylinder** [CATIA-Systems/FMIKit-Simulink#342]
Issue:
Even with FMIKit-3.0 we cannot set initial conditions for an FMU,  until we manually open the FMU, go to the variables tab, navigate through many thousands of FMU 'variables', to the 200 or so we wish to change at Run Time (initial conditions), modify them slightly (type in the variable window) and then apply.  All this before they show up in the s-functions parameters window (and thus enabled to be changed at run time).

Desired Behavior:
We would like a method to read in a list of path.parameter names and have FMIKit put all of them into the s-function parameters window, and thus enabling those parameters for change at Run time.  Or some other way of enabling a subset of parameters to be changed at run time)

A second issue is a lack of understanding on our part. 
What is the connection between valueReference# with the parameter path.name  (how are they used)?
In one test case we identified the same parameter with 6 different paths in the model with 6 different valueReferences it was only the last one we changed at run time that actually affected the initial condition of a test run.  While this is likely model dependent (which is the first in the propagation of that signal?).  Any info regarding how this works may help us find the correct parameters to change.

**Comment by t-sommer** [comment]
> What is the connection between valueReference# with the parameter path.name (how are they used)?

This is completely under the control of the exporting tool.

**Comment by mast0rcylinder** [comment]
I'm sorry, Torsten, I don't quite understand that (my inexperience).  It is FMIKit that interfaces an FMU to Simulink.  It looks to be FMIKit that we are interacting with when we 'open' the FMU (in Simulink), and navigate to the said parameters.  It looks to be FMIKit that creates the FMU folder, not sure but it looks like FMIKit also creates the modelDescription.xml.

It would be nice is if we could bypass any dependency on variable showing up in the 's-function parameter' window or the order that they show up in that window...
Instead having a way to query the modelDescription.xml file (finding the parameters of interest by path.name), obtaining the associated valueReference# and use that to change initial condition parameters.
(The current approach we are working on is writing a partial calibration file which is read in and applied at run time. )

**Comment by mast0rcylinder** [comment]
This was helpful Torsten, thank you.  
I modified this file to read in a list of Override parameters and only those matching are added to the dialog parameters.

**Comment by t-sommer** [comment]
This function gives you the dialog parameters and the corresponding index in the S-function parameters:

```MATLAB
function dialog_params = get_dialog_params(block)
% returns a struct array of the dialog parameters

% load the block dialog w/o showing it
dialog = FMIKit.showBlockDialog(block, false);

dialog_params = struct([]);

index = 22;  % one-based index of the dialog parameter within the S-function parameters

for i = 0:dialog.modelDescription.scalarVariables.size-1
  
  variable = dialog.modelDescription.scalarVariables.get(i);
  
  if dialog.startValues.containsKey(variable.name)
      index = index + 5;
      dialog_params = [dialog_params struct(...
          'variable_name', char(variable.name),...
          'dialog_parameter', char(variable.dialogParameter),...
          'index', index,...
          'start_value', char(dialog.startValues.get(variable.name)),...
          'description', char(variable.description)...
          )];
  end

end

end
```
