### ISSUE TITLE
Undeclared variable reference 'instance' in .\FMIKit-Simulink-3.0-alpha.5\grtfmi\fmi2Functions.c (should be 's_instance')

### ISSUE THREAD

**Issue by VonSquiggles** [CATIA-Systems/FMIKit-Simulink#346]
In trying to export a model using FMIKit-Simulink-3.0-alpha.5, got an error regarding variable name 'instance' in line 209 and 307 of 
'.\FMIKit-Simulink-3.0-alpha.5\grtfmi\fmi2Functions.c' being undefined. Changed variable name to 's_instance' as referenced in other relevant functions and compilation was then successful.

**Comment by t-sommer** [comment]
Duplicate of #345.
