### ISSUE TITLE
FMU Generation error: RTWSFCNFMI.TLC- Undefined identifier mxClass

### ISSUE THREAD

**Issue by jyothiprasadkk** [CATIA-Systems/FMIKit-Simulink#347]
I am getting below error when trying to generate FMU from simulink model which has dependency with mex files.

Error: “Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 281 Column: 65 Undefined identifier mxClass”

Target used : RTWSFCNFMI. TLC

FMU Type : Co-simulation

FMI KIT version used : FMIKit-Simulink-3.0-alpha.4

### Generating code into build folder: K:\_Output\mcArchCode\ARB_new_sfcn_rtw_fmi
Matching "From" for "Goto" '[ARB_new/plant/Goto15](matlab:open_and_hilite_hyperlink ('ARB_new/plant/Goto15','error'))' not found
Component:Simulink | Category:Block warning
S-function parameter 'CompareToConstant_const' can not be made tunable because its data type is not a built-in type [3 similar]
Component:Simulink | Category:Model warning
### Generating TLC interface API for custom data
.
### Caching model source code
Simulink Coder -- In block "[ARB_new/plant/Power Electronics/Scope](matlab:das_dv_hyperlink('DAS','mdl','ARB_new/plant/Power Electronics/Scope'))", block type "Scope": Scope blocks not currently supported for S-Function code format.  Block disabled. [2 similar]
Component:Simulink | Category:Model warning
...............................................................................
...............................................................................
...............................................................................
...............................................................................
.....
    ### Writing header file ARB_new_sf_types.h
    ### Writing source file ARB_new_sf.c
.
    ### Writing header file ARB_new_sf_private.h
    ### Writing header file ARB_new_sf.h
    ### Writing header file rtwtypes.h
    ### Writing header file multiword_types.h
    ### Writing header file ARB_new_sid.h
    ### Writing header file ARB_new_mid.h
.
    ### Writing source file ARB_new_sf_data.c
    ### Writing header file rtGetNaN.h
    ### Writing source file rtGetNaN.c
    ### Writing header file rt_nonfinite.h
    ### Writing source file rt_nonfinite.c
    ### Writing header file rt_defines.h
.
    ### Writing header file rtGetInf.h
    ### Writing source file rtGetInf.c
### TLC code generation complete.
.
Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 270 Column: 38
Attempt to call a non-function value: GetMxClass
Main program:
==> [00] K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc:<NONE>(270)
Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 281 Column: 65
Undefined identifier mxClass
Main program:
==> [00] K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc:<NONE>(281)
Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 281 Column: 65
Values of NULL type cannot be expanded
Main program:
==> [00] K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc:<NONE>(281)
Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 270 Column: 38
Attempt to call a non-function value: GetMxClass
Main program:
==> [00] K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc:<NONE>(270)
 Build Summary  1
Elapsed: 0.11 sec
Top model targets built:

Model    Action  Rebuild Reason                                    
===================================================================
ARB_new  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 14.39s
Error: File: K:\mcArch\mcArch_sensLessCont\arbModel\FMIKit-Simulink-3.0-alpha.4\rtwsfcnfmi\sfcnmei.tlc Line: 281 Column: 65
Undefined identifier mxClass

**Comment by jyothiprasadkk** [comment]
By Keeping breakpoints in TLC generation process, we are able to narrowdown to the parameter which is causing this error.

This issue is solved by changing the storage class of one of the tunable parameter from ExportedGlobal to SimulinkGlobal(Auto)

**Comment by t-sommer** [comment]
Thanks for sharing your solution.
