### ISSUE TITLE
grtfmi.tlc fails for referenced models w/ parameters and parameter DefaultParameterBehavior=tunable

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMIKit-Simulink#355]

**Comment by tabytitus** [comment]
Test files to reproduce error
[FMU_GEN_test_V2.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/8740293/FMU_GEN_test_V2.zip)

**Comment by tabytitus** [comment]
![image](https://user-images.githubusercontent.com/105926290/169534160-eb38e559-fb72-4673-912a-16fbf2d5c03a.png)

**Comment by tabytitus** [comment]
The fix seems to work for this issue for smaller models but when i try to generate for bigger models with lots of parameters either matlab crashes or compiler gives an error (ex: compiler out of heap space)

**Comment by nl78** [comment]
After some analysis, the compiler issue is not directly linked to issue-355. In case of "large model" (= lot of ports and usage of large vectors for these ports), it seems that fmiwrapper.inc becomes HUGE and overloads compiler memory.
I suggest the attached patch
[0001-Handle-variables-w-RegisteredIdentifier-in-grtfmi.tl.patch.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/8984282/0001-Handle-variables-w-RegisteredIdentifier-in-grtfmi.tl.patch.zip)
.
