### ISSUE TITLE
FMUArchive not found error: Matlab r2021b 

### ISSUE THREAD

**Issue by hadrianhu888** [CATIA-Systems/FMIKit-Simulink#356]
**I am trying to generate the FMU and I keep getting this when I try to run the build:** 

Top Model Build  
### Initial pass through model to cache user defined code
.
### Writing header file rtwtypes.h
.
### Writing source file custom_bouncing_ball_sf_data.c
.
### Writing header file rtGetInf.h
.
###
###
### Creating FMU archive
 Build Summary  
Top model targets built:

Model                 Action  Rebuild Reason                                    
================================================================================
custom_bouncing_ball  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 8.934s
The call to rtwsfcnfmi_make_rtw_hook, during the after_make hook generated the following error:
    ROOTDIR directory "FMUArchive" does not exist.

The build process will terminate as a result.

Caused by: ROOTDIR directory "FMUArchive" does not exist.
Component:Simulink | Category:Block diagram error

**I am also unable to find the CMake Toolchain option.
I have the FMIKit-Simulink-2.7 in the working folder. 
Any help would be appreciated.** 

**_Thanks_**

**Comment by t-sommer** [comment]
Please reopen if the problem persists with [v3.0-beta.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-beta.1).
