### ISSUE TITLE
Undefined Unit Type with FMI Kit Simulink 2.9 in Matlab r2021a 

### ISSUE THREAD

**Issue by hadrianhu888** [CATIA-Systems/FMIKit-Simulink#357]
When I try to run the build, I get the following error: 

### Generating code into build folder: F:\GitHubRepos\fmi_test_example\fmi_setup_test_grt_fmi_rtw
The output(s) read after the base-rate model step reflects intervening minor time steps. To observe data that is a snapshot of output(s) at major time steps, do one of the following:
 * Place a Zero-Order Hold block before the continuous output port '[fmi_setup_test/del](matlab:open_and_hilite_hyperlink ('fmi_setup_test/del','error'))'. 
 * Clear [Single output/update function](matlab:configset.internal.open('fmi_setup_test','CombineOutputUpdateFcns');), and read model output values after model_output call and before model_update call. 
 For more details, see ["Single output/update function"](matlab:helpview([docroot '/rtw/csh/configparams/Simulink.ConfigSet.ListView.map'], 'Tag_ConfigSet_RTW_GRT_CombineOutputUpdateFcns')) in the Simulink documentation.
Component:Simulink | Category:Block warning
### Writing header file fmi_setup_test_private.h
.
### Writing modelDescription.xml
Error: File: D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 24
Undefined identifier Units
Main program:
==> [00] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 30
The left-hand side of a . operator must be a valid scope identifier
Main program:
==> [00] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 39
The argument for an [] operation must be a repeated scope symbol, a vector, or a matrix
Main program:
==> [00] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
Error: File: D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 49
The left-hand side of a . operator must be a valid scope identifier
Main program:
==> [00] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:MinMaxAttributes(76)
    [01] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc:VariableFMI2(113)
    [02] D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmixml.tlc:<NONE>(226)
 Build Summary  
Top model targets built:

Model           Action  Rebuild Reason                                    
==========================================================================
fmi_setup_test  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 19.882s
Error: File: D:\Program Files\Matlab\rtw\c\FMIKit-Simulink-2.9\grtfmi\grtfmilib.tlc Line: 76 Column: 24
**Undefined identifier Units**

I am not sure if this is a bug or if I am doing something wrong in Simulink with the setup. 

Any help would be appreciated!

**Comment by t-sommer** [comment]
Please reopen if the problem persists with [v3.0-beta.1](https://github.com/CATIA-Systems/FMIKit-Simulink/releases/tag/v3.0-beta.1).
