### ISSUE TITLE
Automate initialization of FMIKit App

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#36]
With the new app mechanism (which in general works great), I have after startup of MATLAB once to klick on the app to initialize it.  With the old installation method I could automatize this in the startup.m file. Is this also possible with the app?
Is the installation and initialization documented somewhere (cannot find it in the documentation folder)

**Comment by t-sommer** [comment]
To run the FMI Kit app automatically when you start MATLAB you can add the following lines to your `startup.m` file:

```matlab
apps = matlab.apputil.getInstalledAppInfo();

for i = 1:numel(apps)
    app = apps(i);
    if strcmp(app.name, 'FMI Kit')
        matlab.apputil.run(app.id);
        return
    end
end
```

The installation of the app follows the standard procedure and is explained in [this video](https://de.mathworks.com/videos/packaging-and-installing-matlab-apps-70404.html).

**Comment by chrbertsch** [comment]
Thanks. Would it be possible to provide this information in an installation documentation?
