### ISSUE TITLE
Merit 

### ISSUE THREAD

**Issue by svarig** [CATIA-Systems/FMIKit-Simulink#361]
Please consider providing methods to get and set FMU block parameter values and other attributes like type for imported FMUs. This would be helpful to conduct parametric variation studies for Simulink models with imported FMUs using scripts.

If this feature/capability already exists, please add the documentation and provide a simple example.

**Comment by suijiacai2016** [comment]
I also expect the feature.

**Comment by t-sommer** [comment]
The interface type can be set with

```MATLAB
FMIKit.setInterfaceType(gcb, 'CoSimulation');
```

The start values can be changed to any valid MATLAB expression with

```MATLAB
height = 1.5; % create a workspace variable
FMIKit.setStartValue(gcb, 'h', 'height'); % and use it as a start value
```

The MATLAB API is documented in https://github.com/CATIA-Systems/FMIKit-Simulink/blob/main/docs/fmu_import.md#matlab-commands.

**Comment by svarig** [comment]
Thank you for the enhancements!

It's still not clear how you get and set FMU model parameters. These are
typically different from model state or algebraic variables for which
getting and setting start values may apply.

Are the same methods meant to be used for both model parameters (non-time
varying) and variables? If so, can this be clarified in the API
documentation?

Thanks!
Subba

**Comment by t-sommer** [comment]
Can you clarify, based on an actual `modelDescription.xml`, what variables you want to get / set?
