### ISSUE TITLE
FMU-block not found in Simulink Library Browser?

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMIKit-Simulink#363]
I recently downloaded v3.0 and set the path in Simulink but can't locate the FMU-block in the library browser - my fault?

**Comment by t-sommer** [comment]
Did you run `FMIKit.initialize()`?

**Comment by AHaumer** [comment]
Yes, I did set the Matlab path, and I called FMIKit.initialize(), but it's not shown in Simulink Library Browser.
If I open FMIKit_blocks_R2012b.slx and drag the FMU-block, it works perfectly.

**Comment by AHaumer** [comment]
Sorry for bothering: After refreshing the Library browser the FMU-Block appears.
