### ISSUE TITLE
cmake generator fails to run

### ISSUE THREAD

**Issue by merlonus** [CATIA-Systems/FMIKit-Simulink#365]
Hi there,

As the title suggest, i get the following error when trying to generate a FMU-FIle:
"
The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to run CMake generator

The build process will terminate as a result.

Caused by: Failed to run CMake generator
"
I've installed the FMIKit-Simulink-3.0 and install cmake with a command suggested by simulink diagnostics. I have also set the model configuration parameters according to the documentation. I have tried generating x64 FMU-Files of my simulink models on matlab R2022a and R2021a. I have also updated my visual studio and selected the newest version (Visual Studio 17 2022) as the cmake generator.
I have tried using a cmake run command  such as:
G:\Ingenieurprogramme\MATLAB\R2022a\bin\win64\cmake\bin\cmake.exe
which seems to find the cmake.exe but as there error says, it fails to  run it.
Any suggestions?

thank you, very much!

**Comment by hadrianhu888** [comment]
Make sure there is no typo in the G:\Ingenieurprogramme\MATLAB\R2022a\bin\win64\cmake\bin\cmake.exe line. Sometimes an extra space can cause the cmake to not run. 
Also make sure the FMIKit.initialize() runs in G:\Ingenieurprogramme\MATLAB\R2022a\bin.
Typically, cmake is in  G:\Ingenieurprogramme\MATLAB\R2022a\c\rtw\FMIKit-Simulink-3.0\<cmake path>\bin\cmake.exe
