### ISSUE TITLE
Enable Simulink Help for FMI-Kit Block

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#37]
It would be good to enable the Simulink help for the FMIkit-Block.
Currently one gets 
![image](https://user-images.githubusercontent.com/16363372/59350214-d7765280-8d1b-11e9-93ed-e8a64dcc6690.png)

**Comment by t-sommer** [comment]
Solved with 9eed1c6b2ad175f79d1b87f71c6ac14afde7bb47
