### ISSUE TITLE
Tool coupling tools 

### ISSUE THREAD

**Issue by guidout** [CATIA-Systems/FMIKit-Simulink#373]
Some tools, like Siemens Amesim, can generate a hook with the FMU, running on another software, to review results while the simulation runs.
When importing an FMU created with tool coupling I get the following error in Simulink:

**[FMUtest_model/FMU] _fmi2ExitInitializationMode: tool coupling is required but an invalid model directory path "(null)" is provided -> Error
Error reported by S-function 'sfun_fmurun' in '[FMUtest_model/FMU](matlab:open_and_hilite_hyperlink ('FMUtest_model/FMU','error'))':
The FMU reported an error.**

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by guidout** [comment]
> Can you share an FMU to reproduce the problem?

Below is a simple FMU generated with Siemens Amesim and Tool Coupling enabled. (Extension changed to .zip to upload it)
It gets imported correctly but it doesn't run giving the error above.

To actually run this you will need Amesim installed and a license for it, but hopefully you get the error before that.

[ToolCouplingTest.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/9175786/ToolCouplingTest.zip)

For reference this is a screenshot where you can see that there is a amemodelpath parameter but the error says that the "path" is set to null. Not sure if it's the same path or something else.

![image](https://user-images.githubusercontent.com/6175248/180647212-6ee17ecc-ddb8-463e-ac98-505cd3fe1cdf.png)


Also, this could be a different bug, when I first import that FMU I don't get any errors. If I then change the value of amemodelpath to something else I get the following error. Is there an issue with string parameters? Or paths?

![image](https://user-images.githubusercontent.com/6175248/180647551-f8ff9ff4-9696-487e-b52b-396736318226.png)

**Comment by t-sommer** [comment]
Start values must be a valid MATLAB expression. For a string you have to add single quotes e.g. `'D:\FMIkit_Amesim_Import_test'`.

**Comment by guidout** [comment]
thank you for your answer. I have other parameters that are strings that seem to not require single quotes.
Wonder why.
I also found that an FMU exported from ADAMS doesn't work. I'll open a separate issue with a description.
