### ISSUE TITLE
MSC ADAMS FMU issue

### ISSUE THREAD

**Issue by guidout** [CATIA-Systems/FMIKit-Simulink#375]
When I try to run an FMU exported from ADAMS I get the error in the picture below. Attached is the simple FMU I'm trying (extension changed to .zip).
FMUcheck utility gives no errors and I can import and successfully run this FMU on another software or using the "native" FMU support from Simulink.
I'd be happy to debug but the error text is not very helpful.
[Controls_Plant_1.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/9184506/Controls_Plant_1.zip)

![image](https://user-images.githubusercontent.com/6175248/180866461-76cc3b2d-cae0-4eb9-a506-10c507b52b5c.png)

**Comment by t-sommer** [comment]
The model is not a legal FMI 2.0 FMU. From the [FMI 2.0 Spec, p. 69](https://github.com/modelica/fmi-standard/releases/download/v2.0.3/FMI-Specification-2.0.3.pdf):

>  The implementation must either implement all the functions of FMI for Model Exchange or all the functions of
FMI for Co-Simulation or both.

**Comment by guidout** [comment]
> The model is not a legal FMI 2.0 FMU. From the [FMI 2.0 Spec, p. 69](https://github.com/modelica/fmi-standard/releases/download/v2.0.3/FMI-Specification-2.0.3.pdf):
> 
> > The implementation must either implement all the functions of FMI for Model Exchange or all the functions of
> > FMI for Co-Simulation or both.

Thank you for the feedback. I can reach out to the ADAMS developers and ask for help. Would you care giving a more datiled pointer for the issue?
Did you use an FMU check utility? I used this https://github.com/modelica-tools/FMUComplianceChecker/releases and I got no warnings or errors
