### ISSUE TITLE
Missing file when initializing FMIKit-3.0 with Matlab r2022a 

### ISSUE THREAD

**Issue by hadrianhu888** [CATIA-Systems/FMIKit-Simulink#376]
I get this error message when I run FMIKit,initialize():

`Warning: "janklab-java-0.1-SNAPSHOT.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path (line 290)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 124)
In javaaddpath (line 71)
In FMIKit.initialize (line 55)
In fmi_init (line 2) 
Warning: "slf4j-log4j12-1.5.8.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path (line 290)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 124)
In javaaddpath (line 71)
In FMIKit.initialize (line 55)
In fmi_init (line 2) 
Warning: "slf4j-api-1.5.8.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path (line 290)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 124)
In javaaddpath (line 71)
In FMIKit.initialize (line 55)
In fmi_init (line 2) 
Warning: "log4j1-config-gui-0.1.1.jar" is already specified on static java path. 
> In javaclasspath>local_validate_dynamic_path (line 290)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 124)
In javaaddpath (line 71)
In FMIKit.initialize (line 55)
In fmi_init (line 2) 
Warning: Invalid file or directory 'D:\Program
Files\Matlab\rtw\c\FMIKit-Simulink-3.0\fmikit.jar'. 
> In javaclasspath>local_validate_dynamic_path (line 271)
In javaclasspath>local_javapath (line 187)
In javaclasspath (line 124)
In javaaddpath (line 71)
In FMIKit.initialize (line 55)
In fmi_init (line 2) 
**Unable to resolve the name 'fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION'.

Error in FMIKit.initialize (line 60)
jarVersion = char(fmikit.ui.FMUBlockDialog.FMI_KIT_VERSION);

Error in fmi_init (line 2)
FMIKit.initialize()**
 `

Not sure what the problem is, and I did a pull from the remote, and still no luck. 

Any help would be appreciated. 

Thanks

**Comment by t-sommer** [comment]
Please follow the steps in https://github.com/CATIA-Systems/FMIKit-Simulink#quick-start to install FMI Kit.

**Comment by hadrianhu888** [comment]
> Please follow the steps in https://github.com/CATIA-Systems/FMIKit-Simulink#quick-start to install FMI Kit.

I did follow the instructions, and it gave the same error message as above.

**Comment by YanceyYq** [comment]
hello
Has this problem been solved?
