### ISSUE TITLE
Could not use FMIKit's FMU in Simulink R2022a

### ISSUE THREAD

**Issue by hadrianhu888** [CATIA-Systems/FMIKit-Simulink#378]
I wonder why I cannot use the FMIKit's version of the FMU in Matlab R2022a? 
Is there any way I can import it to the same library as the rest of the Simulink standard library components? 

Thanks

**Comment by t-sommer** [comment]
FMI Kit 3.0 supports R2022. Please provide steps to reproduce the problem.

**Comment by hadrianhu888** [comment]
The problem is solved. 
FMIKit Simulink 3.0 worked on my work computer, and did not work on my personal computer. 
The reason was because for some reason the latest Github build did not contain: 

**'fmikit.jar'**

I would like to have a pull request to restore this .jar file back into the FMIKit-Simulink-3.0 build.
