### ISSUE TITLE
Guidance on using GRT FMI with Simscape

### ISSUE THREAD

**Issue by hadrianhu888** [CATIA-Systems/FMIKit-Simulink#387]
I have a repo here: 

[https://github.com/hadrianhu888/fmi_test_6](https://github.com/hadrianhu888/fmi_test_6)

And I keep getting **cannot call CMake error** with f_mi_test_GRT_1.slx_ file. 

What are the required settings for it to work? 

Thanks

**Comment by t-sommer** [comment]
This should be fixed with 227d0c37ad7292389292e5006fa3475305ca9f22.
