### ISSUE TITLE
Can't FMU Export in MATLAB R2021a

### ISSUE THREAD

**Issue by modernModelCreator** [CATIA-Systems/FMIKit-Simulink#388]
Dear FMIKit Team,
I would like to export FMU from my model with Model References, but can't export it. I used FMIKit-Simulink 3.0.
I've attached the model to this comment.
[TheModel.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/9847958/TheModel.zip)

**Comment by t-sommer** [comment]
I can successfully export the above model with 227d0c37ad7292389292e5006fa3475305ca9f22 and R2023a.
