### ISSUE TITLE
Don't remove square brackets from port names

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#39]
When a Simulink port name contains square brackets (e.g. Output[2]) the ModelDescription.xml will not contain these brackets (e.g. name="Output2").
Please keep the brackets!

**Comment by chrbertsch** [comment]
@fajansen :
The square brackets are used in FMI for serialization of Arrays. 
So a Simulink output Output being an array will be serialized to Output[1] Output[2] .... 
This conflicts with your request.
