### ISSUE TITLE
Model Exchange FMU Export error

### ISSUE THREAD

**Issue by AnilGurlek** [CATIA-Systems/FMIKit-Simulink#399]
Hi good day,

I am facing problem while exporting model exchange FMU code generation with rtwsfcnfmi.tlc

Following configuration was used:
Windows 10
Matlab 2022b
Cmake 3.25.2
Visual Studio 16 2019 
FMIKit-Simulink-3.0 (also tried FMIKit-Simulink-3.0-alpha.5 and same error occured)

![adsfdg](https://user-images.githubusercontent.com/100282654/217224997-3d55831f-77b5-4528-b745-1e63290558d8.png)

Diagnostic view of the error has shown below:

`### Generating code and artifacts to 'Model specific' folder structure
### Writing header file rtwtypes.h
.
### Writing source file pid_control_sf_data.c
.
### Writing header file rtGetInf.h
.
### TLC code generation complete (took 2.398s).
.
### Writing modelDescription.xml
.
### Saving binary information cache.
Using find_system without the 'Variants' argument skips inactive Variant Subsystem blocks in the search. This behavior will change in a future release to look at all choices of the Variant Subsystem. To find blocks that are active in simulation or code generation, compile the model and use the built-in variant filters with the 'MatchFilter' option. To find all blocks use filter '@Simulink.match.allVariants' with the 'MatchFilter' option.
Component:Simulink | Category:Model warning
### Generating project
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30147.0
-- The CXX compiler identification is MSVC 19.29.30147.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
FIPXT_SHARED_MODULE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Lenovo/Desktop/WORK/pid_control_sfcn_rtw_fmi
### Building FMU
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework 
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  Building Custom Rule C:/Users/Lenovo/Desktop/WORK/FMIKit-Simulink-3.0/rtwsfcnfmi/CMakeLists.txt
  ode1.c
  ode1.vcxproj -> C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\Release\ode1.lib
  Building Custom Rule C:/Users/Lenovo/Desktop/WORK/FMIKit-Simulink-3.0/rtwsfcnfmi/CMakeLists.txt
  fmi2Functions.c
C:\Users\Lenovo\Desktop\WORK\FMIKit-Simulink-3.0\rtwsfcnfmi\fmi2Functions.c(130,58): warning C4028: formal parameter 2 different from declaration [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Users\Lenovo\Desktop\WORK\FMIKit-Simulink-3.0\rtwsfcnfmi\fmi2Functions.c(273,69): warning C4028: formal parameter 2 different from declaration [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
  sfunction.c
  rt_matrx.c
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(44,18): error C2061: syntax error: identifier 'mxArray' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(44,18): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(47,16): error C2061: syntax error: identifier 'mxChar' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(47,16): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(69,15): error C2061: syntax error: identifier 'rtInf' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(69,15): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(70,15): error C2061: syntax error: identifier 'rtMinusInf' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(70,15): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(71,15): error C2061: syntax error: identifier 'rtNaN' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(71,15): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,9): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,49): error C2146: syntax error: missing ')' before identifier 'm' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,49): error C2061: syntax error: identifier 'm' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,49): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,50): error C2059: syntax error: ',' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(212,70): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(266,9): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(268,13): error C2065: 'int_T': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(268,13): error C2146: syntax error: missing ';' before identifier 'len' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(268,17): error C2065: 'len': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(268,25): error C2065: 'int_T': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(268,26): error C2146: syntax error: missing ';' before identifier 'strlen' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(270,13): error C2065: 'mxArray': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(270,17): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(270,28): error C2065: 'mxArray': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(270,29): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(272,10): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(272,16): warning C4047: '!=': 'int' differs in levels of indirection from 'void *' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(273,9): error C2065: 'real_T': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(273,12): error C2065: 'pr': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(273,9): warning C4552: '*': result of expression not used [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(276,2): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(276,2): error C2109: subscript requires array or pointer type [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(277,2): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(277,2): error C2109: subscript requires array or pointer type [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(277,2): error C2065: 'len': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(278,5): error C2065: 'pr': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(278,7): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(278,7): error C2109: subscript requires array or pointer type [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(279,12): error C2065: 'len': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(280,16): error C2065: 'pr': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(280,13): error C2100: illegal indirection [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(280,28): error C2065: 'real_T': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(280,40): error C2297: '*': illegal, right operand has type 'const unsigned char *' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(283,14): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(283,15): warning C4047: 'return': 'int *' differs in levels of indirection from 'int' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(301,9): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(304,17): error C2065: 'mxArray': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(304,21): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(304,32): error C2065: 'mxArray': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(304,33): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(305,14): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(305,20): warning C4047: '!=': 'int' differs in levels of indirection from 'void *' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(306,13): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(306,13): error C2109: subscript requires array or pointer type [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(307,13): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(307,13): error C2109: subscript requires array or pointer type [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(309,18): error C2065: 'pa': undeclared identifier [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(309,19): warning C4047: 'return': 'int *' differs in levels of indirection from 'int' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(329,9): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(329,40): error C2146: syntax error: missing ')' before identifier 'ndims' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(329,40): error C2061: syntax error: identifier 'ndims' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(329,40): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(329,45): error C2059: syntax error: ',' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(330,77): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(353,9): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(353,44): error C2143: syntax error: missing ')' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(353,44): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(353,47): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(354,1): error C2054: expected '(' to follow 'pa' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(383,14): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(383,48): error C2143: syntax error: missing ')' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(383,48): error C2143: syntax error: missing '{' before '*' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(383,51): error C2059: syntax error: ')' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(384,1): error C2054: expected '(' to follow 'pa' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(409,8): error C2061: syntax error: identifier 'rt_mxGetEps' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(409,8): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(409,24): error C2059: syntax error: '<parameter-list>' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(431,7): error C2061: syntax error: identifier 'rt_mxGetString' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(431,7): error C2059: syntax error: ';' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
C:\Program Files\MATLAB\R2022b\rtw\c\src\rt_matrx.c(431,28): error C2059: syntax error: '<cv-qualifer>' [C:\Users\Lenovo\Desktop\WORK\pid_control_sfcn_rtw_fmi\pid_control.vcxproj]
  model_interface.c
  pid_control_sf_data.c
  rtGetInf.c
  rtGetNaN.c
  sfcn_fmi.c
  Generating Code...
 Build Summary  
Top model targets built:

Model        Action  Rebuild Reason                                    
=======================================================================
pid_control  Failed  Code generation information file does not exist.  

0 of 1 models built (0 models already up to date)
Build duration: 0h 0m 22.16s
The call to rtwsfcnfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to build FMU

The build process will terminate as a result.
Caused by:
Failed to build FMU `

Thank you in advance for helping.

Kind regards,
Mehmet Anıl Gürlek

**Comment by t-sommer** [comment]
Can you share a model to reproduce the problem?

**Comment by AnilGurlek** [comment]
Yes, I can share. It is only basic control system that I am testing for part of my homework:

[pid_control.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/10697685/pid_control.zip)

**Comment by AnilGurlek** [comment]
Hi,

After controlling other Issues with same problem, I found a solution in Issue #371 via using commit cd8cc24 "Adapt rtwsfcnfmi.tlc for R2022b".

Thank you.
