### ISSUE TITLE
Add a variable step solver to RTWSFCN export

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#4]
For models with changing dynamics or stiffness, it would be great to export CS FMUs from Simulink with a variable step solver inside. As this is not possible currently for Simulink solvers, it would be good to have e.g. a CVODE solver as an alternative.

**Comment by t-sommer** [comment]
As of [FMPy 0.2.21](https://github.com/CATIA-Systems/FMPy/releases/tag/v0.2.21) you can add a Co-Simulation wrapper to FMI 2.0 Model Exchange FMUs that uses CVode as a solver.
