### ISSUE TITLE
Compilation failed for ModelRef [grtfmi]

### ISSUE THREAD

**Issue by nl78** [CATIA-Systems/FMIKit-Simulink#409]
Compilation fails when using ModelRef.

How to reproduce:
* TopLevel is a simple call to modelRef:
![image](https://user-images.githubusercontent.com/18714082/227146132-e1fc2b7d-bf79-4940-8058-15852e5103ad.png)

* ModelRef is a simple addition:
![image](https://user-images.githubusercontent.com/18714082/227146218-a143fb55-2564-41bd-8772-c40b1e723528.png)

Result :
![image](https://user-images.githubusercontent.com/18714082/227146317-4340e6e6-ff21-4117-b956-8288c0f45767.png)

It seems that 'gcs' - "get current system" gives some weird name.

Configuration: matlab 2016b, FMIkit 3.0 or lastest commit.

Attached: 2 slx to reproduce
[modelref.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/11048606/modelref.zip)

**Comment by t-sommer** [comment]
The model `plus1` is referencing a variable `Configuration` that does not exist. Can you share it?

**Comment by nl78** [comment]
Here it is.
Anyway, using a reference configuration  (or not) does not make any difference.

[configuration.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/11052773/configuration.zip)

**Comment by t-sommer** [comment]
I can reproduce the problem with R2016b. However with R2022b it works fine. Can you try a newer MATLAB version?

**Comment by nl78** [comment]
I confirm : issue is present with R2016b and not present in R2020b.
Could it be fixed on R2016b (by adding a try/catch?) ?

**Comment by t-sommer** [comment]
Can you give 0fb40d358b8550d6a419d8db61770cdd1ef600e1 a try?
