### ISSUE TITLE
Export FMUs including S-Functions with variable step size

### ISSUE THREAD

**Issue by meikehlert** [CATIA-Systems/FMIKit-Simulink#41]
We have a use case in which we build a Simulink model that includes an S-function. This S-function specifies a variable step size with which the Simulink model is simulated. The step size is read with the function mdlGetTimeOfNextVarHit. 

An FMU for ModelExchange is to be exported via the rtwsfcnfmi target. However, this export fails because no S-Functions with variable step size are supported. 

> 'sfcndemo_vsfunc/Continuous-Time Variable Step by S-function' has a variable sample time. Variable sample times are not supported by the S-Function Target.

The export for CoSimulation fails due to the VariableStep Solver. The same is true for the grtfmi target. 

In the appendix a Simulink model is attached, which shows the problem exemplarily. The model contains an S-function, which has a sine function as input and outputs it again. The sampling rate at which the S-function operates is specified at the second input. The S-function then determines the step size of the Simulink VariableStep Solver. (Note in the real application, the step size is completely defined within the S-function.)

[VarSampleTime_TimeOfNextVarHit.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3306008/VarSampleTime_TimeOfNextVarHit.zip)

Would it be conceivable for future releases that FMUs can be exported from such models that execute a possible S-function function mdlGetTimeOfNextVarHit? In this way, internal step sizes could be read and made available to the master. This could also be an interesting implementation of the clocks from FMI 3.0.

**Comment by chrbertsch** [comment]
Not being able to generate code for a Simulink model with a variable step solver is a Simulink  Coder restriction. Just set the solver to any Fixed step solver to export the ME FMU with the rtwsfcnfmi.tlc target.

**Comment by dhenriksson** [comment]
_Variable sample times_ through the S-function 'NextVarHit' interface is not supported by the S-function target. It is a built-in restriction of the target as the message says. It will not be supported for FMU export.
