### ISSUE TITLE
Can this tool export an FMU that supports restart ？

### ISSUE THREAD

**Issue by zzlonggg** [CATIA-Systems/FMIKit-Simulink#410]
I need a fmu that supports restart, can this tool export a fmu that supports resart and if so how should I do it?

![AS6SL0M2SJV_KV2}`B0_22V](https://user-images.githubusercontent.com/101376398/229876418-9f46b2ef-aa88-4c92-9f81-393f64d8ac76.png)

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by zzlonggg** [comment]
I am using FMU in conjunction with fluent to do some research in CFD.
In MATLAB/Simulink :
1. FMIKit.initialize()
2. select solver: fixed-step(0.001)
3. sysetm target file : grtfmi.tlc
4. built a FMU model 
The model is shown in Figure 1
![LS$F)~)IOJI{U6@3{%ASB_3](https://user-images.githubusercontent.com/101376398/230032835-af155a49-e7f4-4be2-8f12-650d9d30af90.png)
Figure 1

In ANSYS\Fluent:
The ANSYS\Fluent is shown in Figure 2
![N@$_%B _F}J0ABZTHO}9IY6](https://user-images.githubusercontent.com/101376398/230033436-e305881d-aaa0-4494-8d83-cd310ad5977c.png)
Figure 2
1.run the script like
```
/file/set-tui-version "21.2"
(cx-gui-do cx-activate-item "MenuBar*ReadSubMenu*xianxing")
(cx-gui-do cx-activate-item "MenuBar*ImportSubMenu*FMU ...")
(cx-gui-do cx-activate-item "Import FMU File*Table1*Frame1(FMU Input File)*PushButton2(Import)")
(cx-gui-do cx-set-file-dialog-entries "Select File" '( "Deal.fmu") "FMU Files (*.fmu )")
```
When I import the fmu model, it gives a warning that the model does not support restart
If the FMU does not support restart, when the CFD needs to be restarted after an interruption, it needs to reinitialise the solution and run the calculation from scratch.
In fact, CFD is a very time consuming task and it would be very costly to re-initialize after every interruption, so I needed FMU support for restarting

**Comment by t-sommer** [comment]
I assume "reset" refers to the FMI capability flag `canGetAndSetFMUstate` that is currently not supported.

**Comment by t-sommer** [comment]
@zzlonggg, can you give b8db9443a5bf779467cf386002e457ed480aa082 a try? It adds an experimental implementation of the get/set FMU state functions.
