### ISSUE TITLE
Is MinGW compiler supported under Windows?

### ISSUE THREAD

**Issue by PhilippZofer** [CATIA-Systems/FMIKit-Simulink#42]
Can I export a FMU from a Windows machine using MinGW as  c/c++ compiler if MATLAB excepts the compiler (>> mex -setup c)?

**Comment by t-sommer** [comment]
With the `grtfmi.tlc` target you can use any compiler supported by CMake, including MinGW.

**Comment by PhilippZofer** [comment]
Ah I see. Thanks! 
And exporting via s-function `rtwsfcnfmi.tcl`,  is this possible with MinGW on Windows?

**Comment by t-sommer** [comment]
The `rtwsfcnfmi.tcl` target currently supports only Visual Studio on Windows.
