### ISSUE TITLE
Clarification of origin of forms_rt.jar

### ISSUE THREAD

**Issue by gens-rainer** [CATIA-Systems/FMIKit-Simulink#428]
Hello Thorsten, 

during open-source-scanning inside Bosch a problem came up with the origin of the sources of forms_rt.jar. They unfortunately did not accept your statement, that it is released under Apache 2.0-license. Inside Bosch we cannot use software of Jetbrains released under their community-edition-license any more, because it mixes free licenses with proprietary ones. Could you maybe clarify, where it is from? Our problem is that we will very likely loose the permission to use the FMIKit as well.

Regards, Rainer

**Comment by t-sommer** [comment]
The `forms_rt.jar` is published [on the Maven Repository](https://mvnrepository.com/artifact/com.intellij/forms_rt/7.0.3) under the Apache License 2.

**Comment by gens-rainer** [comment]
Thanks for the answer. It was the first step to google it. I filed this issue because the released file in the Maven-Repository and the distributed file in FMIKit are not the same. So where is it from?

**Comment by t-sommer** [comment]
The `forms_rt.jar` in this repo is from the IntelliJ Community Edition 2019.2.2.

**Comment by gens-rainer** [comment]
Thank you very much. And I apologize that I needed to bother you for that. Regards, Rainer.
