### ISSUE TITLE
cmake is not executed for grtfmi.tlc target for Linux 64bit

### ISSUE THREAD

**Issue by Nomados** [CATIA-Systems/FMIKit-Simulink#435]
### Simulink cache artifacts for 'SOX_CG' were created in '/home/../temp/xxcc.slxc'.
**Build process completed successfully**

As it it can be seen, CMAKE was not executed and no FMU file was actually built!

FMIKit 3.0 and 3.1 MATLAB 2022b 
S-Function target works fine

**Comment by Nomados** [comment]
![image](https://github.com/CATIA-Systems/FMIKit-Simulink/assets/1502300/590ab3eb-f0f5-451e-b03a-040038c41be5)
For grtfmi.tlc target no FMU is created, for rtwsfcnfmi.tlc FMU is created successfully for the same CMAKE configuration

**Comment by t-sommer** [comment]
Please reopen if you it does not work with 18a7b6c64244567c5e6f412f4be2d52c7f5f53d1.
