### ISSUE TITLE
Document automatic initialization of FMI-Kit

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#44]
It would be good to add something like the following text in the documentation:

To run the FMI Kit app automatically when you start MATLAB you can add the following lines to your startup.m file (as you, @t-sommer, have provided to me. Thanks!):

```
apps = matlab.apputil.getInstalledAppInfo();

for i = 1:numel(apps)
    app = apps(i);
    if strcmp(app.name, 'FMI Kit')
        matlab.apputil.run(app.id);
        return
    end
```
end

**Comment by t-sommer** [comment]
Closing in favor of #36
