### ISSUE TITLE
Simulink export fmu version 1.0?

### ISSUE THREAD

**Issue by MelissaBa37** [CATIA-Systems/FMIKit-Simulink#442]
Hi all, 

I would like to co-simulate my E+ and Simulink models. I am wondering whether it is possible to export my Simulink model as a FMU version 1.0? 

Thank you in advance!

Kind regards,

Melissa

**Comment by t-sommer** [comment]
FMI 1.0 export is not supported.

**Comment by MelissaBa37** [comment]
Ahh I read: 

_A Simulink library to import and export [Functional Mock-up Units](https://fmi-standard.org/) that supports...

FMI 1.0, 2.0, and 3.0
Model Exchange and Co-Simulation
MATLAB R2016a - R2023a_

Does that mean that it only supports the import of FMI 1.0?
