### ISSUE TITLE
Clarify if importing Co-Simulation FMI 1.0 is supported

### ISSUE THREAD

**Issue by GarronFish** [CATIA-Systems/FMIKit-Simulink#445]
On https://github.com/CATIA-Systems/FMIKit-Simulink/blob/main/docs/fmu_import.md it says:
"For FMI 2.0 FMUs that support both model exchange and co-simulation the interface type can be selected."

Could you please clarify if FMI 1.0 FMU's are supported on model exchange and or co-simulation.

**Comment by t-sommer** [comment]
Both Co-Simulation and Model Exchange import is supported for FMI 1.0.

**Comment by GarronFish** [comment]
Thanks
