### ISSUE TITLE
FMUs cannot be reused and cannot be instantiated!

### ISSUE THREAD

**Issue by 2351498801** [CATIA-Systems/FMIKit-Simulink#462]
I would like to export the simulink model as fmu. then import it into AMESim for co-simulation. The previous was done successfully, but it turns out that I can't reuse the FMU module, and it runs with no problem on its own. I hope the authors can fix this bug soon, graduation depends on you author-sama!!!!

**Comment by t-sommer** [comment]
What do you mean by "can't reuse the FMU module"?

**Comment by t-sommer** [comment]
Please re-open if the problem persists and provide steps to reproduce it.
