### ISSUE TITLE
FMIKit compiler cannot find relative path

### ISSUE THREAD

**Issue by TerkaHi** [CATIA-Systems/FMIKit-Simulink#463]
I have troubles with generation of FMU from S-function, because in c-code the header is included with partial path #include LIB/LIB_Mat/LIB_Mat.h, but the compiler needs whole address as S:/VOB/LIB/LIB_Mat I think....this whole address is already set as path in Matlab. I also tried to write the whole address to include directories in Simulink Custom Code Settings – no improve. Please can you help me, how can I set the compiler that it knows that the LIB/LIB_Mat/LIB_Mat.h is on S:/VOB/LIB/LIB_Mat path?

**Comment by t-sommer** [comment]
Can you share an example model to reproduce the problem?

**Comment by TerkaHi** [comment]
Hello, I find the solution, the pathes of included files have to be written in CMake.txt. file.
