### ISSUE TITLE
exporting simscape fmus not working due to updated paths for simscape sources

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMIKit-Simulink#465]
hi @t-sommer  
If I change the paths like this, im able to export simscape fmus. 
I only tested it from R2022b upwards. 
https://github.com/jbernalr/FMIKit-Simulink/blob/main/grtfmi/CMakeLists.txt

Thanks!

**Comment by t-sommer** [comment]
Fixed with b37905bee8a4e1703fed6ecbb4768071e13c781c.
