### ISSUE TITLE
grtfmi build fails for models with many s function source files

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#47]
Error message:

### Running CMake generator
The command line is too long.

See line 67 in grtfmi_make_rtw_hook

**Comment by t-sommer** [comment]
@fajansen, can you give 39014dabe476afb791697d0e0d74266822b1a60d a try?

**Comment by fajansen** [comment]
Works!

**Comment by t-sommer** [comment]
@fajansen, can you please try again with 9c73afe1d24a0555a81e0e08e955bc5d4a232ef9?

**Comment by fajansen** [comment]
I get an error message about a missing parameter. The same model works with the previous version.

Message:
fmiwrapper.inc(337973): error C2039: 'PARAMNAME': is not a member of 'P_MODELNAME_T_' 
...
The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to build FMU

Grepping for the (redacted) parametername gives me three hits.
1st in fmiwrapper.inc:
return &(rtmGetDefaultParam(S)->PARAMNAME);
2nd in modelDescription.xml:
<ScalarVariable name="PARAMNAME" valueReference="112651" causality="parameter" variability="tunable">
3rd in MODELNAME.rtw
  Identifier	      "PARAMNAME"
 Name			  "PARAMNAME"

**Comment by t-sommer** [comment]
Please open a new issue if the problem still exists with the current develop version.
