### ISSUE TITLE
How to set the output to discrete

### ISSUE THREAD

**Issue by DYS811** [CATIA-Systems/FMIKit-Simulink#471]
hello，I successfully made a FMU files by FMIKit through the user manual, however, when I import the FMU to DigSILENT, it come error that the 'Variability' of output is continous, DigSILENT only support discrete 'Variability'.

I have already set simulink mode as a discrete solver, also I try to set a discrete sampling of the simulink model output. All these method is not useful. HOW CAN I DO TO SOLVE THIS ?
![Uploading Error.png…]()

**Comment by yinyue01** [comment]
The result of my attempt is that FMIKit exported fmu is available on PF 2022. 
For higher versions of PF, only fmu exported from Matlab can be used.
