### ISSUE TITLE
Document CMake installation

### ISSUE THREAD

**Issue by GallLeo** [CATIA-Systems/FMIKit-Simulink#49]
On PCs without admin rights, one might not be able to install CMake.

Please document, that one can download the ZIP file instead of installer:
https://cmake.org/download
e.g. use e.g. cmake-3.14.5-win64-x64.zip

Which version is required?

**Comment by beutlich** [comment]
> Which version is required?

https://github.com/CATIA-Systems/FMIKit-Simulink/blob/e76f356eba554c2d17b21aae24e75a69a39dfcf2/CMakeLists.txt#L1
