### ISSUE TITLE
feature/grt-build-variables: Inports appear multiple times

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#51]
In the feature/grt-build-variables all inports appear several times in the FMU.

`    
    <ScalarVariable name="In1" valueReference="3" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[1]" valueReference="4" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[2]" valueReference="5" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[3]" valueReference="6" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In1" valueReference="7" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[1]" valueReference="8" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[2]" valueReference="9" causality="input">
      <Real start="0"/>
    </ScalarVariable>
    <ScalarVariable name="In2[3]" valueReference="10" causality="input">
      <Real start="0"/>
    </ScalarVariable>`

**Comment by t-sommer** [comment]
@fajansen, can you share the model that causes the problem?

**Comment by t-sommer** [comment]
With 7691f0c76922fd9e00fdd2693792d760b484d11f I get the expected result.
