### ISSUE TITLE
grtfmi: Provide option for binary only FMU

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#52]
To avoid having to modify the FMU later if the goal is to have a binary only FMU, please provide an option to exclude the source code (and the corresponding entries in the modelDescription.xml) from the resulting FMU.

**Comment by t-sommer** [comment]
Have you tried to uncheck "Include sources in FMU"?

**Comment by fajansen** [comment]
My bad m(
