### ISSUE TITLE
Use Simulink Block parameters for FMI attributes

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#55]
The following variable attributes of in- and outports are also available in Simulink. It would be helpful to use the simulink properties to specify the values in modelDescription.xml:

FMU attribute | Simulink Inport Block property
-------------- | -------------
description | Description
unit | Unit
min | Outmin
max | Outmax

**Comment by t-sommer** [comment]
Solved with 665f539f388b212246f43da630ebbac0bfe5ce04
