### ISSUE TITLE
Support of SimScape blocks

### ISSUE THREAD

**Issue by FranciscoCollado** [CATIA-Systems/FMIKit-Simulink#56]
Would be possible to support SimScape blocks for exporting a FMU?
At the moment with both tlc targets you get an error that SimScape is not supported.

**Comment by t-sommer** [comment]
The export of SimScape models with grtfmi.tlc should be possible with two limitations:

1. only one FMU instance per process (since "Reusable function" is not supported for SimScape) 
2. no source code FMUs (model must be linked against libraries from the MATLAB installation)

**Comment by FranciscoCollado** [comment]
I tried to generate an FMU with grtfmi but I get this error:

**The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    Failed to run CMake generator
The build process will terminate as a result.
Caused by:
Failed to run CMake generator**

Not sure if I have my configuration right. 
Could you please share what kind of configuration on the "model configuration parameters" you have so I can replicate them?

**Comment by t-sommer** [comment]
It's currently not possible. I just made a prototype to try it out. Sorry for the confusion.

**Comment by FranciscoCollado** [comment]
Is there any possible workaround?
Even if we have to recompile libraries or do any sort of process manually.

**Comment by t-sommer** [comment]
If you're on Windows you can export the model with `grt.tlc` as a Visual Studio project and add all the include directories and libraries from the VS project to `grtfmi/CMakeLists.txt`. I have to investigate if this is sufficient for all SimScape models.

**Comment by chrbertsch** [comment]
> At the moment with both tlc targets you get an error that SimScape is not supported.

With rtwsfncfmi.tlc export of Simscape models works.

**Comment by FranciscoCollado** [comment]
How did you make it work?
 If I try to generate the fmu with rtwsfncfmi.tlc, it stops and shows a message saying that simscape is not supported.

**Comment by t-sommer** [comment]
The `grtfmi.tlc` target on `develop` has now experimental Simscape support. Please open a new issue if you find any problems.
