### ISSUE TITLE
modelDescription.xml lists source files not existing and needed within the FMU

### ISSUE THREAD

**Issue by MichaelKuebler** [CATIA-Systems/FMIKit-Simulink#60]
The generated modelDescription.xml lists some source files which are not required for successful (re-)compilation - and not copied to the FMU or even not existing.
The list seems to be hard-coded within the TLC files:
      File name="rt_logging.c"
      File name="rt_logging_mmi.c"
      File name="rt_nonfinite.c"
      File name="rtGetInf.c"
      File name="rtGetNaN.c"
      File name="rtw_modelmap_utils.c"
Some of these source files will only be created when "MAT-file logging" is activated, which can not be selected - due to the settings in grtfmi_selectcallback.m.
Workaround currently is to manually edit the modelDescription.xml, but a more convenient approach would be appreciated.

**Comment by t-sommer** [comment]
Solved with 7093c81ec6dcdf51aba20ecd33f6492a1ef54da4
