### ISSUE TITLE
Generate FMU only having mex64 file for a S-Function and using grtfmi target.

### ISSUE THREAD

**Issue by FranciscoCollado** [CATIA-Systems/FMIKit-Simulink#64]
Request: To be able to generate the FMU with a S-function that you only have the mex64 file, and using grtfmi as target.

**Comment by t-sommer** [comment]
This is a limitation of the GRT target grtfmi.tlc is based on. To export a model that contains S-functions you have two options:

1. Provide the sources of the S-function by putting a `<name_of_s_function>.[c|cpp]` file on the MATLAB path. If you want to protect the IP of the S-function the source may be scrambled. This approach will allow you to export source code FMUs.

2. Create a wrapper (source code) S-function that forwards the function calls to a static or dynamic library that contains the actual code. This approach will not allow you to export source code FMUs.
