### ISSUE TITLE
Support for "For Each" subsystem blocks?

### ISSUE THREAD

**Issue by GallLeo** [CATIA-Systems/FMIKit-Simulink#65]
When exporting FMUs from Simulink we get the following error message:

> 
> Model 'sldemo_foreach_vectorized' cannot generate code for the S-function target because the model has one or more subsystems which contain a For
> Each block

You can reproduce this error with the following standard Simulink example: 'sldemo_foreach_vectorized’

Is there the possibilty to support this block in FMIKit?

**Comment by t-sommer** [comment]
I can successfully export the model with grtfmi.tlc on R2019a. Can you provide steps to reproduce the problem?

**Comment by t-sommer** [comment]
The rtwsfcnfmi.tlc target does not support "For Each" blocks. This is a limitation of the rtwsfcn.tlc it's based on.
