### ISSUE TITLE
Can I use grtfmi.tlc without running the MATLAB installer?

### ISSUE THREAD

**Issue by meek1** [CATIA-Systems/FMIKit-Simulink#66]
Can I use grtfmi.tlc without running the MATLAB installer, and what is the minimum set of files I need to use grtfmi.tlc for FMU-CS generation of Simulink models?

**Comment by t-sommer** [comment]
To use the `grtfmi.tlc` target it is sufficient to clone or download the repository and put the `grtfmi` folder on the MATLAB path (no binaries or initialization required).
