### ISSUE TITLE
How to export an FMU with ARM binaries?

### ISSUE THREAD

**Issue by Camork** [CATIA-Systems/FMIKit-Simulink#67]
Does it possible to config FMIKit to make it export ARM lib?

**Comment by t-sommer** [comment]
You cannot directly export an FMU with ARM binaries on a PC. However you can export a source code FMU and compile it on the target machine. See https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi for an example.

**Comment by Camork** [comment]
Hey @t-sommer , I can successfully export source code use grtfmi target file, but the source files exported not contains some C source files (like 'rt_logging.c' 'rt_logging_mmi.c') which are specified in generated modelDescription.xml, and my Matlab version is 'R2018b'.
