### ISSUE TITLE
communicationStepSize effects FMU results

### ISSUE THREAD

**Issue by PhilippZofer** [CATIA-Systems/FMIKit-Simulink#68]
The results of a FMU are effected by the communictionStepSize. 

FMU Export 
-------------------------------------------------------------
The model and the FMU are attached [here](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3583485/communicationStepSize.zip).

**Modeling TooL -> MATLAB/Simulink R2018b**

Model
*  3 Sine Wave Blocks
*  every Block has one scalar output port
*  Amplitude: 1
 *  Frequency: 1, 5, 15 Hz
    
**Export Tool  -> FMI-Kit 2.6.0**

Settings
*  Solver Type: Fixed-step
*  Code Geneneration -> System target file: grtfmi.tlc
*  Code Generation/FMI -> CMake generator: MinGW Makefiles

Steps to reproduce
--------

1. Import the attached [FMU](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3583485/communicationStepSize.zip) to Dymola or FMPy
2. Simulate
3. see Results:
    `scalarSineWave_fmu1.Out1 `-> should have 1 Hz
   ` scalarSineWave_fmu1.Out2` -> should have 5 Hz
    `scalarSineWave_fmu1.Out2` -> should have 15 Hz
4. change communictionStepSize: FMU block -> FMI -> `fmi_CommunicationStepSize = 0.001`
5. now the output signals behave like expected

Expected Result
-----------------------
The results of the FMU should not depend on the `communictionStepSize`. A User expects a FMU to have always the same output behaviour.

**Comment by t-sommer** [comment]
@PhilippZofer, can you please give 79e2f2100b0dcb10c9b207d4b75f62ceb293fcad a try?

**Comment by t-sommer** [comment]
To work around the problem you can add a dummy state to the model, so it's not discrete.

**Comment by matthiasliermann** [comment]
Thank you, the workaround works: simply include a continuous element into the otherwise discrete system. What is the underlying issue here? Can it be fixed in the FMIKit, or is it intended that for discrete systems the input/output behavior changes with the FMU communication step size?

**Comment by t-sommer** [comment]
This seems to be a result of auto-selected fixed step discrete solver. By adding a continuous state you're forcing Simulink to use a different solver.
