### ISSUE TITLE
Export 32/64-Bit FMUs

### ISSUE THREAD

**Issue by thegermantank** [CATIA-Systems/FMIKit-Simulink#70]
I am using Matlab R2018a 64 Bits and i am successfully exporting 64BitFMUs. I would also like to export 32 Bit FMUs. Is this possible? The only possible configuration parameters i found are `model configuration / optimization > memcpy threshold and maximum stack size` (Default 64). Yet entering 32 has no impact on the generated binary bit type of the fmu.
Can you help me out? Thanks!

**Comment by t-sommer** [comment]
You should be able to export a 32-bit FMU with `grtfmi.tlc` by selecting a 32-bit CMake Generator (w/o the "Win64" suffix).
