### ISSUE TITLE
Export FMUs from Simulink models that contain imported FMUs

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#71]
For some use cases it would be beneficial to create FMUs from Simulink models that already contain imported FMUs. This would create "Matryoshka" FMUs (but part of the "outer" FMU could be also created from the Simulink model that contains the inner FMUs.

**Comment by t-sommer** [comment]
Can you give 1dde743781998dfe591412b148fcb7bc5b95242f a try?

**Comment by Spiegel-Leser** [comment]
We also need that, did it work out?

**Comment by t-sommer** [comment]
This should work for `grtfmi.tlc`

**Comment by chrbertsch** [comment]
I tried it with the 3-FMU model that I provided to you (putting the Control and Drive FMU as CS FMUs in one FMU with a stepsize of 0.001s): 
First I could generate an FMU containing both FMUs in the resources folder, but when combining it with the Stimuli FMU, I did not get meaningful simulation results ...
![grafik](https://user-images.githubusercontent.com/16363372/71926180-07db7d80-3193-11ea-8f84-04ce8e736eef.png)



When I tried to generate  FMU again, I got the following error: 
```
...
### Copy nested FMUs
Copying C:\home\fmi-tutorial\ModelicaFMIExample\FMUs\MODELICA_0Demo_Control to resources
Copying C:\home\fmi-tutorial\ModelicaFMIExample\FMUs\MODELICA_0Demo_Drive to resources
### Running CMake generator
The call to grtfmi_make_rtw_hook, during the after_make hook generated the following error:
    block_diagram does not have a parameter named 'CMakeCompilerOptimizationLevel'

The build process will terminate as a result.
Caused by:
block_diagram does not have a parameter named 'CMakeCompilerOptimizationLevel'
```
