### ISSUE TITLE
Support struct in model parameters 

### ISSUE THREAD

**Issue by kojojo1** [CATIA-Systems/FMIKit-Simulink#74]
When a model block  is initialized by structure not by the simple variable nor hard-coded constant the parameter is not in modelDescription.xml after the compilation.
By the model block I mean an **Integrator** for example and by initialization settings the **Initial condition** of the **Integrator** .

Jan

**Comment by t-sommer** [comment]
@kojojo1, can you  share a model or one of Simulink's built-in examples that reproduces the problem?

**Comment by kojojo1** [comment]
Hi,
here is the example :
[parametrIssue.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3635534/parametrIssue.zip)
In the zip file there are two models one with struct parameters (parametrIssue.slx) and second one with 'hard-coded' parameters (parametrNoIssue.slx). Look on the different in modelDescription.xml s

**Comment by t-sommer** [comment]
@kojojo1, is the workaround in #151 acceptable for you?

**Comment by chrbertsch** [comment]
> ... is the workaround in #151 acceptable ... ?
The workaround works fine, but still is a trap for users who are not aware of it. Would be nice to support struct variables pararamters for variables w/o the workaround
