### ISSUE TITLE
Shared Library problem

### ISSUE THREAD

**Issue by joaha058** [CATIA-Systems/FMIKit-Simulink#75]
Hi!

When I tried to make an FMU of one of our biggest models, The FMU generation went well.  But when I am trying to import the generated FMU and run it in Matlab 2016b (Linux environment) I got the following error "Error while executing C MEX S-function sfun_fmurun at time 0. Caused By: Unexpected standard exception from Mex file. What() is: Could not load shared library"

Anyone that can help me what is wrong? (any hint on how to debug the the error)  
Are there any documentation on how I can mex sfun_fmurun? (If there are some settings in our environment that differ from the one used when the sfun_fmurun.c was compiled)

Regards
Joakim

**Comment by t-sommer** [comment]
Which target did you use to export the FMU?

**Comment by t-sommer** [comment]
And on which platform did you export the FMU?

**Comment by joaha058** [comment]
I used grtfmi to export the FMU. 
Matlab 2016b
Linux environment, Centos 7.4. 
gcc 4.9.3 was used.

**Comment by t-sommer** [comment]
Have you tried to export the model on Mac or Windows?

**Comment by joaha058** [comment]
No.  Can see if I can get the export to work on windows to see if the problem still occur.

**Comment by joaha058** [comment]
I solved the problem. Depending of the settings in the configuration settings, a file <model>_data.c will be generated including necessary initialization of parameters for the model. 

I updated the file fmigrt_make_rtw_hook locally on row 46 (custom_source{end+1}= ....
and added that also the file <model>_data.c was included in the compilation if it exist.

**Comment by meek1** [comment]
@t-sommer should this be labeled as bug with solution based on above?
