### ISSUE TITLE
Create Blackbox FMU with GRT target

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#76]
The S-Function target has a black box mode, which hides all information about the contents of the FMU except the interfaces. Please provide a similar option for GRT target.
When this option is enabled, the resulting FMU description should contain only inports, outports and the parameters selected in the "Visible Parameters" field, nothing else.

**Comment by t-sommer** [comment]
You should be able to achieve the same result by inlining all parameters you want to hide.

**Comment by fajansen** [comment]
Sorry, I should check more thoroughly what I'm writing.

**Comment by t-sommer** [comment]
No worries 😉
