### ISSUE TITLE
Create Whitebox FMU with GRT target

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#77]
With S-Function FMI target it is possible to create a "Whitebox" FMU, meaning that all the block outputs are visible in the resulting FMU. This is very handy for debugging, as you can trace where a specific problem comes from.
Please provide a similar option to the GRT target.

**Comment by meek1** [comment]
Have not realized the black-box limitation for GRT. Does the Visible parameters option enable something inbetween black and white box, ie access all internal parameters but not internal signals?

**Comment by t-sommer** [comment]
> Does the Visible parameters option enable something inbetween black and white box, ie access all internal parameters but not internal signals?

No. It only filters out existing variables.

**Comment by t-sommer** [comment]
Block outputs can now be exported with `grtfmi.tlc` in 2.7 (alpha).
