### ISSUE TITLE
Modify GUID

### ISSUE THREAD

**Issue by cjay123321** [CATIA-Systems/FMIKit-Simulink#80]
Hi,

Is there any possibilities to modify/predefine the GUID when exporting simulink model to FMU. Currently all models are predefined to be 0.

**Comment by t-sommer** [comment]
The GUID is automatically generated during export. Can you describe a use case where you need to define it manually?

**Comment by cjay123321** [comment]
So the use case is to run multiple FMUs generated from the FMIKit on a application, but currently it is not expanded to run two or more FMUs with the exact same GUID (currently all are set to 0). Manually changing the GUID to a different value than 0 in the XML file does not seem to help (maybe the GUID information is wrapped somewhere else as well).

**Comment by t-sommer** [comment]
Every exported FMU gets a GUID of the form `{3eb9dd1e-82ed-4475-978f-7a1e812d6caa}`. Can you provide steps to reproduce the problem?

**Comment by cjay123321** [comment]
<img width="548" alt="FMI" src="https://user-images.githubusercontent.com/56473750/66749892-51197b00-ee8b-11e9-8f92-a1b53a765db2.png">
A simple simulink model is created and exported following the steps provided in the repo. Then the .fmu file is converted to .zip such that files within can be investigated. The image above shows the headline of the XML-file where the guid = 0.

**Comment by hplatou** [comment]
I have seen exactly the same problem. I have filed PR#88 that should fix the problem. In the mean time you can try to manually download the `grtfmi/grtfmi_generate_guid.m` from the repository, and add it to you `matlabpath` before building your model.

**Comment by t-sommer** [comment]
This problem should be resolved with the ZIP archive installation (see #86).
