### ISSUE TITLE
Unable to locate template makefile: rtwsfcnfmi_18b_unix.tmf

### ISSUE THREAD

**Issue by pvangils** [CATIA-Systems/FMIKit-Simulink#82]
When trying to build a Simulink model using rtwsfcnfmi.tlc system target file and FMI Kit 2.6 on a CentOS 6.10 Linux 64 Virtual Machine and Matlab 2018b, I get the following error:

> Unable to locate template makefile: rtwsfcnfmi_18b_unix.tmf

**Comment by pvangils** [comment]
Note that after copying rtwsfcnfmi_unix.tmf and renaming it to rtwsfcnfmi_18b_unix.tmf the code generation seems to work, however I do get the warnings:

> •	The make variables |>USERMODULES<| are used in the template makefile, but they are not defined. You may have a mismatch between the system target file and the template makefile.
> •	./sfcn_fmi.h:34:1: warning: "mxGetData" redefined [2 similar] 

And finally the error:
> •	Assertion failed.

The good thing however is that a folder FMUArchive is created that includes the modelDescription, binaries and resources files. From this I can then create a .zip package and rename it to .fmu. Importing this FMU using Simulink’s native FMU import functionality seems to work fine.

**Comment by t-sommer** [comment]
The build for `rtwsfcnfmi.tlc` uses CMake now. Please try again with the latest version of `develop` and open an new issue, if it does not work.
