### ISSUE TITLE
FMU cross-compilation (lin64->lin32): No rule to make target `32', needed by `fmi2Functions.o'.

### ISSUE THREAD

**Issue by pvangils** [CATIA-Systems/FMIKit-Simulink#83]
Setup:
* rtwsfcnfmi.tlc system target file 
* FMI Kit 2.6 
* CentOS 6.10 Linux 64 Virtual Machine 
* Matlab 2018b

After performing the change as described in: https://github.com/CATIA-Systems/FMIKit-Simulink/issues/82#issuecomment-541596888_ and changing the following lines:

```
ifeq ($(MEXEXT),mexa64)
FMI_ARCH_OPT = -m64
FMI_DIR = linux64
else
FMI_ARCH_OPT = -m32
FMI_DIR = linux32
endif

```
to:

```
ifeq ($(MEXEXT),mexa64)
FMI_ARCH_OPT = -m32
FMI_DIR = linux32
else
FMI_ARCH_OPT = -m32
FMI_DIR = linux32
endif
```

I get the following error during the build process:

> •	gmake: *** No rule to make target `32', needed by `fmi2Functions.o'.  Stop.

**Comment by t-sommer** [comment]
As a workaround you could export a source code FMU with grtfmi.tlc and compile the platform binary on the target platform.

**Comment by dhenriksson** [comment]
I would classify this as a permanent restriction for the S-function target as cross-compilation is not supported. Compiling from a 64-bit MATLAB installation can only generate 64-bit binaries and vice versa.
