### ISSUE TITLE
Make FMU parameters tunable when importing

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#85]
With the FMIKit FMU importer, parameters of the FMU can only be changed at the beginning of the simulation. With the Mathworks FMU importer (tested with 2019b), the FMU parameters are tunable and can be changed during runtime.

**Comment by fajansen** [comment]
Any news on this topic? We really need this.

**Comment by fajansen** [comment]
Any update?

**Comment by t-sommer** [comment]
I've created a prototype (443d57fa7e4bb3bf9a7145c77180dc9197cd62fa) based on `fmikit_demo_BouncingBall` that makes parameter `e` a tunable dialog parameter.

Pros:
- allows changing the parameters at runtime

Cons:
- would replace workspace variables as start values for tunable parameters

**Comment by t-sommer** [comment]
Another (and probably more robust) approach would be to simply add the tunable parameters as discrete inputs, leveraging the existing infrastructure.

**Comment by fajansen** [comment]
Would you expose all tunable parameters as discrete inputs or just a few selected by the user? The downside of this approach is that you have to create lots of "constant" blocks and connect them to the right inputs. This might also have a performance impact. Parameters are only written when changed, inputs every timestep.

**Comment by t-sommer** [comment]
> Would you expose all tunable parameters as discrete inputs or just a few selected by the user?

No. These inputs would have to be added individually, like the output ports.

> The downside of this approach is that you have to create lots of "constant" blocks and connect them to the right inputs. This might also have a performance impact.

We could keep track of the previous value and only set it, when it has changed.

**Comment by fajansen** [comment]
This would work nicely for my use case.
If it's only for a handful of variables, the performance impact should also be negligible, keeping track of the previous value is just an additional error source.

**Comment by sloghavi68** [comment]
@t-sommer I want to test the new tunable parameters with the 3.0 alpha. What do I need to do to make a parameter tunable? Do I have to select it as an input? I noticed that not all parameters have the input option available. Would you mind commenting on what is required for a parameter for it to be available to be defined as a tunable parameter?

**Comment by t-sommer** [comment]
> I noticed that not all parameters have the input option available.

Only _tunable_ parameters can be exposed as block inputs.
