### ISSUE TITLE
Provide .zip file of FMIKit, not only installer

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#86]
For automated use of different FMIKit versions on the same machine, it is helpful to get FMIKit as a zip file that can be added to the path instead of having to use an installer.

**Comment by t-sommer** [comment]
We've set up CI with Azure Pipelines. You can now download the distribution archive for every build:

- go to https://dev.azure.com/CATIA-Systems/FMIKit-Simulink/_build
- select a build
- click `Artifacts` and select `dist`
- select `dist > FMIKit-Simulink.zip`
- click `...` and select `Download`

@fajansen, please let us know if this works for you.

**Comment by chrbertsch** [comment]
> We've set up CI with Azure Pipelines. You can now download the distribution archive for every build

If one uses the zip-file, how do you initialize FMI-Kit in Simulink?
And do you have to add some folders to the MATLAB path?

**Comment by t-sommer** [comment]
Just like before the App Installer: add the extracted folder (that contains the `+FMIKit` folder) to the MATLAB path and run `FMIKit.initialize()`.

**Comment by rrahman2020** [comment]
As a continuing discussion I am using FMI Kit 2.8.0. Can you please elaborate on building fmikit.jar? I installed Intellij. Not familiar with Java build. So I'd appreciate if you could help with this.

**Comment by t-sommer** [comment]
Take a look at https://github.com/CATIA-Systems/FMIKit-Simulink/blob/master/docs/build.md#build-fmikitjar

**Comment by rrahman2020** [comment]
Thanks!

I did install IntelliJ and tried to follow the Java building instructions given at the link. Do I need to give the path to Java src here? I built and it gave some fmikit.jar file. However, seems like that file is empty. What am I missing?
