### ISSUE TITLE
Wrong ShLwApi.Lib path

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#87]
The nested-FMU feature branch detects an invalid path for ShLwApi.Lib

**Comment by t-sommer** [comment]
If `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\CurrentInstallFolder` does not point to a valid Windows SDK there seems to be something wrong with your installation.

To work around the problem you can fix the path manually in `CustomLibrary`.

**Comment by fajansen** [comment]
By changing this nested FMUs do work for me.
