### ISSUE TITLE
Set fmuResourceLocation as environment variable for exported FMUs

### ISSUE THREAD

**Issue by eidekrist** [CATIA-Systems/FMIKit-Simulink#89]
I have a Simulink model using an S-function to read resource files. After generating an FMU from this model I put the these resource files in the `resources` directory inside the FMU so they follow the FMU.

In order to make the generated FMU portable, I also need tell the S-function where to look for these resource files, which depends on where the FMU is unzipped. This can be solved by storing `fmuResourceLocation` as an environment variable during the call to `fmi2Instantiate()`. During the subsequent call to `mdlStart()` the S-function can read this environment variable and locate the needed files.

**Comment by t-sommer** [comment]
You can use the static variable [FMU_RESOURCES_DIR](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/develop/grtfmi/fmi2Functions.c#L15). See [sfun_fmurun.cpp](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/develop/sfun_fmurun.cpp#L913) for an example.

**Comment by eidekrist** [comment]
Oh, that is much nicer. Tested with success, thanks!
