### ISSUE TITLE
Problem with simulating an FMU containing an FMU

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMIKit-Simulink#9]
The attached FMU (remove ending .zip) was create by importing a simple ME 2.0 FMU (Simulink model: input is integrated) generate from Simulink with FMI-Kit 2.4.2 to SimulationX 4.0 and re-exported as a CS-FMU. [integrator_cs.fmu.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/2965855/integrator_cs.fmu.zip)
I can be run by the FMU Compliance Checker and fmpy, but not with FMI-Kit 2.4.2 within ML/SL 2.4.2; the following error is produced: 
```
ERROR: Error: Simulation stopped!
The FMU "C:/home/fmi_test_ME_CS/integrator_cs/integrator_sf.fmu" could not be found.
CVODE Error: Initialization of model failed.
Error during initialization of FMU.
Failed to enter initialization mode
Failed to enter initialization mode. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).
Error in 'asdfuntitled/FMU' while executing C MEX S-function 'sfun_fmurun', (mdlStart), at time 0.0.
Caused by:
Unexpected Standard exception from MEX file.
What() is:Failed to enter initialization mode. The FMU crashed (exception code: UNKOWN_EXEPTION_CODE).
```

**Comment by t-sommer** [comment]
This problem related to a broken path to the resources directory in the FMI 2.0 import. It's already fixed in the current `develop` branch.
