### ISSUE TITLE
FMU Export: Create Custom FMU Log Messages

### ISSUE THREAD

**Issue by Batemo-Karlsruhe** [CATIA-Systems/FMIKit-Simulink#92]
When a FMU is created from a Simulink model, it seems to be impossible to write custom messages to the [FMU log](https://fmi-standard.org/docs/3.0-dev/#definition-of-log-categories). However, this feature would be very helpful to output and display model diagnostic messages to the end-user.
Is it possible to integrate the string of an "[disp](https://de.mathworks.com/help/matlab/ref/disp.html)" or "[error](https://de.mathworks.com/help/matlab/ref/error.html)" command to the FMU log? Or alternatively to use [assertion blocks](https://de.mathworks.com/help/simulink/slref/assertion.html) in a way to create FMU log messages?

**Comment by t-sommer** [comment]
@Batemo-Karlsruhe, can you share an example model that uses the above commands to print messages?

**Comment by Batemo-Karlsruhe** [comment]
Yes, sure. Attached you find an R2016b example model in a ZIP file that creates info, warning and error messages. All messages are displayed in the [Simulink Diagnostic Viewer](https://de.mathworks.com/help/simulink/ug/diagnose-simulation-errors.html).

Download Link to the ZIP-file: [sample_model_print_messages.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3814440/sample_model_print_messages.zip)

Thanks for considering this as an enhancement. I really think that this would help a lot!

**Comment by t-sommer** [comment]
We could expose the FMI callback [fmi2CallbackLogger](https://github.com/modelica/fmi-standard/blob/support/v2.0.x/headers/fmi2FunctionTypes.h#L131) (like the [fmuResourceLocation](https://github.com/CATIA-Systems/FMIKit-Simulink/blob/develop/grtfmi/fmi2Functions.c#L15)), so you can call it from your custom S-function. Would this solve your problem?

**Comment by t-sommer** [comment]
@Batemo-Karlsruhe, would it be sufficient to implement `rtPrintfNoOp()`, so you can use `ssPrintf()`?

**Comment by Batemo-Karlsruhe** [comment]
To be honest: I do not know... I neither have experience with the [fmi2CallbackLogger](https://github.com/modelica/fmi-standard/blob/support/v2.0.x/headers/fmi2FunctionTypes.h#L131) callback nor with the [ssPrintf()](https://de.mathworks.com/help/simulink/sfg/ssprintf.html) function. 

From the perspective of the end user it would be best if the FMU produces info, warning and error log messages that I as the creator of the FMU can control. This means to be able to customize both the conditions when log messages are created as well as the log message type and content. Taking this consideration into account, it seems that the fmi2CallbackLogger is the better way to go.
Can you share a sample model how the call to the fmi2CallbackLogger callback must be included in a Simulink model from which the FMU is created?

**Comment by t-sommer** [comment]
> Can you share a sample model how the call to the fmi2CallbackLogger callback must be included in a Simulink model from which the FMU is created?

You would have to write a simple S-function (with a similar functionality as the assertion block) that gets compiled into the FMU and calls the logger function.

**Comment by Batemo-Karlsruhe** [comment]
Alright, I would try to directly insert the [fmi2CallbackLogger](https://github.com/modelica/fmi-standard/blob/support/v2.0.x/headers/fmi2FunctionTypes.h#L131) callback to the Simulink model that the FMU is created for using the [coder.ceval](https://de.mathworks.com/help/simulink/slref/coder.ceval.html) command: **coder.ceval('fmi2CallbackLogger', [input arguments] )**

- Do you think that approach works?
- Please let me know when the enhancement is implemented. I then develop a simple example model and upload it here so that the community has a best-practice example available.

**Comment by t-sommer** [comment]
Can you give 004166a34cd90717aa7e5bd62296c5687e01d6e9 a try?

I've tested it with the S-function builder with this external function definition

```C
#ifdef RT
extern int rtPrintfNoOp(const char *fmt, ...);
#endif
```
 and this code in "Outputs"

```C
#ifdef RT
rtPrintfNoOp("u0[0] = %g\n", u0[0]);
#endif

y0[0] = -u0[0];
```

**Comment by Batemo-Karlsruhe** [comment]
Thanks for the fast implementation. In my tests, I could not get the log messages to show up unfortuntately. I am probably missing someting... So here is what I did ([FMU_log_sample_model.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3900793/FMU_log_sample_model.zip)): 

- **FMU_log_sample_model.slx**: I created a simple model that includes the S-function Builder and calls `rtPrintfNoOp`. The model should output the message to the FMU log in every simulation step. I then used the "FMIKit-Simulink-feature-rtPrintfNoOp" version (004166a) to built the FMU.
- **FMU_log_sample_model_sf.fmu**: That is the FMU that I created.
- **FMU_log_testbench.slx**: I tested with the FMI Kit 2.4 in R2016b and with the FMU Import of R2017b. In both cases I could not find the `rtPrintfNoOp` message in the FMU log.

Any idea what I do wrong here?

**Comment by t-sommer** [comment]
> Any idea what I do wrong here?

The suffix `_sf.fmu` indicates that you exported the FMU with `rtwsfcnfmi.tlc`. You should have used `grtfmi.tlc`.

**Comment by Batemo-Karlsruhe** [comment]
Using `grtfmu.tlc` together with 004166a did the trick! I tested the so created FMU in R2016b with the FMI Kit and in R2017b with the built-in FMU import. In both tests the custom FMU log message is displayed.

As a starting point for others who want to implement custom log messages into their FMUs, I attached an example that worked for me. The example files are packaged together and can be downloaded here: [sample_model_print_messages.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3912133/sample_model_print_messages.zip).
- **FMU_log_sample_model.slx**: The model writes a message to the Simulink diagnostics viewer (which is omitted when the FMU is created) and to the FMU log using the S-function Builder.
- **FMU_log_sample_model.fmu**: That is the FMU created from FMU_log_sample_model.slx using 004166a that shows the log message in my tests.
- **testbench.slx**: This is a R2016b Simulink model that uses the FMI import of the FMI Kit that you can use as testbench. FMU log messages are displayed in the Simulink Diagnostics Viewer.

Special thanks to @t-sommer for the the fast implementation and the support. We really appreciate that you push the FMI standard forward with your tool!

**Comment by r-hans** [comment]
Hey @t-sommer,
is there a reason why this feature never entered any release? It would be great having that.

**Comment by t-sommer** [comment]
Have you tried the above examples?

**Comment by r-hans** [comment]
Yes, and it works fine. But we are looking to have it in a release. As model provider, we would like to make use of that feature but every user would have to patch their FMIKit installation to enable log messages

**Comment by t-sommer** [comment]
This feature has already been merged into develop and will go into the next release.

**Comment by r-hans** [comment]
👍  That's great. Thanks for the fast response.
