### ISSUE TITLE
Simulink output vector gets mixed up in Dymola (was #69)

### ISSUE THREAD

**Issue by hv3ds** [CATIA-Systems/FMIKit-Simulink#93]
The problem is in "sources/fmiwrapper.inc": the FMU exports a set of arrays but getScalarVariable always return a pointer to the first element. This has the effect of rewriting every value to the first entry and as could be expected, Out1[1] takes the shape of Out1[5].

The error made by Dymola is using fmiSetReal - remove the call from "initial algorithm" modelica source and the FMU works as expected.

void *getScalarVariable(RT_MDL_TYPE *S, int vr, BuiltInDTypeId *dtypeID) {
  switch(vr) {
    case 1:
      *dtypeID = 0;
      return &(rtmGetDefaultParam(S)->SineWave_Amp);
    case 2:
      *dtypeID = 0;
      return &(rtmGetDefaultParam(S)->SineWave_Amp);

// … and so on ...

**Comment by t-sommer** [comment]
@hv3ds, can you reproduce the problem with the latest version of `develop`?

**Comment by t-sommer** [comment]
This should be solved with c038c4941543c8e81d2000bae4b25098ec0820a0.
