### ISSUE TITLE
Export 32bit/64bit FMU

### ISSUE THREAD

**Issue by a-moeller** [CATIA-Systems/FMIKit-Simulink#95]
I am working with Matlab R2018a and installed FMIKit-2.6. and cmake-3.16.0-rc3-win64-x64.  The generation of 64-bit FMU works fine. Until now I could not find the right settings to build 32-bit FMU's.  Can  anyone help me to find the right settings?
Thanks
![FMIKit](https://user-images.githubusercontent.com/57756972/68858727-f40d2100-06e5-11ea-8291-c354e618f611.png)

**Comment by fajansen** [comment]
You need to use a 32bit Matlab version to create 32bit FMUs

**Comment by a-moeller** [comment]
Thanks a lot for your help.
One additional question: Which would be the right way for generation f FMUs on Xeno / Linus OS ?

**Comment by t-sommer** [comment]
> You need to use a 32bit Matlab version to create 32bit FMUs

This is not a requirement for `grtfmi.tlc`. You can select a 32-bit Visual Studio generator (without "Win64") to generate a 32-bit FMU. Please let us know if this does not work with your CMake version.

**Comment by t-sommer** [comment]
> Which would be the right way for generation f FMUs on Xeno / Linus OS ?

You can export source code FMUs with `grtfmi.tlc` and compile them on the target platform e.g. with [FMPy](https://github.com/CATIA-Systems/FMPy):

`fmpy compile MyModel.fmu`

**Comment by a-moeller** [comment]
Update...

32bit: I could successfully build a 32bit FMU by setting "Visual Studio 14 2015" instead of "Visual Studio 14 2015 Win64" (Matlab -> Code -> Code generation options -> FMI settings -> CMake generator).

Linux: Torsten, can you please describe the steps in more detail? Sorry, I have no experience with it.

Thanks again for your help

**Comment by t-sommer** [comment]
> Linux: Torsten, can you please describe the steps in more detail?

1. [Install FMPy](https://github.com/CATIA-Systems/FMPy#installation)
2. Export an FMU with `grtfmi.tlc` (make sure "Include sources in FMU" is checked)
3. On the command change to the folder that contains the FMU and run `fmpy compile NameOfThe.fmu`

**Comment by a-moeller** [comment]
Get a lot of error messages like...
c1: fatal error C1083: Cannot open source file: 'rt_logging.c': No such file or directory 
etc

![errormessages](https://user-images.githubusercontent.com/57756972/69350886-a743c000-0c7a-11ea-9dfb-ddb2e4def746.png)

**Comment by t-sommer** [comment]
@a-moeller, have you tried the latest version of `develop`?

**Comment by a-moeller** [comment]
Installed FMPy-0.2.14-py2.py3-none-any.whl with python -m pip install --no-deps FMPy...

**Comment by t-sommer** [comment]
I mean the version of FMI Kit you used to export the FMU.

**Comment by a-moeller** [comment]
FMIKit-2.6

**Comment by t-sommer** [comment]
@a-moeller, can you please try again with the latest version of the [grt-bus-io](https://github.com/CATIA-Systems/FMIKit-Simulink/tree/grtfmi-bus-io) branch?

**Comment by a-moeller** [comment]
@t-sommer, can you please tell me how to install such a branch version?

**Comment by t-sommer** [comment]
To try it out
 - download and extract [the code](https://github.com/CATIA-Systems/FMIKit-Simulink/archive/grtfmi-bus-io.zip)
- in MATLAB, add the `grtfmi` folder to your MATLAB path
- export the model as an FMU using `grtfmi.tlc`

**Comment by a-moeller** [comment]
Thanks...
...\CATIA_FMIKIT_branch\FMIKit-Simulink-grtfmi-bus-io\grtfmi\fmi2Functions.c(452): error C2039: 'Timing': is not a member of 'tag_RTM_a_plus_b_T'  (Matlab R2018a)

**Comment by t-sommer** [comment]
To work around this problem, you can add an Integrator block to you model, so it's not purely discrete.

**Comment by a-moeller** [comment]
Build process completed successfully   ... Perfect !

Now I can come back to the original task to generate FMUs for Win32bit, Win64bit and Linux32bit. 
How can I do it? Win32bit and Win64bit with Matlab by choosing the right generator? What about Linux32b

Ist it possible to generate all the variants with FMPy?

**Comment by t-sommer** [comment]
> Ist it possible to generate all the variants with FMPy?

Generally, yes. FMPy will compile a matching binary for the current Python installation ( e.g. `win32` for a 32-bit Python on Windows).

**Comment by a-moeller** [comment]
Update ...

In the meantime tried to build FMU from source code. 
Unfortunately I get the following message during build (IPG/CarMaker):
![BuildFMU](https://user-images.githubusercontent.com/57756972/70726781-eb1c6900-1cfe-11ea-8be5-2372fd4a0ac0.png)

...and the following error message at beginning of the simulation:
![CarMaker](https://user-images.githubusercontent.com/57756972/70726845-fff8fc80-1cfe-11ea-9661-6dcbc78e55bd.png)

Torsten, do you have idea what can be wrong?
