### ISSUE TITLE
UX request: Allow for an "*.FMU" File type filter when loading FMUs 

### ISSUE THREAD

**Issue by TYanni** [CATIA-Systems/FMIKit-Simulink#98]
Requesting to change the default "Files of type" filter to "*.FMU"?

![FMIKit_FMU_Filter](https://user-images.githubusercontent.com/49491725/69189037-a92b4900-0aeb-11ea-9028-139b12f13995.jpg)

**Comment by t-sommer** [comment]
This filter is already implemented on `develop` and will be part of the next release.
