### ISSUE TITLE
Using non-ASCII characters in Simulink block names creates invalid FMU

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMIKit-Simulink#99]
When exporting a model that contains blocks with non ASCII characters (e.g. µ) the character is not properly encoded in the ModelDescription.xml when block outputs are enabled.
FMPy reports "Input is not proper UTF-8, indicate encoding !"

**Comment by t-sommer** [comment]
Solved with eef750b4ad6d179c3da050ac55f83e7229529472
